---
permalink: windows/concept_preparing_to_upgrade_snapmanager_for_oracle.html 
sidebar: sidebar 
keywords: environment, software, hardware, browser, database, operating, system, preparing 
summary: 'L"environnement dans lequel vous souhaitez mettre à niveau SnapManager doit répondre à une configuration logicielle, matérielle, navigateur, base de données et système d"exploitation spécifique. Pour obtenir les dernières informations sur la configuration requise, consultez la matrice d"interopérabilité.' 
---
= Préparation à la mise à niveau de SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'environnement dans lequel vous souhaitez mettre à niveau SnapManager doit répondre à une configuration logicielle, matérielle, navigateur, base de données et système d'exploitation spécifique. Pour obtenir les dernières informations sur la configuration requise, consultez la matrice d'interopérabilité.

Vous devez vous assurer d'effectuer les tâches suivantes avant de procéder à la mise à niveau :

* Effectuez les tâches de préinstallation requises.
* Téléchargez le pack d'installation SnapManager le plus récent pour Oracle.
* Installez et configurez la version appropriée de SnapDrive pour Windows sur tous les hôtes cibles.
* Créez une sauvegarde de la base de données de référentiel SnapManager pour Oracle existante.


http://support.netapp.com/NOW/products/interoperability/["Matrice d'interopérabilité : support.netapp.com/NOW/products/interoperability"]
