---
permalink: windows/concept_snapmanger_limitations_for_clustered_data_ontap.html 
sidebar: sidebar 
keywords: limitation, functionalities, functionality, operation, cluster, data, ontap 
summary: Vous devez connaître les limites de certaines fonctionnalités et de certaines opérations SnapManager si vous utilisez clustered Data ONTAP. 
---
= Limitations de SnapManager pour clustered Data ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez connaître les limites de certaines fonctionnalités et de certaines opérations SnapManager si vous utilisez clustered Data ONTAP.

Les fonctionnalités suivantes ne sont pas prises en charge si vous utilisez SnapManager sur clustered Data ONTAP :

* Mappage de périphériques RAW device (RDM) Logical Unit Number (LUN) pour les machines virtuelles de stockage (SVM)
* Base de données dans laquelle une LUN appartient à un système exécutant Data ONTAP sous 7-mode, et l'autre LUN appartient à un système exécutant clustered Data ONTAP
* SnapManager pour Oracle ne prend pas en charge la migration d'un vServer, qui n'est pas pris en charge par clustered Data ONTAP
* SnapManager pour Oracle ne prend pas en charge la fonctionnalité clustered Data ONTAP 8.2.1 afin de spécifier différentes règles d'exportation pour les volumes et les qtrees

