---
permalink: windows/concept_prerequisites_for_performing_rolling_upgrade.html 
sidebar: sidebar 
keywords: perform, roll, upgrade, prerequisite, environment, certain, requirement 
summary: Avant de procéder à une mise à niveau propagée, vous devez vous assurer que votre environnement répond à certaines exigences. 
---
= Conditions préalables pour effectuer une mise à niveau propagée
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de procéder à une mise à niveau propagée, vous devez vous assurer que votre environnement répond à certaines exigences.

* Si vous utilisez une version antérieure à SnapManager 3.1 et que vous souhaitez effectuer une mise à niveau par roulement vers SnapManager 3.3 ou une version ultérieure, vous devez d'abord effectuer la mise à niveau vers 3.2, puis vers la dernière version.
+
Vous pouvez directement effectuer la mise à niveau de SnapManager 3.2 vers SnapManager 3.3 ou version ultérieure.

* Les scripts externes utilisés pour réaliser une protection externe ou la conservation des données doivent être sauvegardés.
* La version SnapManager à laquelle vous souhaitez mettre à niveau doit être installée.
+

NOTE: Si vous effectuez une mise à niveau depuis une version antérieure à SnapManager 3.1 vers SnapManager 3.3 ou ultérieure, vous devez d'abord installer SnapManager 3.2 et effectuer une mise à niveau par roulement. Après la mise à niveau vers 3.2, vous pouvez installer SnapManager 3.3 ou version ultérieure et effectuer une autre mise à niveau par roulement vers SnapManager 3.3 ou version ultérieure.

* La version de SnapDrive pour Windows prise en charge avec la version de SnapManager à laquelle vous souhaitez effectuer la mise à niveau doit être installée.
+
Pour plus d'informations sur l'installation de SnapDrive, reportez-vous à la documentation SnapDrive.

* La base de données du référentiel doit être sauvegardée.
* L'utilisation du référentiel SnapManager doit être minimale.
* Si l'hôte à mettre à niveau utilise un référentiel, les opérations SnapManager ne doivent pas être effectuées sur les autres hôtes qui utilisent le même référentiel.
+
Les opérations planifiées ou en cours d'exécution sur les autres hôtes attendent la fin de la mise à niveau propagée.

* Les profils qui pointent vers la même base de données de référentiel doivent être créés avec des noms différents dans les hôtes du serveur SnapManager.
+
Si vous utilisez des profils portant le même nom, la mise à niveau propagée impliquant cette base de données de référentiel échoue sans avertissement.

* Les opérations SnapManager ne doivent pas être effectuées sur l'hôte mis à niveau.



NOTE: Cette mise à niveau est plus longue lorsque le nombre de sauvegardes des hôtes mis à niveau ensemble augmente. La durée de la mise à niveau peut varier en fonction du nombre de profils et de sauvegardes associés à un hôte donné.

*Informations connexes*

xref:task_installing_snapmanager_for_oracle.adoc[Installation de SnapManager pour Oracle]

http://mysupport.netapp.com/["Documentation sur le site de support NetApp : mysupport.netapp.com"]
