---
permalink: windows/reference_the_smosmsap_storage_rename_command.html 
sidebar: sidebar 
keywords: command, update, name, ip, address, storage, system, rename, smo 
summary: 'Cette commande met à jour le nom ou l"adresse IP du système de stockage.' 
---
= Commande smo Storage rename
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande met à jour le nom ou l'adresse IP du système de stockage.



== Syntaxe

[listing]
----

        smo storage rename
-profile profile
-oldname old_storage_name
-newname new_storage_name
\[-quiet \| -verbose\]
----


== Paramètres

* profil **
+
Spécifie le nom du profil. Ce nom peut comporter jusqu'à 30 caractères et doit être unique au sein de l'hôte.

* *-oldname ancien_storage_name*
+
Spécifie l'adresse IP ou le nom du système de stockage avant de renommer le système de stockage. Vous devez saisir l'adresse IP ou le nom du système de stockage qui s'affiche lorsque vous exécutez la commande smo Storage list.

* *-newname new_storage_name*
+
Spécifie l'adresse IP ou le nom du système de stockage après le changement de nom du système de stockage.

* *-calme*
+
Affiche uniquement les messages d'erreur dans la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche les messages d'erreur, d'avertissement et d'information dans la console.





== Exemple

L'exemple suivant utilise la commande smo Storage rename pour renommer le système de stockage :

[listing]
----
smo storage rename -profile mjullian -oldname lech -newname hudson -verbose
----