---
permalink: windows/reference_the_smosmsap_password_reset_command.html 
sidebar: sidebar 
keywords: run, password, reset, command, profile, smo 
summary: 'Vous pouvez exécuter la commande de réinitialisation de mot de passe pour réinitialiser le mot de passe d"un profil.' 
---
= Commande smo password reset
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter la commande de réinitialisation de mot de passe pour réinitialiser le mot de passe d'un profil.



== Syntaxe

[listing]
----

        smo password reset
-profile profile
\[-profile-password profile_password\]
\[-repository-hostadmin-password repository_hostadmin_password\]
[-quiet | -verbose]
----


== Paramètres

* profil **
+
Indique le nom du profil pour lequel vous souhaitez réinitialiser le mot de passe.

* *-profil-mot_de_passe profil*
+
Spécifie le nouveau mot de passe pour le profil.

* *-repository-hostadmin-mot_de_passe_admin*
+
Spécifie les informations d'identification de l'utilisateur autorisé avec le privilège administrateur local pour la base de données du référentiel.

* *-calme*
+
Affiche uniquement les messages d'erreur dans la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche les messages d'erreur, d'avertissement et d'information dans la console.


