---
permalink: windows/reference_the_smosmsapbackup_create_command.html 
sidebar: sidebar 
keywords: run, backup, create, command, database, storage, system, smo 
summary: Vous pouvez exécuter la commande backup create pour créer des sauvegardes de base de données sur un ou plusieurs systèmes de stockage. 
---
= Commande smo backup create
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter la commande backup create pour créer des sauvegardes de base de données sur un ou plusieurs systèmes de stockage.



== Syntaxe


NOTE: Avant d'exécuter cette commande, vous devez créer un profil de base de données à l'aide de la commande profile create.

[listing]
----

        smo backup create
-profile profile_name
{\[-full\{-auto \| -online \| -offline\}\[-retain \{-hourly \| -daily \| -weekly \| -monthly \| -unlimited\} \[-verify\]  |
\[-data \[\[-files files \[files\]\] \|
\[-tablespaces tablespaces \[tablespaces\]\] \[-label label\] \{-auto \| -online \| -offline\}
\[-retain \{-hourly \| -daily \| -weekly \| -monthly \| -unlimited\} \[-verify\] |
\[-archivelogs \[-label label\]\] \[-comment comment\]}

\[-backup-dest path1 \[ , path2\]\]
\[-exclude-dest path1 \[ , path2\]\]
\[-prunelogs \{-all \| -until-scn until-scn \| -until-date yyyy-MM-dd:HH:mm:ss\] \| -before \{-months \| -days \| -weeks \| -hours}}
-prune-dest prune_dest1,\[prune_dest2\]\]
\[-taskspec taskspec\]
\[-dump\]
-force
\[-quiet \| -verbose\]
----


== Paramètres

* *-profil nom_profil*
+
Indique le nom du profil associé à la base de données à sauvegarder. Le profil contient l'identifiant de la base de données et d'autres informations sur la base de données.

* *-auto option*
+
Si la base de données est dans un état monté ou hors ligne, SnapManager effectue une sauvegarde hors ligne. Si la base de données est à l'état ouvert ou en ligne, SnapManager effectue une sauvegarde en ligne. Si vous utilisez l'option -force avec l'option -offline, SnapManager force une sauvegarde hors ligne, même si la base de données est actuellement en ligne.

* *-option en ligne*
+
Spécifie une sauvegarde de base de données en ligne.

+
** Si l'instance locale est à l'état d'arrêt et qu'au moins une instance est à l'état ouvert, vous pouvez utiliser l'option -force pour changer l'instance locale à l'état monté.
** Si aucune instance n'est à l'état ouvert, vous pouvez utiliser l'option -force pour changer l'instance locale à l'état ouvert.


* *-hors ligne option*
+
Spécifie une sauvegarde hors ligne lorsque la base de données est à l'état d'arrêt. Si la base de données est à l'état ouvert ou monté, la sauvegarde échoue. Si l'option -force est utilisée, SnapManager tente de modifier l'état de la base de données pour arrêter la base de données pour une sauvegarde hors ligne.

* *-option complète*
+
Sauvegarde l'intégralité de la base de données. Cela inclut toutes les données, le journal archivé et les fichiers de contrôle. Les journaux de reprise archivés et les fichiers de contrôle sont sauvegardés quel que soit le type de sauvegarde que vous effectuez. Pour sauvegarder uniquement une partie de la base de données, utilisez l'option -files ou -tablespaces.

* *-option de données*
+
Spécifie les fichiers de données.

* *-liste de fichiers*
+
Sauvegarde uniquement les fichiers de données spécifiés, ainsi que les fichiers de journal et de contrôle archivés. Séparez la liste des noms de fichiers par des espaces. Si la base de données est à l'état ouvert, SnapManager vérifie que les espaces de stockage appropriés sont en mode de sauvegarde en ligne.

* *-espaces de stockage*
+
Sauvegarde uniquement les espaces de stockage de base de données spécifiés ainsi que les fichiers de journal et de contrôle archivés. Séparez les noms des espaces de table. Si la base de données est à l'état ouvert, SnapManager vérifie que les espaces de stockage appropriés sont en mode de sauvegarde en ligne.

* *-étiquette*
+
Spécifie un nom facultatif pour cette sauvegarde. Ce nom doit être unique dans le profil. Le nom peut contenir des lettres, des chiffres, des traits de soulignement (_) et des traits d'Union (-). Il ne peut pas commencer par un tiret. Si vous ne spécifiez pas d'étiquette, SnapManager crée une étiquette par défaut au format Scope_type_date :

+
** La portée est soit F pour indiquer une sauvegarde complète, soit P pour indiquer une sauvegarde partielle.
** Le type est C pour indiquer une sauvegarde hors ligne (à froid), H pour indiquer une sauvegarde en ligne (à chaud) ou A pour indiquer une sauvegarde automatique, par exemple P_A_20081010060037IST.
** Date correspond à l'année, au mois, au jour et à l'heure de la sauvegarde.
+
SnapManager utilise une horloge de 24 heures.



+
Par exemple, si vous avez effectué une sauvegarde complète avec la base de données hors ligne le 16 janvier 2007 16, à 5 h 45 Heure normale de l'est, SnapManager créerait l'étiquette F_C_20070116174516EST.

* *-chaine de commentaire*
+
Spécifie un commentaire facultatif décrivant cette sauvegarde. Placez la chaîne entre guillemets (').

+

NOTE: Certaines coques détournant les guillemets. Dans ce cas, vous devez inclure le guillemets avec une barre oblique inverse (\). Par exemple, vous devrez peut-être saisir les informations suivantes : `\' this is a comment\'`.

* *-vérifier option*
+
Vérifie que les fichiers de la sauvegarde ne sont pas corrompus en exécutant l'utilitaire dbv d'Oracle.

+

NOTE: Si vous spécifiez l'option -verify, l'opération de sauvegarde n'est pas terminée tant que l'opération de vérification n'est pas terminée.

* *-force option*
+
Force un changement d'état si la base de données n'est pas à l'état correct. Par exemple, SnapManager peut passer de l'état en ligne de la base de données à l'état hors ligne, en fonction du type de sauvegarde que vous spécifiez et de l'état dans lequel la base de données est.

+
** Si l'instance locale est à l'état d'arrêt et qu'au moins une instance est à l'état ouvert, l'utilisation de l'option -force fait passer l'instance locale à l'état monté.
** Si aucune instance n'est à l'état ouvert, l'utilisation de l'option -force change l'instance locale à l'état ouvert.


* *-calme*
+
Affiche uniquement les messages d'erreur dans la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche les messages d'erreur, d'avertissement et d'information dans la console.

* *-conserver { -horaire | -quotidien | -hebdomadaire | -mensuel | -illimité}*
+
Indique si la sauvegarde doit être conservée toutes les heures, tous les jours, toutes les semaines, tous les mois ou sans limite. Si l'option -retain n'est pas spécifiée, la classe de rétention prend par défaut l'option -hourly. Pour conserver des sauvegardes permanentes, utilisez l'option -Unlimited. L'option -Unlimited rend la sauvegarde inéligible à la suppression par la stratégie de rétention.

* *-archiveils option*
+
Crée une sauvegarde du journal d'archivage.

* *-backup-dest path1, [, [path2]]*
+
Spécifie les destinations du journal d'archivage à sauvegarder pour la sauvegarde du journal d'archivage.

* *-exclude-dest path1, [, [path2]]*
+
Spécifie les destinations du journal d'archivage à exclure de la sauvegarde.

* *-prunelogs {-all | -jusqu'à-sscnto-scn | -jusqu'à-dateyyyy-MM-DD:HH:mm:ss | -avant {-mois | -jours | -semaines | -heures}*
+
Supprime les fichiers journaux d'archive des destinations du journal d'archivage en fonction des options fournies lors de la création d'une sauvegarde. L'option -all supprime tous les fichiers journaux d'archive des destinations du journal d'archivage. L'option -jusqu'à-scn supprime les fichiers journaux d'archive jusqu'à ce qu'un numéro de changement système (SCN) spécifié soit supprimé. L'option -jusqu'à-date supprime les fichiers journaux d'archive jusqu'à la période spécifiée. L'option -before supprime les fichiers journaux d'archive avant la période spécifiée (jours, mois, semaines, heures).

* *-prune-dest prune_dest1,prune_dest2*
+
Supprime les fichiers journaux d'archive des destinations du journal d'archivage lors de la création de la sauvegarde.

* *-taskspspspspspspspspspspspspsp
+
Spécifie le fichier XML de spécification de tâche qui peut être utilisé pour l'activité de prétraitement ou de post-traitement de l'opération de sauvegarde. Le chemin complet du fichier XML doit être fourni tout en donnant l'option -taskspspspspspspspspspec.

* *-option de vidage*
+
Collecte les fichiers de vidage après une opération de sauvegarde de base de données réussie ou ayant échoué.





== Exemple de commande

La commande suivante crée une sauvegarde en ligne complète, crée une sauvegarde sur un stockage secondaire et définit la stratégie de conservation sur tous les jours :

[listing]
----
smo backup create -profile SALES1 -full -online
-label full_backup_sales_May -profile SALESDB -force -retain -daily
Operation Id [8abc01ec0e79356d010e793581f70001] succeeded.
----
*Informations connexes*

xref:task_creating_database_backups.adoc[Création de sauvegardes de base de données]

xref:reference_the_smosmsapprofile_create_command.adoc[Commande smo profile create]
