---
permalink: windows/reference_how_to_locate_dump_files.html 
sidebar: sidebar 
keywords: dump, file, locate, client, system, easy, access, file, helpful, troubleshoot, problem, profile, system, operation 
summary: Le fichier dump est situé sur le système client pour un accès facile. Ces fichiers sont utiles si vous devez résoudre un problème lié au profil, au système ou à toute opération. 
---
= Comment localiser les fichiers de vidage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le fichier dump est situé sur le système client pour un accès facile. Ces fichiers sont utiles si vous devez résoudre un problème lié au profil, au système ou à toute opération.

Le fichier dump se trouve dans le répertoire home de l'utilisateur sur le système client.

* Si vous utilisez l'interface utilisateur graphique, le fichier dump se trouve à l'adresse suivante :
+
[listing]
----
user_home\Application Data\NetApp\smo\3.3.0\smo_dump dump_file_type_name
server_host.jar
----
* Si vous utilisez l'interface de ligne de commande, le fichier dump est situé à l'adresse :
+
[listing]
----
user_home\.netapp\smo\3.3.0\smo_dump_dump_file_type_name server_host.jar
----


Le fichier dump contient la sortie de la commande dump. Le nom du fichier dépend des informations fournies. Le tableau suivant présente les types d'opérations de vidage et les noms de fichiers obtenus :

|===


| Type d'opération de vidage | Nom de fichier résultant 


 a| 
Opération dump commande avec l'ID d'opération
 a| 
smo_dump_operation-id.jar



 a| 
Opération dump commande sans ID d'opération
 a| 
Opération smo dump -profil VH1-détaillé les valeurs de sortie suivantes sont affichées :

[listing]
----
smo operation dump -profile VH1 -verbose
[ INFO] SMO-13048: Dump Operation Status: SUCCESS
[ INFO] SMO-13049: Elapsed Time: 0:00:01.404
Dump file created.
Path: user_home\Application Data\ontap\smo\3.3.0\smo_dump_VH1_kaw.rtp.foo.com.jar
----


 a| 
Commande System dump
 a| 
smo_dump_host-name.jar



 a| 
Commande de vidage de profil
 a| 
smo_dump_profile-name_host-name.jar

|===