---
permalink: windows/reference_the_smosmsapbackup_unmount_command.html 
sidebar: sidebar 
keywords: run, backup, unmount, command, smo 
summary: Vous pouvez exécuter la commande backup unmount pour démonter une sauvegarde. 
---
= La commande smo backup uncuncloud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter la commande backup unmount pour démonter une sauvegarde.



== Syntaxe

[listing]
----

        smo backup unmount
-profile profile_name
[-label label \[-data \| -archivelogs\] \| \[-id id\]
\[-force\]
\[-dump\]
\[-quiet \| -verbose\]
----


== Paramètres

* *-profil nom_profil*
+
Indique le profil pour lequel vous souhaitez démonter une sauvegarde. Le profil contient l'identifiant de la base de données et d'autres informations sur la base de données.

* *-id*
+
Démonte la sauvegarde avec le GUID spécifié. Le GUID est généré par SnapManager lors de la création d'une sauvegarde. Vous pouvez utiliser la commande SMO backup list pour afficher le GUID pour chaque sauvegarde.

* *-étiquette*
+
Démonte la sauvegarde avec l'étiquette spécifiée.

* *-données*
+
Spécifie les fichiers de données.

* *-archiveils*
+
Spécifie les fichiers journaux d'archive.

* *-dump*
+
Collecte les fichiers de vidage après une opération de démontage réussie ou ayant échoué.

* *-force*
+
Démonte la sauvegarde, même s'il y a des problèmes lors de la libération des ressources associées à la sauvegarde. SnapManager tente de démonter la sauvegarde et de nettoyer les ressources associées. Le journal indique que l'opération de démontage a réussi, mais vous devrez peut-être nettoyer manuellement les ressources en cas d'erreurs dans le journal.

* *-calme*
+
Affiche uniquement les messages d'erreur dans la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche les messages d'erreur, d'avertissement et d'information dans la console.





== Exemple

Voici un exemple d'opération de démontage :

[listing]
----
# smo backup unmount -label test -profile SALES1 -verbose
----
[listing]
----
[INFO ]: SMO-13051: Process PID=9788
[INFO ]: SMO-13036: Starting operation Backup Unmount on host hadley.domain.private
[INFO ]: SMO-13036: Starting operation Backup Unmount on host hadley.domain.private
[INFO ]: SMO-13046: Operation GUID 8abc015738849a3d0138849a43900001 starting on Profile FAS_P1
[INFO ]: SD-00031: Beginning to disconnect filesystem(s) [C:\SnapManager_auto_mounts\H-2012071400592312_0, C:\SnapManager_auto_mounts\I-2012071400592328_0].
[INFO ]: SD-00032: Finished disconnecting filesystem(s) [C:\SnapManager_auto_mounts\H-2012071400592312_0, C:\SnapManager_auto_mounts\I-2012071400592328_0].
[INFO ]: SMO-13048: Backup Unmount Operation Status: SUCCESS
[INFO ]: SMO-13049: Elapsed Time: 0:07:26.754
----
*Informations connexes*

xref:task_unmounting_backups.adoc[Démontage des sauvegardes]
