---
permalink: windows/reference_the_smosmsapcredential_delete_command.html 
sidebar: sidebar 
keywords: command, delete, credentials, particular, secured, resource, smo 
summary: 'Cette commande supprime les informations d"identification de l"utilisateur pour une ressource sécurisée particulière.' 
---
= Commande de suppression des informations d'identification smo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande supprime les informations d'identification de l'utilisateur pour une ressource sécurisée particulière.



== Syntaxe

[listing]
----

        smo credential delete
\[-host -name host_name
-username username\] \|
[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username
-port repo_port\] \|
\[-profile
-name profile_name\]
[-quiet | -verbose]
----


== Paramètres

* *-hôte_hôte*
+
Spécifie le nom du serveur hôte sur lequel SnapManager s'exécute.

+
Le paramètre -host inclut les options suivantes :

+
** -Name nom_hôte : indique le nom de l'hôte pour lequel vous allez supprimer le mot de passe.
** -Username nom_utilisateur : indique le nom d'utilisateur sur l'hôte.


* *-repository -dbname*
+
Indique le nom de la base de données qui stocke le profil. Utilisez le nom global ou le SID.

+
Le paramètre -repository inclut les options suivantes :

+
** -Dbnamerepo_service_name : indique le nom de la base de données qui stocke le profil. Utilisez le nom global ou le SID.
** -Host repo_host : indique le nom ou l'adresse IP du serveur hôte sur lequel s'exécute la base de données de référentiel.
** -Login-username repo_username : indique le nom d'utilisateur nécessaire pour accéder à la base de données qui stocke le référentiel.
** -Port repo_port : indique le numéro de port TCP utilisé pour accéder à la base de données qui stocke le référentiel.


* *-profile -name nom_profil*
+
Spécifie le profil auquel la base de données est associée.

+
Le paramètre -profile inclut l'option suivante :

+
** -Name profilName : indique le nom du profil pour lequel vous allez supprimer le mot de passe.


* *-calme*
+
Affiche uniquement les messages d'erreur sur la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche des messages d'erreur, d'avertissement et d'information sur la console.





== Exemple de commande

Cet exemple supprime les informations d'identification du profil.

[listing]
----
smo credential delete -profile -name user1 -verbose
----
[listing]
----
SMO-20022 [INFO ]: Deleted credentials and repository mapping
 for profile "user1" in user credentials for "user1".
----
Cet exemple supprime les informations d'identification du référentiel.

[listing]
----
smo credential delete -repository -dbname SMOREPO -host Host2
-login -username user1 -port 1521
----
[listing]
----
SMO-20023 [INFO ]: Deleted repository credentials for "user1@SMOREPO/wasp:1521"
and associated profile mappings in user credentials for "user1".
----
Cet exemple supprime les informations d'identification de l'hôte.

[listing]
----
smo credential delete -host -name Host2
----
[listing]
----
SMO-20033 [INFO ]: Deleted host credentials for "Host2" in user credentials for "user1".
----
*Informations connexes*

xref:task_deleting_credentials_for_individual_resources.adoc[Suppression des informations d'identification pour des ressources individuelles]
