---
permalink: windows/reference_the_smosmsapprofile_update_command.html 
sidebar: sidebar 
keywords: run, profile, update, command, information, existing, smo 
summary: 'Vous pouvez exécuter la commande de mise à jour du profil pour mettre à jour les informations d"un profil existant.' 
---
= Commande smo profile update
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter la commande de mise à jour du profil pour mettre à jour les informations d'un profil existant.



== Syntaxe

[listing]
----

        smo profile update
-profile profile
\[-new-profile new_profile_name\]
\[-profile-password profile_password\]
[-database
-dbname db_dbname
-host db_host
\[-sid db_sid\]
[-login
\[-username db_username -password db_password -port db_port\]
 ]
[\{-rman  \{-controlfile \| \{\{-login
-username  rman_username
-password  rman_password \}
\[-tnsname  tnsname\]\}\}\} \|
-remove-rman\]


[-retain
\[-hourly \[-count n\] \[-duration m\]\]
\[-daily \[-count n\] \[-duration m\]]
\[-weekly \[-count n\] \[-duration m\]]
\[-monthly \[-count n\] \[-duration m\]]]]
-comment comment
-snapname-patternpattern
[]
[-summary-notification]
[-notification
\[-success
-email email_address1,email_address2
-subject subject_pattern\]
\[-failure
-email email_address1,email_address2
-subject subject_pattern]
[-separate-archivelog-backups
-retain-archivelog-backups
-hours  hours |
-days days |
-weeks weeks |
-months months
[]
[-include-with-online-backups \| -no-include-with-online-backups]]
[-dump]
\[-quiet \| -verbose\]
----


== Paramètres

* profil **
+
Spécifie le nom du profil. Ce nom peut comporter jusqu'à 30 caractères et doit être unique au sein de l'hôte.

* *-profil-mot_de_passe profil*
+
Spécifie le mot de passe du profil.

* *-new-profile new_profile nom_profile*
+
Spécifie le nouveau nom que vous pouvez fournir pour un profil.

* *-base de données*
+
Indique les détails de la base de données que le profil décrit. Il s'agit de la base de données qui sera sauvegardée, restaurée, etc.

* *-dbname db_dbname*
+
Indique le nom de la base de données décrit par le profil. Vous pouvez utiliser le nom global ou l'identifiant système.

* *-hôte db_host*
+
Indique le nom ou l'adresse IP de l'ordinateur hôte sur lequel la base de données s'exécute.

* *-sid db_sid*
+
Indique l'identifiant système de la base de données décrit par le profil. Par défaut, SnapManager utilise le nom de la base de données comme identificateur système. Si l'identifiant système est différent du nom de la base de données, vous devez le spécifier à l'aide de l'option -sid.

* *-connexion*
+
Spécifie les détails de connexion au référentiel.

* *-username repo_username*
+
Indique le nom d'utilisateur requis pour accéder à la base de données du référentiel.

* *-port repo_port*
+
Spécifie le numéro de port TCP requis pour accéder à la base de données du référentiel.

* *-base de données*
+
Indique les détails de la base de données que le profil décrit. Il s'agit de la base de données qui sera sauvegardée, restaurée ou clonée.

* *-dbname db_dbname*
+
Indique le nom de la base de données décrit par le profil. Vous pouvez utiliser le nom global ou l'identifiant système.

* *-hôte db_host*
+
Indique le nom ou l'adresse IP de l'ordinateur hôte sur lequel la base de données s'exécute.

* *-connexion*
+
Spécifie les détails de connexion à la base de données.

* *-username db_username*
+
Indique le nom d'utilisateur requis pour accéder à la base de données décrit par le profil.

* *-mot de passe db_password*
+
Spécifie le mot de passe requis pour accéder à la base de données décrit par le profil.

* *-port db_port*
+
Spécifie le numéro de port TCP requis pour accéder à la base de données que le profil décrit.

* *-rman*
+
Spécifie les détails qu'SnapManager utilise pour cataloguer les sauvegardes avec Oracle Recovery Manager (RMAN).

* *-controlfile*
+
Spécifie les fichiers de contrôle de base de données cible au lieu d'un catalogue en tant que référentiel RMAN.

* *-connexion*
+
Spécifie les détails de connexion RMAN.

* *-mot de passe rman_mot de passe*
+
Spécifie le mot de passe utilisé pour se connecter au catalogue RMAN.

* *-username rman_username*
+
Spécifie le nom d'utilisateur utilisé pour se connecter au catalogue RMAN.

* *-tnsname nomnet*
+
Indique le nom de la connexion tnsname (défini dans le fichier tsname.ora).

* *-remove-rman*
+
Indique de supprimer RMAN sur le profil.

* *-retain [-hourly [-countn] [-duration m]] [-daily [-count n] [-duration m]] [-hebdomadaire [-count n][-duration m]] [-mensuel [-count n][-duration m]*
+
Spécifie la classe de rétention (horaire, quotidien, hebdomadaire, mensuelle) pour une sauvegarde.

+
Pour chaque classe de rétention, un nombre de rétention, une durée de rétention ou les deux peuvent être spécifiés. La durée est exprimée en unités de la classe (par exemple, heures pour l'heure ou jours pour le quotidien). Par exemple, si l'utilisateur indique uniquement une durée de conservation de 7 pour les sauvegardes quotidiennes, SnapManager ne limite pas le nombre de sauvegardes quotidiennes du profil (car le nombre de rétention est 0), mais SnapManager supprimera automatiquement les sauvegardes quotidiennes créées il y a plus de 7 jours.

* *-commentaire*
+
Spécifie le commentaire pour un profil.

* *-motif-snapname*
+
Spécifie le modèle de nom pour les copies Snapshot. Vous pouvez également inclure du texte personnalisé, par exemple HAOPS pour les opérations hautement disponibles, dans tous les noms de copie Snapshot. Vous pouvez modifier le schéma de nommage des copies Snapshot lorsque vous créez un profil ou après sa création. La mise à jour de la grille s'applique uniquement aux copies Snapshot qui n'ont pas encore eu lieu. Les copies Snapshot qui existent conservent le modèle Snapname précédent. Vous pouvez utiliser plusieurs variables dans le texte du motif.

* *-résumé-notification*
+
Indique que la notification par e-mail sommaire est activée pour le profil existant.

* *-notification [-success-email e-mail_address1,e-mail adresse 2 -subject_pattern]*
+
Active la notification par e-mail pour le profil existant afin que les e-mails soient reçus par les destinataires lorsque l'opération SnapManager réussit. Vous devez entrer une ou plusieurs adresses e-mail auxquelles les alertes e-mail seront envoyées et un modèle d'objet d'e-mail pour le profil existant.

+
Vous pouvez modifier le texte de l'objet lors de la mise à jour du profil ou inclure un objet personnalisé. L'objet mis à jour s'applique uniquement aux e-mails non envoyés. Vous pouvez utiliser plusieurs variables pour l'objet de l'e-mail.

* *-notification [-échec -email e-mail_address1,e-mail adresse 2 -subject_pattern]*
+
Active la notification par e-mail pour le profil existant afin que les e-mails soient reçus par les destinataires en cas d'échec de l'opération SnapManager. Vous devez entrer une ou plusieurs adresses e-mail auxquelles les alertes e-mail seront envoyées et un modèle d'objet d'e-mail pour le profil existant.

+
Vous pouvez modifier le texte de l'objet lors de la mise à jour du profil ou inclure un objet personnalisé. L'objet mis à jour s'applique uniquement aux e-mails non envoyés. Vous pouvez utiliser plusieurs variables pour l'objet de l'e-mail.

* *-séparé-archivelog-sauvegardes*
+
Sépare la sauvegarde du journal d'archivage de la sauvegarde des fichiers de données. Il s'agit d'un paramètre facultatif que vous pouvez fournir lors de la création du profil. Une fois les sauvegardes séparées, vous pouvez créer une sauvegarde de fichiers de données uniquement ou des journaux d'archivage uniquement.

* *-conserver-archivelog-sauvegardes -heures | -jours de repos | -semaines| -mois de semaine*
+
Indique que les sauvegardes du journal d'archivage sont conservées en fonction de la durée de conservation du journal d'archivage (horaire, quotidien, hebdomadaire, mensuel).

* *-inclure-avec-sauvegardes-en-ligne | -sans-inclure-avec-sauvegardes-en-ligne*
+
Indique que la sauvegarde du journal d'archivage est incluse avec la sauvegarde de base de données en ligne.

+
Indique que les sauvegardes du journal d'archivage ne sont pas incluses avec la sauvegarde de base de données en ligne.

* *-dump*
+
Indique que les fichiers de vidage sont collectés après l'opération de création de profil réussie.

* *-calme*
+
Affiche uniquement les messages d'erreur dans la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche les messages d'erreur, d'avertissement et d'information dans la console.





== Exemple

L'exemple suivant modifie les informations de connexion de la base de données décrites par le profil et la notification par e-mail est configurée pour ce profil :

[listing]
----
smo profile update -profile SALES1 -database -dbname SALESDB
 -sid SALESDB -login -username admin2 -password d4jPe7bw -port 1521
-host server1 -profile-notification -success -e-mail Preston.Davis@org.com -subject success
Operation Id [8abc01ec0e78ec33010e78ec3b410001] succeeded.
----
*Informations connexes*

xref:task_changing_profile_passwords.adoc[Modification des mots de passe de profil]

xref:concept_how_snapmanager_retains_backups_on_the_local_storage.adoc[SnapManager conserve les sauvegardes sur le système de stockage local]
