---
permalink: windows/reference_the_smosmsap_notification_updatesummarynotification_command.html 
sidebar: sidebar 
keywords: run, notification, update-summary-notification, command, enable, summary, repository, database, smo 
summary: Vous pouvez exécuter la commande notification de mise à jour-résumé-notification pour activer la notification de synthèse pour une base de données de référentiel. 
---
= La commande smo de notification update-summary-notification
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter la commande notification de mise à jour-résumé-notification pour activer la notification de synthèse pour une base de données de référentiel.



== Syntaxe

[listing]
----

        smo notification update-summary-notification
-repository
-port repo_port
-dbname  repo_service_name
-host repo_host
-login -username repo_username
-email email-address1,email-address2
-subject subject-pattern
-frequency
[-daily –time daily_time \|
-hourly –time hourly_time \|
-monthly –time monthly_time -date \[1\|2\|3\|...\|31\] \|
-weekly  –time weekly_time -day \[1\|2\|3\|4\|5\|6\|7\]\]
-profiles profile1,profile2
-notification-host notification-host
\[-quiet \| -verbose\]
----


== Paramètres

* *-référentiel*
+
Spécifie les détails de la base de données du référentiel.

* *-port repo_port*
+
Spécifie le numéro de port TCP utilisé pour accéder à la base de données du référentiel.

* *-dbname repo_service_name*
+
Indique le nom de la base de données du référentiel. Vous pouvez utiliser le nom global ou l'identifiant système.

* *-hôte repo_host*
+
Indique le nom ou l'adresse IP de l'hôte sur lequel réside la base de données du référentiel.

* *-connexion*
+
Spécifie les détails de connexion au référentiel. Cette option est facultative. Si ce n'est pas le cas, SnapManager utilise par défaut le mode de connexion à l'authentification OS.

* *-username repo_username*
+
Indique le nom d'utilisateur requis pour accéder à la base de données du référentiel.

* *-courriel-adresse 1,courriel-adresse 2*
+
Spécifie les adresses e-mail des destinataires.

* *-sujet-modèle*
+
Spécifie le modèle d'objet de l'e-mail.

* *-fréquence { -daily --time daily_time | -hourly --time hourly_time | -monthly --time monthly_time -date {1|2|3...|31 } | -hebdomadaire --time weekly_time -day {1|2|3|4|5|6|7 }*
+
Spécifie le type d'horaire et l'heure de planification lorsque vous souhaitez que la notification par e-mail soit envoyée.

* *-profils profile1, profile2*
+
Spécifie les noms de profil qui nécessitent une notification par e-mail.

* *-notification-hôte-notification*
+
Spécifie l'hôte du serveur SnapManager à partir duquel l'e-mail de notification de synthèse est envoyé aux destinataires. Vous pouvez fournir un nom d'hôte ou une adresse IP pour l'hôte de notification. Vous pouvez également mettre à jour l'adresse IP de l'hôte ou le nom d'hôte.

* *-calme*
+
Affiche uniquement les messages d'erreur dans la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche les messages d'erreur, d'avertissement et d'information dans la console.





== Exemple

L'exemple suivant active la notification récapitulative pour une base de données de référentiel :

[listing]
----

smo notification update-summary-notification –repository –port 1521 –dbname repo2 –host 10.72.197.133 –login –username oba5 –email admin@org.com –subject success –frequency -daily -time 19:30:45 –profiles sales1
----