---
permalink: windows/reference_the_smosmsapbackup_delete_command.html 
sidebar: sidebar 
keywords: run, backup, delete, command, remove, remove, create, clone, retention, class, smo 
summary: Vous pouvez exécuter la commande backup delete pour supprimer des sauvegardes qui ne sont pas automatiquement supprimées, comme les sauvegardes utilisées pour créer un clone ou des sauvegardes en panne. Vous pouvez supprimer les sauvegardes conservées sans limite de temps sans modifier la classe de rétention. 
---
= Commande smo backup delete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter la commande backup delete pour supprimer des sauvegardes qui ne sont pas automatiquement supprimées, comme les sauvegardes utilisées pour créer un clone ou des sauvegardes en panne. Vous pouvez supprimer les sauvegardes conservées sans limite de temps sans modifier la classe de rétention.



== Syntaxe

[listing]
----

        smo backup delete
-profile profile_name
[-label label \[-data \| -archivelogs\] \| \[-id guid \| -all\]
-force
\[-dump\]
\[-quiet \| -verbose\]
----


== Paramètres

* *-profil nom_profil*
+
Spécifie la base de données associée à la sauvegarde que vous souhaitez supprimer. Le profil contient l'identifiant de la base de données et d'autres informations sur la base de données.

* *-id guid*
+
Spécifie la sauvegarde avec le GUID spécifié. Le GUID est généré par SnapManager lors de la création d'une sauvegarde. Vous pouvez utiliser la commande SMO backup list pour afficher le GUID pour chaque sauvegarde.

* *-étiquette*
+
Spécifie la sauvegarde avec l'étiquette spécifiée. Vous pouvez également spécifier l'étendue de la sauvegarde sous forme de fichier de données ou de journal d'archivage.

* *-données*
+
Spécifie les fichiers de données.

* *-archiveils*
+
Spécifie les fichiers journaux d'archive.

* *-tous*
+
Spécifie toutes les sauvegardes. Pour supprimer uniquement les sauvegardes spécifiées, utilisez l'option -ID ou -label.

* *-dump*
+
Collecte les fichiers de vidage après une opération de suppression de sauvegarde réussie ou ayant échoué.

* *-force*
+
Force la dépose de la sauvegarde. SnapManager supprime la sauvegarde même en cas de problème pour libérer les ressources associées à la sauvegarde. Par exemple, si la sauvegarde a été cataloguée avec Oracle Recovery Manager (RMAN), mais que la base de données RMAN n'existe plus, y compris -force supprime la sauvegarde bien qu'elle ne puisse pas se connecter avec RMAN.

* *-calme*
+
Affiche uniquement les messages d'erreur dans la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche les messages d'erreur, d'avertissement et d'information dans la console.





== Exemple

L'exemple suivant illustre la suppression de la sauvegarde :

[listing]
----
smo backup delete -profile SALES1 -label full_backup_sales_May
Operation Id [8abc01ec0e79004b010e79006da60001] succeeded.
----
*Informations connexes*

xref:task_deleting_backups.adoc[Suppression de sauvegardes]

xref:reference_the_smosmsapprofile_create_command.adoc[Commande smo profile create]

xref:reference_the_smosmsapprofile_update_command.adoc[Commande smo profile update]
