---
permalink: windows/reference_error_messages.html 
sidebar: sidebar 
keywords: error, message, information, operation 
summary: 'Vous trouverez des informations sur les messages d"erreur associés aux différentes opérations de SnapManager.' 
---
= Messages d'erreur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous trouverez des informations sur les messages d'erreur associés aux différentes opérations de SnapManager.



== Messages d'erreur les plus courants

Le tableau suivant répertorie certaines des erreurs les plus courantes et les plus importantes associées à SnapManager pour Oracle :

|===


| Message d'erreur | Explication | Solution 


 a| 
SD-10038 : le système de fichiers n'est pas accessible en écriture.
 a| 
Le processus SnapManager ne possède pas d'accès en écriture au système de fichiers.
 a| 
Vous devez vous assurer que le processus SnapManager possède un accès en écriture au système de fichiers. Après avoir corrigé ceci, vous devrez peut-être prendre un autre instantané.



 a| 
SMO-05075 : impossible de créer le profil. Vous devez configurer correctement la relation DP/XDP ou choisir la règle de protection appropriée pour la relation sous-jacente.
 a| 
Les volumes sous-jacents ne font pas partie d'une relation SnapVault ou SnapMirror.
 a| 
Vous devez configurer une relation de protection des données entre les volumes source et destination et initialiser la relation.



 a| 
SMO-05503 : vous avez spécifié le même nom au profil. Spécifiez un autre nom pour renommer le profil.
 a| 
Les profils ayant des noms identiques ne peuvent pas exister dans un référentiel.
 a| 
Indiquez un nom de profil non utilisé.



 a| 
SMO-05505 : impossible de mettre à jour les métadonnées du jeu de données.
 a| 
Le jeu de données a peut-être été supprimé ou n'existe pas.
 a| 
Avant de mettre à jour les métadonnées du dataset, vérifiez qu'il existe à l'aide de la console de gestion NetApp.



 a| 
SMO-05506 : vous ne pouvez pas mettre à jour le profil car des opérations sont en cours d'exécution sur le profil. Vous devez attendre que l'opération soit terminée, puis mettre à jour le profil.
 a| 
Le profil ne peut pas être mis à jour lorsque des opérations de sauvegarde, de restauration et de clonage sont en cours.
 a| 
Mettre à jour le profil une fois l'opération en cours terminée.



 a| 
SMO-05509 : durée de conservation primaire de l'archive non valide - spécifiez une valeur entière positive.
 a| 
La durée de conservation des sauvegardes du journal d'archivage ne peut pas être négative.
 a| 
Spécifiez une valeur positive pour la durée de conservation des sauvegardes du journal d'archivage.



 a| 
SMO-07463 : cette restauration de sauvegarde nécessite que la base de données soit dans l'état requis. Impossible de ramener la base de données à l'état requis.
 a| 
La base de données n'est pas dans l'état requis pour une opération de sauvegarde.
 a| 
Vérifiez que la base de données est dans un état approprié avant de créer une copie de sauvegarde. L'état de la base de données à restaurer dépend du type de processus de restauration que vous souhaitez exécuter et du type de fichiers à inclure.



 a| 
SMO-09315 : après l'opération de mise à niveau ou de mise à jour du référentiel, il se peut que vous ne receviez pas la notification récapitulative pour les notifications définies dans la version précédente, sauf si vous mettez à jour la notification récapitulative avec les détails de l'hôte de notification.
 a| 
Les paramètres de notification ne sont pas configurés pour le référentiel après une mise à niveau propagée.
 a| 
Après une mise à niveau propagée, mettez à jour les paramètres de notification récapitulative pour recevoir les notifications.



 a| 
SM0-02076 : le nom du libellé ne doit pas contenir de caractères spéciaux autres que le trait de soulignement.
 a| 
Le nom de l'étiquette contient des caractères spéciaux autres que le trait de soulignement.
 a| 
Le nom du libellé doit être unique dans le profil. Le nom peut contenir des lettres, des chiffres, un trait de soulignement (_) et un tiret (-) (mais ne peut pas commencer par un tiret). Assurez-vous que les étiquettes ne contiennent pas de caractères spéciaux, à l'exception du trait de soulignement.



 a| 
SMO-06308 : exception lors de la tentative de démarrage du programme : java.lang.NullPointerException
 a| 
Le nom de domaine complet (FQDN) de l'hôte de profil est configuré à la place du nom d'hôte du système et le FQDN de l'hôte de profil ne peut pas être résolu.
 a| 
Assurez-vous d'utiliser le nom d'hôte du système et non le nom de domaine complet.



 a| 
Échec dans ExecuteRestoreSteps: ORACLE-10003: Erreur exécutant SQL "DROP DISKGROUP;control diskgroup nom; INCLUDE CONTENU" sur la base de données Oracle +ASM1: ORA-15039: diskgroup pas supprimé ORA-15027: Utilisation active du groupe de disques; "control diskgroup nom;" exclut son démontage
 a| 
L'opération de restauration d'une sauvegarde avec des fichiers de contrôle ne parvient pas à supprimer le groupe de disques de contrôle. Ce problème se produit si des fichiers de contrôle sont déjà sauvegardés dans le groupe de disques de contrôle.
 a| 
Identifiez les fichiers de contrôle obsolètes sauvegardés et supprimez-les manuellement.



 a| 
RMAN-06004 : erreur ORACLE de la base de données du catalogue de récupération : ORA-01424 : caractère manquant ou illégal suivant le caractère d'échappement
 a| 
L'opération de création de sauvegarde n'a pas pu supprimer la copie de sauvegarde du catalogue lorsqu'SnapManager est intégré à RMAN.
 a| 
Vérifiez si des scripts externes sont utilisés pour supprimer les sauvegardes de RMAN. Exécutez la commande CROSSCHECK BACKUP dans RMAN pour mettre à jour le référentiel RMAN et la commande resynchroniser le catalogue pour synchroniser le fichier de contrôle de la base de données cible avec le catalogue de récupération.



 a| 
[DEBUG] : exception lors de l'élagage de la sauvegarde. java.lang.IllegalStateException: [Assertion failed] - cet invariant d'état doit être vrai
 a| 
Plusieurs copies Snapshot sont créées pour un ID d'opération unique.
 a| 
Supprimez manuellement les copies Snapshot et utilisez des scripts pour supprimer les entrées du référentiel.



 a| 
L'heure système et l'heure affichées par SnapManager dans les fichiers journaux ne correspondent pas ou ne sont pas synchronisées.
 a| 
Une modification de fuseau horaire n'est pas encore prise en charge par Java 7.
 a| 
Appliquez le correctif tzupdater fourni par Oracle.



 a| 
DISQUE-00001 : Impossible de détecter le stockage : l'identificateur suivant n'existe pas ou n'est pas du type attendu : fichier ASM
 a| 
Les fichiers de données ou de contrôle ou les journaux de reprise sont multiplexés dans une base de données ASM.
 a| 
Retirez le multiplexage Oracle.



 a| 
ORA-01031: Privilèges insuffisants. Vérifiez que le service Windows de SnapManager est configuré pour s'exécuter en tant qu'utilisateur avec les privilèges appropriés et que l'utilisateur est inclus dans LE groupe ORA_DBA.
 a| 
Vous ne disposez pas des privilèges suffisants dans SnapManager. Le compte de service SnapManager ne fait pas partie du groupe ORA_DBA.
 a| 
Cliquez avec le bouton droit de la souris sur l'icône *Computer* de votre bureau et sélectionnez *Manage* pour vérifier que le compte d'utilisateur du service SnapManager fait partie du groupe ORA_DBA. Vérifiez les utilisateurs et les groupes locaux et assurez-vous que le compte fait partie du groupe ORA_DBA. Si l'utilisateur est l'administrateur local, assurez-vous que l'utilisateur se trouve dans le groupe plutôt que l'administrateur du domaine.



 a| 
0001-SMO-02016 : il peut y avoir des tables externes dans la base de données qui ne sont pas sauvegardées dans le cadre de cette opération de sauvegarde (puisque la base de données n'a pas ÉTÉ OUVERTE pendant cette sauvegarde TOUS_EXTERNAL_LOCATIONS n'a pas pu être interrogée pour déterminer si des tables externes existent ou non).
 a| 
SnapManager ne sauvegarde pas les tables externes (par exemple, les tables qui ne sont pas stockées dans des fichiers .dbf). Ce problème survient parce que la base de données n'a pas été ouverte pendant la sauvegarde, SnapManager ne peut pas déterminer si des tables externes sont utilisées.
 a| 
Il se peut que des tables externes de la base de données ne soient pas sauvegardées dans le cadre de cette opération (car la base de données n'a pas été ouverte pendant la sauvegarde).



 a| 
0002-332 erreur administrative : impossible de vérifier SD.snapshot.Clone accès sur le volume « volume_name » pour le nom d'utilisateur utilisateur sur Operations Manager Server « dfm_Server ». Motif : ressource spécifiée non valide. Impossible de trouver son ID sur le serveur Operations Manager « dfm_Server »
 a| 
Les privilèges d'accès et les rôles appropriés ne sont pas définis.
 a| 
Définissez les privilèges d'accès ou les rôles pour les utilisateurs qui tentent d'exécuter la commande.



 a| 
[WAREN] FLOW-11011 : opération abandonnée [ERROR] FLOW-11008 : échec de l'opération : espace de tas Java.
 a| 
Il y a plus de fichiers journaux d'archive dans la base de données que le maximum autorisé.
 a| 
. Accédez au répertoire d'installation de SnapManager.
. Ouvrez le fichier Launch-Java.
. Augmenter la valeur de `java -Xmx160m` Paramètre d'espace mémoire Java . Par exemple, vous pouvez modifier la valeur par défaut de 160m à 200m comme `java -Xmx200m`.




 a| 
SMO-21019 : échec de l'élagage du journal des archives pour la destination : « E:\dest » pour la raison : « ORACLE-00101 : erreur lors de l'exécution de la commande RMAN : [DELETE NOPROMPT ARCHIVELOG 'E:\dest']
 a| 
L'élagage du journal d'archivage échoue dans l'une des destinations. Dans un tel scénario, SnapManager continue de nettoyer les fichiers journaux d'archive des autres destinations. Si des fichiers sont supprimés manuellement du système de fichiers actif, RMAN ne parvient pas à nettoyer les fichiers journaux d'archive de cette destination.
 a| 
Connectez-vous à RMAN à partir de l'hôte SnapManager. Exécutez la commande RMAN CROSSCHECK ARCHIVELOG ALL et exécutez à nouveau l'opération d'élagage des fichiers journaux d'archive.



 a| 
SMO-13032 : impossible d'exécuter l'opération : archive log Prune. Cause principale : exception RMAN : ORACLE-00101 : erreur lors de l'exécution de la commande RMAN.
 a| 
Les fichiers journaux d'archives sont supprimés manuellement des destinations du journal d'archivage.
 a| 
Connectez-vous à RMAN à partir de l'hôte SnapManager. Exécutez la commande RMAN CROSSCHECK ARCHIVELOG ALL et exécutez à nouveau l'opération d'élagage des fichiers journaux d'archive.



 a| 
Impossible d'analyser la sortie du shell : (java.util.regex.Matcher[pattern=commande terminée. Region=0,18 lastmatch=]) ne correspond pas (name:backup_script) Impossible d'analyser la sortie du shell : (java.util.regex.Matcher[Pattern=Command Complete. region=0,25 lastmatch=]) ne correspond pas (description:script de sauvegarde)

Impossible d'analyser la sortie du shell : (java.util.regex.Matcher[pattern=commande terminée. region=0,9 lastmatch=]) ne correspond pas (timeout:0)
 a| 
Les variables d'environnement ne sont pas définies correctement dans les scripts de pré-tâche ou de post-tâche.
 a| 
Vérifiez si les scripts de pré-tâche ou post-tâche suivent la structure standard du plug-in SnapManager. Pour plus d'informations sur l'utilisation des variables d'environnement dans le script, reportez-vous à la section xref:concept_operations_in_task_scripts.adoc[Opérations dans les scripts de tâches].



 a| 
ORA-01450 : longueur maximale de clé (6398) dépassée.
 a| 
Lorsque vous effectuez une mise à niveau de SnapManager 3.2 pour Oracle vers SnapManager 3.3 pour Oracle, l'opération de mise à niveau échoue avec ce message d'erreur. Ce problème peut survenir pour l'une des raisons suivantes :

* La taille de bloc de l'espace table dans lequel le référentiel existe est inférieure à 8 Ko.
* Le paramètre nls_length_sémantique est défini sur char.

 a| 
Vous devez affecter les valeurs aux paramètres suivants :

* block_size=8192
* nls_length=octet


Après avoir modifié les valeurs des paramètres, vous devez redémarrer la base de données.

Pour en savoir plus, consultez l'article 2017632 de la base de connaissances.

|===


== Messages d'erreur associés au processus de sauvegarde de la base de données (série 2000)

Le tableau suivant répertorie les erreurs courantes associées au processus de sauvegarde de la base de données :

|===


| Message d'erreur | Explication | Solution 


 a| 
SMO-02066 : vous ne pouvez pas supprimer ni libérer les « journaux de données » de sauvegarde du journal d'archivage car la sauvegarde est associée aux « journaux de données » de sauvegarde des données.
 a| 
La sauvegarde du journal d'archivage est effectuée avec la sauvegarde des fichiers de données et vous avez tenté de supprimer la sauvegarde du journal d'archivage.
 a| 
Utilisez l'option -force pour supprimer ou libérer la sauvegarde.



 a| 
SMO-02067 : vous ne pouvez pas supprimer ou libérer les « journaux de données » de sauvegarde du journal d'archivage car la sauvegarde est associée aux « journaux de données » de sauvegarde des données et se situe dans la durée de conservation attribuée.
 a| 
La sauvegarde du journal d'archivage est associée à la sauvegarde de la base de données et se situe dans la période de rétention, et vous avez tenté de supprimer la sauvegarde du journal d'archivage.
 a| 
Utilisez l'option -force pour supprimer ou libérer la sauvegarde.



 a| 
SMO-07142 : journaux archivés exclus du modèle d'exclusion <exclusion>.
 a| 
Vous excluez certains fichiers journaux d'archives pendant l'opération de création de profil ou de sauvegarde.
 a| 
Aucune action n'est requise.



 a| 
SMO-07155 : <count> les fichiers journaux archivés n'existent pas dans le système de fichiers actif. Ces fichiers journaux archivés ne seront pas inclus dans la sauvegarde.
 a| 
Les fichiers journaux d'archive n'existent pas dans le système de fichiers actif pendant l'opération de création de profil ou de sauvegarde. Ces fichiers journaux archivés ne sont pas inclus dans la sauvegarde.
 a| 
Aucune action n'est requise.



 a| 
SMO-07148 : les fichiers journaux archivés ne sont pas disponibles.
 a| 
Aucun fichier journal d'archivage n'est créé pour la base de données actuelle lors de l'opération de création de profil ou de création de sauvegarde.
 a| 
Aucune action n'est requise.



 a| 
SMO-07150 : les fichiers journaux archivés sont introuvables.
 a| 
Tous les fichiers journaux d'archives sont manquants dans le système de fichiers ou exclus lors de l'opération de création ou de sauvegarde de profil.
 a| 
Aucune action n'est requise.



 a| 
SMO-13032 : impossible d'effectuer l'opération : backup Create Cause principale : ORACLE-20001 : erreur lors de la tentative de modification de l'état à OUVRIR pour l'instance de base de données dfcln1 : ORACLE-20004 : en attendant de pouvoir ouvrir la base de données sans l'option RESETLOGS, mais oracle signale que la base de données doit être ouverte avec l'option RESETLOGS. Pour ne pas réinitialiser les journaux de manière inattendue, le processus ne se poursuit pas. Assurez-vous que la base de données peut être ouverte sans l'option RESETLOGS et réessayez.
 a| 
Vous essayez de sauvegarder la base de données clonée créée avec l'option -no-resetlogs. La base de données clonée n'est pas complète.toutefois, vous pouvez effectuer des opérations SnapManager telles que la création de profils et de sauvegardes, etc. Avec la base de données clonée, mais les opérations SnapManager échouent car la base de données clonée n'est pas configurée comme base de données complète.
 a| 
Restaurez la base de données clonée ou convertissez-la en base de données de secours Data Guard.

|===


== Messages d'erreur associés au processus de restauration (série 3000)

Le tableau suivant présente les erreurs courantes associées au processus de restauration :

|===


| Message d'erreur | Explication | Solution 


 a| 
SMO-03031:la spécification de restauration est nécessaire pour restaurer la sauvegarde <variable>, car les ressources de stockage pour la sauvegarde ont déjà été libérées.
 a| 
Vous avez tenté de restaurer une sauvegarde dont les ressources de stockage sont libérées sans spécifier de spécification de restauration.
 a| 
Spécifiez une spécification de restauration.



 a| 
SMO-03032:la spécification de restauration doit contenir des mappages pour les fichiers à restaurer, car les ressources de stockage de la sauvegarde ont déjà été libérées. Les fichiers qui ont besoin de mappages sont : <variable> depuis les snapshots : <variable>
 a| 
Vous avez tenté de restaurer une sauvegarde dont les ressources de stockage sont libérées ainsi qu'une spécification de restauration ne contenant pas de mappage pour tous les fichiers à restaurer.
 a| 
Corrigez le fichier de spécification de restauration afin que les mappages correspondent aux fichiers à restaurer.



 a| 
ORACLE-30028 : Impossible de vider le fichier journal <nom_fichier>. Le fichier est peut-être manquant/inaccessible/corrompu. Ce fichier journal ne sera pas utilisé pour la récupération.
 a| 
Les fichiers journaux de reprise en ligne ou les fichiers journaux d'archivage ne peuvent pas être utilisés pour la restauration.cette erreur se produit pour les raisons suivantes :

* Les fichiers journaux de reprise en ligne ou les fichiers journaux archivés mentionnés dans le message d'erreur ne disposent pas de numéros de modification suffisants pour s'appliquer à la récupération. Cela se produit lorsque la base de données est en ligne sans transactions. Les fichiers journaux de reprise ou archivés ne contiennent aucun numéro de modification valide pouvant être appliqué pour la restauration.
* Le fichier journal de reprise en ligne ou le fichier journal archivé mentionné dans le message d'erreur ne dispose pas de privilèges d'accès suffisants pour Oracle.
* Le fichier journal de reprise en ligne ou le fichier journal archivé mentionné dans le message d'erreur est corrompu et ne peut pas être lu par Oracle.
* Le fichier journal de reprise en ligne ou le fichier journal archivé mentionné dans le message d'erreur est introuvable dans le chemin mentionné.

 a| 
Si le fichier mentionné dans le message d'erreur est un fichier journal archivé et que vous avez fourni manuellement pour la récupération, assurez-vous que le fichier dispose des autorisations d'accès complet à Oracle.même si le fichier dispose de toutes les autorisations, et le message continue, le fichier journal d'archives n'a pas de numéro de modification à appliquer pour la restauration, et ce message peut être ignoré.

|===


== Messages d'erreur associés au processus de clonage (série 4000)

Le tableau ci-dessous présente les erreurs courantes associées au processus de clonage :

|===


| Message d'erreur | Explication | Solution 


 a| 
SMO-04133 : la destination de vidage ne doit pas exister
 a| 
Vous utilisez SnapManager pour créer de nouveaux clones. En revanche, les destinations de dump à utiliser par le nouveau clone existent déjà. SnapManager ne peut pas créer de clone si ces destinations existent.
 a| 
Supprimez ou renommez les anciennes destinations de vidage avant de créer un clone.



 a| 
SMO-13032:impossible d'effectuer l'opération : cloner la création. Cause principale : ORACLE-00001 : erreur lors de l'exécution de SQL : [ALTER BASE DE DONNÉES OUVERTE RESETLOGS;]. La commande renvoyée : ORA-38856 : impossible de marquer l'instance SANS NOM_INSTANCE_2 (redo thread 2) comme activée.
 a| 
La création du clone échoue lorsque vous créez le clone à partir de la base de données de secours à l'aide de la configuration suivante :

* La mise en attente est créée à l'aide de RMAN pour la sauvegarde des fichiers de données.

 a| 
Ajoutez le paramètre _no_Recovery_through_resetlogs=TRUE dans le fichier de spécifications du clone avant de créer le clone. Consultez la documentation Oracle (ID 334899.1) pour plus d'informations. Assurez-vous que vous disposez de votre nom d'utilisateur et de votre mot de passe Oracle metalink.



 a| 
 a| 
Vous n'avez pas fourni de valeur pour un paramètre dans le fichier de spécification clone.
 a| 
Vous devez fournir une valeur pour le paramètre ou supprimer ce paramètre s'il n'est pas requis dans le fichier de spécifications du clone.

|===


== Messages d'erreur associés au processus de gestion du profil (série 5000)

Le tableau ci-dessous présente les erreurs courantes associées au processus de clonage :

|===


| Message d'erreur | Explication | Solution 


 a| 
SMO-20600 : le profil "profile1" est introuvable dans le référentiel "repo_name". Exécutez la « synchronisation du profil » pour mettre à jour les mappages entre votre profil et votre référentiel.
 a| 
L'opération de vidage ne peut pas être effectuée lorsque la création du profil échoue.
 a| 
Utilisez le système de vidage.

|===


== Messages d'erreur associés à la libération des ressources de sauvegarde (sauvegardes série 6000)

Le tableau suivant présente les erreurs courantes associées aux tâches de sauvegarde :

|===


| Message d'erreur | Explication | Solution 


 a| 
SMO-06030 : impossible de supprimer la sauvegarde car elle est en cours d'utilisation <variable>
 a| 
Vous avez tenté d'effectuer l'opération de sauvegarde libre à l'aide de commandes, lorsque la sauvegarde est montée ou a des clones, ou est marquée pour être conservée sans limite.
 a| 
Démontez la sauvegarde ou modifiez la stratégie de conservation illimitée. Le cas échéant, supprimez-les.



 a| 
SMO-06045 : impossible de libérer <variable>, car les ressources de stockage pour la sauvegarde ont déjà été libérées
 a| 
Vous avez tenté d'effectuer l'opération de sauvegarde libre à l'aide de commandes lorsque la sauvegarde a déjà été libérée.
 a| 
Vous ne pouvez pas libérer la sauvegarde si elle est déjà libérée.



 a| 
SMO-06047 : seules les sauvegardes réussies peuvent être libérées. L'état de la sauvegarde <ID> est <statut>.
 a| 
Vous avez tenté d'exécuter l'opération de sauvegarde libre à l'aide de commandes lorsque l'état de sauvegarde a échoué.
 a| 
Réessayez une fois la sauvegarde terminée.



 a| 
SMO-13082 : ne peut pas effectuer l'opération <variable> sur la sauvegarde <ID>, car les ressources de stockage pour la sauvegarde ont été libérées.
 a| 
A l'aide de commandes, vous avez tenté de monter une sauvegarde dont les ressources de stockage sont libérées.
 a| 
Vous ne pouvez pas monter, cloner ou vérifier une sauvegarde dont les ressources de stockage sont libérées.

|===


== Messages d'erreur associés au processus de mise à niveau par roulement (série 9000)

Le tableau suivant présente les erreurs courantes associées au processus de mise à niveau par roulement :

|===


| Message d'erreur | Explication | Solution 


 a| 
SMO-09234:les hôtes suivants n'existent pas dans l'ancien référentiel. <noms d'hôte>.
 a| 
Vous avez essayé d'effectuer une mise à niveau propagée d'un hôte, qui n'existe pas dans la version précédente du référentiel.
 a| 
Vérifiez si l'hôte existe dans le référentiel précédent à l'aide de la commande show-repository du référentiel de la version antérieure de l'interface de ligne de commande SnapManager.



 a| 
SMO-09255:les hôtes suivants n'existent pas dans le nouveau référentiel. <noms d'hôte>.
 a| 
Vous avez essayé de restaurer un hôte, qui n'existe pas dans la nouvelle version du référentiel.
 a| 
Vérifiez si l'hôte existe dans le nouveau référentiel à l'aide de la commande show-repository du référentiel à partir de la version ultérieure de l'interface de ligne de commande SnapManager.



 a| 
SMO-09256:Rollback non pris en charge, car il existe de nouveaux profils <profilenames>.pour les hôtes spécifiés <hostnames>.
 a| 
Vous avez tenté de restaurer un hôte contenant de nouveaux profils existants dans le référentiel. Cependant, ces profils n'existaient pas dans l'hôte de la version SnapManager antérieure.
 a| 
Supprimez les nouveaux profils dans la version ultérieure ou mise à niveau de SnapManager avant la restauration.



 a| 
SMO-09257:Retour arrière non pris en charge, car les sauvegardes <backupid> sont montées sur les nouveaux hôtes.
 a| 
Vous avez essayé de restaurer une version ultérieure de l'hôte SnapManager qui a monté des sauvegardes. Ces sauvegardes ne sont pas montées dans la version antérieure de l'hôte SnapManager.
 a| 
Démontez les sauvegardes dans la version ultérieure de l'hôte SnapManager, puis effectuez la restauration.



 a| 
SMO-09258:Restauration non prise en charge, car les sauvegardes <backupid> sont démontés sur les nouveaux hôtes.
 a| 
Vous avez tenté de restaurer une version ultérieure de l'hôte SnapManager dont les sauvegardes sont en cours de démonté.
 a| 
Montez les sauvegardes dans la version ultérieure de l'hôte SnapManager, puis effectuez la restauration.



 a| 
SMO-09298:ne peut pas mettre à jour ce référentiel car il contient déjà d'autres hôtes dans la version supérieure. Effectuez plutôt la mise à niveau roulante pour tous les hôtes.
 a| 
Vous avez effectué une mise à niveau par roulement sur un même hôte, puis mis à jour le référentiel pour cet hôte.
 a| 
Effectuez une mise à niveau propagée sur tous les hôtes.



 a| 
SMO-09297 : une erreur s'est produite lors de l'activation des contraintes. L'état du référentiel est peut-être incohérent. Il est recommandé de restaurer la sauvegarde du référentiel que vous avez effectuée avant l'opération en cours.
 a| 
Vous avez tenté d'effectuer une opération de mise à niveau ou de restauration par roulement si la base de données du référentiel reste dans un état incohérent.
 a| 
Restaurez le référentiel que vous avez sauvegardé précédemment.

|===


== Exécution d'opérations (série 12,000)

Le tableau suivant présente les erreurs courantes associées aux opérations :

|===


| Message d'erreur | Explication | Solution 


 a| 
SMO-12347 [ERREUR] : le serveur SnapManager ne s'exécute pas sur l'hôte <hôte> et le port <port>. Exécutez cette commande sur un hôte exécutant le serveur SnapManager.
 a| 
Lors de la configuration du profil, vous avez entré des informations sur l'hôte et le port. Cependant, SnapManager ne peut pas effectuer ces opérations car le serveur SnapManager n'est pas exécuté sur l'hôte et le port spécifiés.
 a| 
Entrez la commande sur un hôte exécutant le serveur SnapManager. Vous pouvez vérifier le port avec la commande lsnrctl status et voir le port sur lequel la base de données est exécutée. Modifiez le port de la commande backup, si nécessaire.

|===


== Exécution des composants du processus (série 13,000)

Le tableau suivant présente les erreurs courantes associées au composant de processus de SnapManager :

|===


| Message d'erreur | Explication | Solution 


 a| 
SMO-13083 : le motif Snapname avec la valeur "x" contient des caractères autres que des lettres, des chiffres, des traits de soulignement, un tiret et des accolades.
 a| 
Lors de la création d'un profil, vous avez personnalisé le modèle Snapname ; cependant, vous avez inclus des caractères spéciaux qui ne sont pas autorisés.
 a| 
Supprimez les caractères spéciaux autres que les lettres, les chiffres, les traits de soulignement, les tirets et les accolades.



 a| 
SMO-13084 : le motif Snapname avec la valeur "x" ne contient pas le même nombre d'accolades gauche et droite.
 a| 
Lorsque vous créez un profil, vous avez personnalisé le motif Snapname ; cependant, les accolades gauche et droite ne correspondent pas.
 a| 
Entrez les crochets d'ouverture et de fermeture correspondants dans le motif Snapname.



 a| 
SMO-13085 : le motif Snapname avec la valeur "x" contient un nom de variable incorrect de "y".
 a| 
Lorsque vous créez un profil, vous avez personnalisé le motif Snapname ; cependant, vous avez inclus une variable non autorisée.
 a| 
Supprimer la variable incriminée. Pour afficher une liste de variables acceptables, reportez-vous à la section xref:concept_snapshot_copy_naming.adoc[Dénomination de la copie Snapshot].



 a| 
SMO-13086 le modèle Snapname avec la valeur "x" doit contenir la variable "smid".
 a| 
Lorsque vous créez un profil, vous avez personnalisé le modèle Snapname ; cependant, vous avez omis la variable smid requise.
 a| 
Insérez la variable smid requise.

|===


== Messages d'erreur associés aux utilitaires SnapManager (série 14,000)

Le tableau suivant présente les erreurs courantes associées aux utilitaires SnapManager :

|===


| Message d'erreur | Explication | Solution 


 a| 
SMO-14501 : l'ID de courrier ne peut pas être vide.
 a| 
Vous n'avez pas saisi d'adresse e-mail.
 a| 
Saisissez une adresse e-mail valide.



 a| 
SMO-14502 : l'objet du courrier ne peut pas être vide.
 a| 
Vous n'avez pas indiqué l'objet de l'e-mail.
 a| 
Saisissez l'objet de l'e-mail approprié.



 a| 
SMO-14506 : le champ du serveur de messagerie ne peut pas être vide.
 a| 
Vous n'avez pas saisi le nom d'hôte ou l'adresse IP du serveur de messagerie.
 a| 
Entrez le nom d'hôte ou l'adresse IP du serveur de messagerie valide.



 a| 
SMO-14507 : le champ Port de messagerie ne peut pas être vide.
 a| 
Vous n'avez pas saisi le numéro de port de messagerie.
 a| 
Entrez le numéro de port du serveur de messagerie.



 a| 
SMO-14508 : l'ID du courrier ne peut pas être vide.
 a| 
Vous n'avez pas saisi l'adresse e-mail de l'expéditeur.
 a| 
Saisissez l'adresse e-mail de l'expéditeur valide.



 a| 
SMO-14509 : le nom d'utilisateur ne peut pas être vide.
 a| 
Vous avez activé l'authentification et n'avez pas fourni le nom d'utilisateur.
 a| 
Entrez le nom d'utilisateur de l'authentification par e-mail.



 a| 
SMO-14510 : le mot de passe ne peut pas être vide. Veuillez saisir le mot de passe.
 a| 
Vous avez activé l'authentification et n'avez pas fourni le mot de passe.
 a| 
Entrez le mot de passe d'authentification de l'e-mail.



 a| 
SMO-14550 : état de l'e-mail <succès/échec>.
 a| 
Le numéro de port, le serveur de messagerie ou l'adresse e-mail du destinataire n'est pas valide.
 a| 
Fournissez les valeurs appropriées lors de la configuration du courrier électronique.



 a| 
SMO-14559 : échec de l'envoi de la notification par e-mail : <erreur>.
 a| 
Cela peut être dû à un numéro de port non valide, à un serveur de messagerie non valide ou à une adresse de courrier du destinataire non valide.
 a| 
Fournissez les valeurs appropriées lors de la configuration du courrier électronique.



 a| 
SMO-14560 : échec de la notification : la configuration de la notification n'est pas disponible.
 a| 
Échec de l'envoi de la notification, car la configuration de la notification n'est pas disponible.
 a| 
Ajouter une configuration de notification.



 a| 
SMO-14565 : format d'heure non valide. Veuillez saisir le format d'heure en HH:mm.
 a| 
Vous avez saisi l'heure dans un format incorrect.
 a| 
Entrez l'heure au format hh:mm.



 a| 
SMO-14566 : valeur de date non valide. La plage de dates valide est comprise entre 1 et 31.
 a| 
La date configurée est incorrecte.
 a| 
La date doit être comprise entre 1 et 31.



 a| 
SMO-14567 : valeur jour non valide. La plage de jours valide est comprise entre 1 et 7.
 a| 
Le jour configuré est incorrect.
 a| 
Saisissez la plage de jours de 1 à 7.



 a| 
SMO-14569 : le serveur n'a pas pu démarrer le programme de notification de résumé.
 a| 
Le serveur SnapManager s'est arrêté pour des raisons inconnues.
 a| 
Démarrez le serveur SnapManager.



 a| 
SMO-14570 : notification de résumé non disponible.
 a| 
Vous n'avez pas configuré la notification récapitulative.
 a| 
Configurer la notification récapitulative.



 a| 
SMO-14571 : les notifications de profil et de résumé ne peuvent pas être activées.
 a| 
Vous avez sélectionné les options de notification de profil et de résumé.
 a| 
Activez la notification de profil ou la notification récapitulative.



 a| 
SMO-14572 : fournissez une option de notification de succès ou d'échec.
 a| 
Vous n'avez pas activé les options succès ou échec.
 a| 
Vous devez sélectionner l'option succès ou échec ou les deux.

|===
*Informations connexes*

xref:concept_snapshot_copy_naming.adoc[Dénomination de la copie Snapshot]
