---
permalink: windows/reference_the_smosmsapcmdfile_command.html 
sidebar: sidebar 
keywords: cmdfile, command, run, host, limit, smo 
summary: Vous pouvez utiliser la commande cmdfile pour exécuter une commande si le shell de votre hôte limite le nombre de caractères pouvant apparaître sur une ligne de commande. 
---
= Commande smo cmdfile
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser la commande cmdfile pour exécuter une commande si le shell de votre hôte limite le nombre de caractères pouvant apparaître sur une ligne de commande.



== Syntaxe

[listing]
----

        smo cmdfile
-file file_name
\[-quiet \| -verbose\]
----
Vous pouvez inclure la commande dans un fichier texte et utiliser la commande smo cmdfile pour exécuter la commande. Vous ne pouvez ajouter qu'une seule commande dans un fichier texte. Vous ne devez pas inclure smo dans la syntaxe de commande.


NOTE: La commande smo cmdfile remplace la commande SMO pfile. Le cmdfile smo n’est pas compatible avec la commande pfile smo.



== Paramètres

* *-fichier nom_fichier*
+
Indique le chemin d'accès au fichier texte contenant la commande à exécuter.

* *-calme*
+
Spécifie que seuls les messages d'erreur s'affichent dans la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Spécifie que les messages d'erreur, d'avertissement et d'information sont affichés dans la console.


