---
permalink: windows/reference_the_smosmsapclone_create_command.html 
sidebar: sidebar 
keywords: clone, create, command, backed, up, database, primary, secondary, storage, smo 
summary: 'Vous pouvez exécuter la commande clone create pour créer un clone d"une base de données sauvegardée. Il est possible de cloner une sauvegarde à partir d"un stockage primaire ou secondaire.' 
---
= Commande smo clone create
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter la commande clone create pour créer un clone d'une base de données sauvegardée. Il est possible de cloner une sauvegarde à partir d'un stockage primaire ou secondaire.



== Syntaxe

[listing]
----

        smo clone create
-profile profile_name
[-backup-id backup_guid \| -backup-label backup_label_name \| -current\]
-newsid new_sid
\[-host target_host\]
[-label clone_label]
\[-comment string\]
-clonespec full_path_to_clonespec_file
]
\[-syspassword syspassword\]
\[-reserve \{yes \| no \| inherit\}\]

\[-no-resetlogs \| -recover-from-location path1 \[, path2\]\]\[-taskspec taskspec\]
\[-dump\]
\[-quiet \| -verbose\]
----


== Paramètres

* *-nom de profil*
+
Spécifie la base de données à cloner. Le profil contient l'identifiant de la base de données et d'autres informations sur la base de données.

* *-id-sauvegarde guid*
+
Permet de cloner la sauvegarde à l'aide du GUID spécifié. Le GUID est généré par SnapManager lors de la création d'une sauvegarde. Vous pouvez utiliser la commande SMO list-boverdétaillé pour afficher le GUID pour chaque sauvegarde.

* *-label-backup_label_name*
+
Indique de cloner la sauvegarde avec le nom d'étiquette spécifié.

* *-courant*
+
Spécifie pour créer une sauvegarde et un clonage à partir de l'état actuel de la base de données.

+

NOTE: Si la base de données est en mode noarchivelog, SnapManager crée une sauvegarde hors ligne.

* *-newsid new_sid*
+
Spécifie un nouvel identifiant système Oracle unique pour la base de données clonée. La valeur de l'identifiant système est de huit caractères maximum. Oracle ne permet pas l'exécution simultanée de deux bases de données avec le même identificateur système sur le même hôte.

* *-hôte cible_hôte*
+
Spécifie l'hôte sur lequel le clone doit être créé.

* *-label clone_label*
+
Spécifie un libellé pour le clone.

* *-chaine de commentaire*
+
Spécifie un commentaire facultatif pour décrire ce clone. Vous devez inclure la chaîne entre guillemets.

+

NOTE: Certaines coques suppriment les guillemets. Si c'est vrai pour votre shell, vous devez échapper à la citation avec une barre oblique inverse (\). Par exemple, vous devrez peut-être entrer : \' il s'agit d'un commentaire\'.

* *-clonespec full_path_to_clonespec_file*
+
Indique le chemin d'accès au fichier XML de spécification de clone. Il peut s'agir d'un nom de chemin relatif ou absolu.

* *-syspassword*
+
Spécifie le mot de passe pour l'utilisateur privilégié du système.

+

NOTE: Vous devez fournir le mot de passe pour l'utilisateur privilégié du système si les informations d'identification de la base de données fournies ne sont pas les mêmes pour l'utilisateur privilégié du système.

* *-réserve*
+
La définition de l'option -Reserve sur yes garantit que l'espace de réserve de garantie du volume est activé pour les nouveaux volumes clones. Si vous définissez l'option -Reserve sur no, vous vous assurez que l'espace de réserve de garantie du volume est désactivé pour les nouveaux volumes clones. La définition de l'option -Reserve permet d'hériter du nouveau clone, d'hérite des caractéristiques de réservation d'espace de la copie Snapshot parent. Le paramètre par défaut est non

+
Le tableau suivant décrit les méthodes de clonage et leur impact sur l'opération clone create et son option -Reserve. Une LUN peut être clonée à l'aide de l'une ou l'autre méthode.

+
|===


| Méthode de clonage | Description | Résultat 


 a| 
 LUN cloning a| 
 A new clone LUN is created within the same volume. a| 
 When the -reserve option for a LUN is set to yes, space is reserved for the full LUN size within the volume.


 a| 
 Volume cloning a| 
 A new FlexClone is created, and the clone LUN exists within the new clone volume. Uses the FlexClone technology. a| 
 When the -reserve option for a volume is set to yes, space is reserved for the full volume size within the aggregate.
+

|===
* *-no-resetlogs*
+
Spécifie que pour ignorer la récupération de la base de données, exécuter l'utilitaire DBNEWID et ne pas ouvrir la base de données avec les réetlogs lors de la création du clone.

* *-récupération-de-l'emplacement*
+
Spécifie l'emplacement du journal d'archivage externe des sauvegardes du journal d'archivage où SnapManager place les fichiers journaux d'archive à partir de l'emplacement externe et les utilise pour le clonage.

* *-taskspspspspspspspspec
+
Spécifie le fichier XML de spécification de tâche pour l'activité de prétraitement ou de post-traitement de l'opération de clonage. Vous devez fournir le chemin complet du fichier XML de spécification de tâche.

* *-dump*
+
Spécifie pour collecter les fichiers de vidage après l'opération de création du clone.

* *-calme*
+
Affiche uniquement les messages d'erreur dans la console. Le paramètre par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche les messages d'erreur, d'avertissement et d'information dans la console.





== Exemple

L'exemple suivant illustre le clonage de la sauvegarde à l'aide d'une spécification de clone créée pour ce clone :

[listing]
----
smo clone create -profile SALES1 -backup-label full_backup_sales_May -newsid
CLONE -label sales1_clone -clonespec E:\\spec\\clonespec.xml
----
[listing]
----
Operation Id [8abc01ec0e794e3f010e794e6e9b0001] succeeded.
----
*Informations connexes*

xref:task_creating_clone_specifications.adoc[Création de spécifications de clonage]

xref:task_cloning_databases_from_backups.adoc[Le clonage des bases de données à partir des sauvegardes]
