---
permalink: windows/reference_the_smo_notification_removesummarynotification_command.html 
sidebar: sidebar 
keywords: command, disable, summary, notification, multiple, profile, repository, database, smo, remove-summary-notification 
summary: Cette commande désactive la notification récapitulative pour plusieurs profils sur une base de données de référentiel. 
---
= La commande smo de notification remove-summary-notification
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande désactive la notification récapitulative pour plusieurs profils sur une base de données de référentiel.



== Syntaxe

[listing]
----

        smo notification remove-summary-notification
-repository
-dbname repo_service_name
-port repo_port
-host repo_host
-login -username repo_username
\[-quiet \| -verbose\]
----


== Paramètres

* *-référentiel*
+
Les options suivantes -repository spécifient les détails de la base de données pour le référentiel.

* *-port repo_port*
+
Spécifie le numéro de port TCP utilisé pour accéder à la base de données qui stocke le référentiel.

* *-dbname repo_service_name*
+
Indique le nom de la base de données qui stocke le référentiel. Utilisez le nom global ou le SID.

* *-hôte repo_host*
+
Indique le nom ou l'adresse IP de l'ordinateur hôte sur lequel s'exécute la base de données de référentiel.

* *-login repo_username*
+
Spécifie le nom de connexion nécessaire pour accéder à la base de données qui stocke le référentiel.

* *-calme*
+
Affiche uniquement les messages d'erreur sur la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche des messages d'erreur, d'avertissement et d'information sur la console.



L'exemple suivant désactive la notification de synthèse pour plusieurs profils d'une base de données de référentiel.

[listing]
----

smo notification remove-summary-notification –repository –port 1521 –dbname repo2 –host 10.72.197.133 –login -username oba5
----