---
permalink: windows/reference_the_smosmsapclone_list_command.html 
sidebar: sidebar 
keywords: command, list, clone, database 
summary: Cette commande répertorie les clones de la base de données pour un profil donné. 
---
= Commande smo clone list
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande répertorie les clones de la base de données pour un profil donné.



== Syntaxe

[listing]
----

        smo clone list
-profile profile_name
-delimiter character
\[-quiet \| -verbose\]
----


== Paramètres

* *-profil nom_profil*
+
Spécifie la liste des clones associés au profil. Le profil contient l'identifiant de la base de données et d'autres informations sur la base de données.

* *-caractère délimiteur*
+
Lorsque ce paramètre est spécifié, la commande répertorie les attributs de chaque ligne séparés par le caractère spécifié.

* *-calme*
+
Affiche uniquement les messages d'erreur sur la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche des messages d'erreur, d'avertissement et d'information sur la console.





== Exemple de commande

L'exemple suivant répertorie les clones de base de données dans le profil SALES1.

[listing]
----
smo clone list -profile SALES1 -verbose
----
[listing]
----
ID Status SID Host Label Comment
-------- ------- ----- ------- ---------- -------
8ab...01 SUCCESS hsdbc server1 back1clone test comment
----
*Informations connexes*

xref:task_viewing_a_list_of_clones.adoc[Affichage de la liste des clones]
