---
permalink: windows/reference_the_smosmsapprofile_sync_command.html 
sidebar: sidebar 
keywords: command, load, profile-to-repository, mapping, repository, file, directory, smo 
summary: 'Cette commande charge les mappages profil-référentiel pour ce référentiel dans un fichier de votre répertoire personnel sur l"hôte local.' 
---
= Commande de synchronisation du profil smo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande charge les mappages profil-référentiel pour ce référentiel dans un fichier de votre répertoire personnel sur l'hôte local.



== Syntaxe

[listing]
----

        smo profile sync
-repository
-dbname repo_service_name
-host repo_host
-port repo_port
-login
-username repo_username
				\[-quiet \| -verbose\]
----


== Paramètres

* *-référentiel*
+
Les options suivantes -repository spécifient les détails de la base de données pour le référentiel.

* *-dbname repo_service_name*
+
Spécifie la base de données du référentiel pour que le profil se synchronise.

* *-hôte*
+
Spécifie l'hôte de base de données.

* *-port*
+
Spécifie le port de l'hôte.

* *-connexion*
+
Spécifie le processus de connexion pour l'utilisateur hôte.

* *-username*
+
Spécifie le nom d'utilisateur de l'hôte.

* *-calme*
+
Affiche uniquement les messages d'erreur sur la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche des messages d'erreur, d'avertissement et d'information sur la console.





== Exemple de commande

L'exemple suivant montre le résultat de la commande pour synchroniser les mappages profil-référentiel de la base de données.

[listing]
----
smo profile sync -repository -dbname smrepo -host Host2 -port 1521 -login -username user2
SMO-12345 [INFO ]: Loading profile mappings for repository "user2@Host2:smrepo" into cache for OS User "admin".
Operation Id [Nff8080810da9018f010da901a0170001] succeeded.
----