---
permalink: windows/reference_the_smosmsapprofile_create_command.html 
sidebar: sidebar 
keywords: run, profile, create, command, database, repository, smo 
summary: 'Vous pouvez exécuter la commande création de profil pour créer un profil d"une base de données dans un référentiel. Vous devez monter la base de données avant d"exécuter cette commande.' 
---
= Commande smo profile create
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter la commande création de profil pour créer un profil d'une base de données dans un référentiel. Vous devez monter la base de données avant d'exécuter cette commande.



== Syntaxe

[listing]
----

        smo profile create
-profile profile
\[-profile-password profile_password\]
-repository
-dbname repo_service_name
-host repo_host
-port repo_port
-login -username repo_username
-database
-dbname db_dbname
-host db_host
[-sid  db_sid\]
[-login
\[-username db_username -password db_password -port db_port\]
 ]
[-rman \{-controlfile \| \{-login
-username  rman_username -password  rman_password\}
-tnsname  rman_tnsname\}\}]


[-retain
\[-hourly \[-count n\] \[-duration m\]\]
\[-daily \[-count n\] \[-duration m\]]
\[-weekly \[-count n\] \[-duration m\]]
\[-monthly \[-count n\] \[-duration m\]]]]
-comment comment
-snapname-pattern pattern
[]
[-summary-notification]
[-notification
\[-success
-email email_address1,email_address2
-subject subject_pattern\]
\[-failure
-email email_address1,email_address2
-subject subject_pattern]
[-separate-archivelog-backups
-retain-archivelog-backups
 -hours hours |
-days days |
-weeks weeks |
-months months
[]
[-include-with-online-backups \| -no-include-with-online-backups]]
[-dump]
[-quiet | -verbose]
----


== Paramètres

* profil **
+
Spécifie le nom du profil. Ce nom peut comporter jusqu'à 30 caractères et doit être unique au sein de l'hôte.

* *-profil-mot_de_passe profil*
+
Spécifiez le mot de passe du profil.

* *-référentiel*
+
Les options suivantes -repository spécifient les détails de la base de données qui stocke le profil.

* *-dbname repo_service_name*
+
Indique le nom de la base de données qui stocke le profil. Utilisez le nom global ou le SID.

* *-hôte repo_host*
+
Indique le nom ou l'adresse IP de l'ordinateur hôte sur lequel s'exécute la base de données de référentiel.

* *-sid db_sid*
+
Indique l'identifiant système de la base de données décrit par le profil. Par défaut, SnapManager utilise le nom de la base de données comme identificateur système. Si l'identifiant système est différent du nom de la base de données, vous devez le spécifier avec l'option -sid.

* *-connexion*
+
Spécifie les détails de connexion au référentiel.

* *-username repo_username*
+
Spécifie le nom d'utilisateur nécessaire pour accéder à la base de données du référentiel.

* *-port repo_port*
+
Spécifie le numéro de port TCP utilisé pour accéder à la base de données du référentiel.

* *-base de données*
+
Indique les détails de la base de données que le profil décrit. Il s'agit de la base de données qui sera sauvegardée, restaurée ou clonée.

* *-dbname db_dbname*
+
Indique le nom de la base de données décrit par le profil. Vous pouvez utiliser le nom global ou l'identifiant système.

* *-hôte db_host db_host*
+
Indique le nom ou l'adresse IP de l'ordinateur hôte sur lequel la base de données s'exécute.

* *-connexion*
+
Spécifie les détails de connexion à la base de données.

* *-username db_username*
+
Indique le nom d'utilisateur requis pour accéder à la base de données décrit par le profil.

* *-mot de passe db_password*
+
Spécifie le mot de passe requis pour accéder à la base de données décrit par le profil.

* *-port db_port*
+
Spécifie le numéro de port TCP utilisé pour accéder à la base de données que le profil décrit.

* *-rman*
+
Spécifie les détails qu'SnapManager utilise pour cataloguer les sauvegardes avec Oracle Recovery Manager (RMAN).

* *-controlfile*
+
Spécifie les fichiers de contrôle de base de données cible au lieu d'un catalogue en tant que référentiel RMAN.

* *-connexion*
+
Spécifie les détails de connexion RMAN.

* *-mot de passe rman_mot de passe*
+
Spécifie le mot de passe utilisé pour se connecter au catalogue RMAN.

* *-username rman_username*
+
Spécifie le nom d'utilisateur utilisé pour se connecter au catalogue RMAN.

* *-tnsname nomnet*
+
Indique le nom de la connexion tnsname (défini dans le fichier tsname.ora).

* *-retain [-hourly [-count n] [-duration m]] [-daily [-count n] [-duration m]] [-hebdomadaire [-count n] [-duration m]] [-mensuel [-comptage n] [-durée m]*
+
Spécifie la stratégie de conservation pour une sauvegarde où ou les deux d'un compte de rétention et une durée de conservation pour une classe de rétention (horaire, quotidien, hebdomadaire, mensuel).

+
Pour chaque classe de rétention, ou les deux d'un nombre de rétention ou d'une durée de conservation peuvent être spécifiés. La durée est exprimée en unités de la classe (par exemple, heures pour l'heure, jours pour la journée). Par exemple, si l'utilisateur indique uniquement une durée de conservation de 7 pour les sauvegardes quotidiennes, SnapManager ne limite pas le nombre de sauvegardes quotidiennes du profil (car le nombre de rétention est 0), mais SnapManager supprimera automatiquement les sauvegardes quotidiennes créées il y a plus de 7 jours.

* *-commentaire*
+
Spécifie le commentaire d'un profil décrivant le domaine de profil.

* *-motif-snapname*
+
Spécifie le modèle de nom pour les copies Snapshot. Vous pouvez également inclure du texte personnalisé, par exemple HAOPS pour les opérations hautement disponibles, dans tous les noms de copie Snapshot. Vous pouvez modifier le schéma de nommage des copies Snapshot lorsque vous créez un profil ou après sa création. La mise à jour s'applique uniquement aux copies Snapshot qui n'ont pas encore été créées. Les copies Snapshot qui existent conservent le modèle Snapname précédent. Vous pouvez utiliser plusieurs variables dans le texte du motif.

* *-résumé-notification*
+
Indique que la notification par e-mail sommaire est activée pour le nouveau profil.

* *-notification -courriel-succès-adresse_courriel 1,adresse-courriel-2 -thème_modèle*
+
Spécifie que la notification par e-mail est activée pour le nouveau profil afin que les e-mails soient reçus par les destinataires lorsque l'opération SnapManager réussit. Vous devez entrer une ou plusieurs adresses e-mail auxquelles les alertes e-mail seront envoyées et un modèle d'objet d'e-mail pour le nouveau profil.

+
Vous pouvez également inclure du texte d'objet personnalisé pour le nouveau profil. Vous pouvez modifier le texte de l'objet lorsque vous créez un profil ou après sa création. L'objet mis à jour s'applique uniquement aux e-mails non envoyés. Vous pouvez utiliser plusieurs variables pour l'objet de l'e-mail.

* *-notification -échec -email e-mail_address1,adresse e-mail 2 -subject_pattern*
+
Spécifie que l'activation de la notification par e-mail est activée pour le nouveau profil afin que les e-mails soient reçus par les destinataires en cas d'échec de l'opération SnapManager. Vous devez entrer une ou plusieurs adresses e-mail auxquelles les alertes e-mail seront envoyées et un modèle d'objet d'e-mail pour le nouveau profil.

+
Vous pouvez également inclure du texte d'objet personnalisé pour le nouveau profil. Vous pouvez modifier le texte de l'objet lorsque vous créez un profil ou après sa création. L'objet mis à jour s'applique uniquement aux e-mails non envoyés. Vous pouvez utiliser plusieurs variables pour l'objet de l'e-mail.

* *-séparé-archivelog-sauvegardes*
+
Spécifie que la sauvegarde du journal d'archivage est séparée de la sauvegarde du fichier de données. Il s'agit d'un paramètre facultatif que vous pouvez fournir lors de la création du profil. Après avoir séparé la sauvegarde à l'aide de cette option, vous pouvez effectuer une sauvegarde de fichiers de données uniquement ou des journaux d'archivage uniquement.

* *-conserver-archivelog-sauvegardes -heures | -jours de repos | -semaines| -mois de semaine*
+
Indique que les sauvegardes du journal d'archivage sont conservées en fonction de la durée de conservation du journal d'archivage (horaire, quotidien, hebdomadaire, mensuel).

* *-calme*
+
Affiche uniquement les messages d'erreur dans la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche les messages d'erreur, d'avertissement et d'information dans la console.

* *-inclure-avec-sauvegardes-en-ligne*
+
Indique que la sauvegarde du journal d'archivage est incluse avec la sauvegarde de base de données en ligne.

* *-sans-inclure-avec-en-ligne-sauvegardes*
+
Indique que les sauvegardes du journal d'archivage ne sont pas incluses avec la sauvegarde de base de données en ligne.

* *-dump*
+
Indique que les fichiers de vidage sont collectés après l'opération de création de profil réussie.





== Exemple

L'exemple suivant montre la création d'un profil avec une stratégie de conservation horaire et une notification par e-mail :

[listing]
----
smo profile create -profile test_rbac -profile-password netapp -repository -dbname SMOREP -host hostname.org.com -port 1521 -login -username smorep -database -dbname
RACB -host saal -sid racb1 -login -username sys -password netapp -port 1521 -rman -controlfile -retain -hourly -count 30 -verbose
Operation Id [8abc01ec0e78ebda010e78ebe6a40005] succeeded.
----
*Informations connexes*

xref:concept_managing_profiles_for_efficient_backups.adoc[Gestion des profils pour des sauvegardes efficaces]

xref:concept_snapshot_copy_naming.adoc[Dénomination de la copie Snapshot]

xref:concept_how_snapmanager_retains_backups_on_the_local_storage.adoc[SnapManager conserve les sauvegardes sur le système de stockage local]
