---
permalink: windows/task_configuring_e_mail_notification_for_an_existing_profile.html 
sidebar: sidebar 
keywords: updating, profile, configure, receive, email, notification, completion, database, operation, configuring, existing 
summary: 'Lorsque vous mettez à jour un profil, vous pouvez configurer pour recevoir une notification par e-mail à la fin de l"opération de base de données.' 
---
= Configuration de la notification par e-mail pour un profil existant
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous mettez à jour un profil, vous pouvez configurer pour recevoir une notification par e-mail à la fin de l'opération de base de données.

* Vous devez configurer l'adresse e-mail à partir de laquelle les alertes sont envoyées.
* Vous devez entrer une ou plusieurs adresses e-mail auxquelles les alertes seront envoyées.
+
Vous pouvez utiliser une liste séparée par des virgules pour plusieurs adresses. Vous devez vous assurer qu'il n'y a pas d'espace entre la virgule et l'adresse e-mail suivante. Vous pouvez également ajouter un objet à l'e-mail.

+

NOTE: Vous devez vous assurer que vous entrez l'ensemble de plusieurs adresses e-mail entre guillemets.

+
.. Entrez la commande suivante :smo profil update -profileprofile [-profile-passwordprofile_password][-database-dbnamedb_dbname-host db_host [-siddb_sid] [-login_usernamedb_password [-db_port db] [-adressedern_statefn] [-statn-term-stackname] [-tersted] [-tersted-term-tern] [-term-tersted [-tern] [-term [-term-term-term-term-term-term] [-terregate] [-terregate] [-terregate] [-terregate] [-terregate] [-terregate] [-terregate] [-terregate] [-terregate] [-terregate [-terregate] [-terregate] [-terregate] [-terregate] [-terregate] [-terregate [-terregate] [-terregate] [-terregate
+
Vous pouvez utiliser l'option succès pour recevoir une notification uniquement pour les opérations de base de données réussies et l'option échec pour recevoir une notification uniquement pour les opérations de base de données ayant échoué.




