---
permalink: windows/task_modifying_the_backup_retention_class.html 
sidebar: sidebar 
keywords: upgrade, snapmanager, assign, default, retention, class, exist, backup, requirement, modify 
summary: Le SnapManager mis à niveau attribue la classe de conservation de sauvegarde par défaut aux sauvegardes existantes. Vous pouvez modifier les valeurs de classe de rétention par défaut pour répondre à vos exigences de sauvegarde. 
---
= Modification de la classe de rétention de sauvegarde
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le SnapManager mis à niveau attribue la classe de conservation de sauvegarde par défaut aux sauvegardes existantes. Vous pouvez modifier les valeurs de classe de rétention par défaut pour répondre à vos exigences de sauvegarde.

La classe de rétention des sauvegardes par défaut attribuée aux sauvegardes existantes est la suivante :

|===


| Type de sauvegarde | Attribution de classe de conservation après la mise à niveau 


 a| 
Sauvegardes à conserver indéfiniment
 a| 
Illimitée



 a| 
Autres sauvegardes
 a| 
Tous les jours

|===
*Remarque :* vous pouvez supprimer les sauvegardes qui sont conservées indéfiniment sans changer la classe de rétention.

Si vous effectuez une mise à niveau vers SnapManager 3.0 ou version ultérieure, les deux valeurs suivantes sont attribuées aux profils existants :

* Nombre de rétention précédent pour le profil
* Valeurs par défaut du nombre de rétention et de la durée des sauvegardes quotidiennes, comme spécifié dans le fichier smo.config
+
.. Modifiez les valeurs affectées à retain.hourly.count et retain.hourly.duration dans le fichier smo.config.
+
Vous pouvez entrer les valeurs suivantes :

+
*** retain.hourly.count = 12
*** retenue.horaire.durée = 2






*Informations connexes*

xref:reference_snapmanager_configuration_parameters.adoc[Paramètres de configuration SnapManager]
