---
permalink: windows/task_freeing_backups.html 
sidebar: sidebar 
keywords: free, backup, delete, snapshot, copies, copy, deleting, metadata, fuction, space, smo 
summary: 'Vous pouvez libérer des sauvegardes, qui suppriment les copies Snapshot sans supprimer les métadonnées de sauvegarde. Cette fonction libère l"espace occupé par la sauvegarde. Vous pouvez utiliser la commande sans sauvegarde smo pour libérer les sauvegardes.' 
---
= Sauvegardes libérées
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez libérer des sauvegardes, qui suppriment les copies Snapshot sans supprimer les métadonnées de sauvegarde. Cette fonction libère l'espace occupé par la sauvegarde. Vous pouvez utiliser la commande sans sauvegarde smo pour libérer les sauvegardes.

Pour qu'une sauvegarde puisse être déautorisée, vous devez vous assurer que :

* La sauvegarde a réussi
* La sauvegarde ne doit pas être montée
* La sauvegarde ne contient pas de clones
* La sauvegarde ne doit pas être conservée au moyen d'une stratégie de conservation illimitée
* La sauvegarde n'est pas déjà libérée


Vous pouvez spécifier l'option -dump en tant que paramètre facultatif pour collecter les fichiers de vidage après l'opération de sauvegarde libre réussie ou échoué.

. Entrez la commande suivante : smo backup free -profileprofile_name {-labellabel [data | -archivelogs] | -idid | -all} -force [-dump] [-quiet] [-force]


*Informations connexes*

xref:reference_the_smosmsapbackup_free_command.adoc[Commande gratuite de sauvegarde smo]
