---
permalink: windows/task_verifying_installation_of_plugin_scripts.html 
sidebar: sidebar 
keywords: snapmanager, enable, install, custom, script, perform, various, operation, backup, restore, clone 
summary: 'SnapManager vous permet d"installer et d"utiliser des scripts personnalisés pour effectuer diverses opérations. SnapManager propose des plug-ins pour les opérations de sauvegarde, de restauration et de clonage. Ces plug-ins permettent d"automatiser les scripts personnalisés avant et après les opérations de sauvegarde, de restauration et de clonage.' 
---
= Vérification de l'installation des scripts du plug-in
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager vous permet d'installer et d'utiliser des scripts personnalisés pour effectuer diverses opérations. SnapManager propose des plug-ins pour les opérations de sauvegarde, de restauration et de clonage. Ces plug-ins permettent d'automatiser les scripts personnalisés avant et après les opérations de sauvegarde, de restauration et de clonage.

. Saisissez la commande suivante :
+
vérification du plug-in smo -osaccount nom d'utilisateur de la base de données du système d'exploitation

+
Si vous ne fournissez pas l'option -osaccount, la vérification de l'installation du script du plug-in se produit pour l'administrateur plutôt que pour un utilisateur spécifié.

+
Le résultat suivant indique que les scripts politie1, pré-plugin1 et pré-plugin2 ont été installés avec succès. Cependant, le script post-plugin1 n'est pas opérationnel.

+
[listing]
----

            smo plugin check
Checking plugin directory structure ...
<installdir>\plugins\clone\policy
   OK: 'policy1' is executable

<installdir>\plugins\clone\pre
   OK: 'pre-plugin1' is executable and returned status 0
   OK: 'pre-plugin2' is executable and returned status 0

<installdir>\plugins\clone\post
   ERROR: 'post-plugin1' is executable and returned status 3
Command complete.
----

