---
permalink: windows/task_changing_the_retention_policy_default_behavior.html 
sidebar: sidebar 
keywords: backup, expire, retention, policy, snapmanager, delete, settings, default, behavior, protect, unprotected 
summary: 'Lorsqu"une sauvegarde expire en fonction de la stratégie de conservation, SnapManager détermine si elle doit être supprimée en fonction des paramètres de conservation. La suppression des sauvegardes est le comportement par défaut. Vous pouvez modifier ce comportement par défaut et choisir de libérer à la place les sauvegardes non protégées.' 
---
= Modification du comportement par défaut de la stratégie de rétention des médias
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsqu'une sauvegarde expire en fonction de la stratégie de conservation, SnapManager détermine si elle doit être supprimée en fonction des paramètres de conservation. La suppression des sauvegardes est le comportement par défaut. Vous pouvez modifier ce comportement par défaut et choisir de libérer à la place les sauvegardes non protégées.

Par défaut, Snap Manager supprime la sauvegarde lorsqu'elle expire.

. Accédez à l'emplacement par défaut suivant :
+
emplacement d'installation smo par défaut\properties\smo.config

. Modifiez le fichier smo.config.
. Définissez la propriété retain.alwaysFreeExpiredBackups dans le fichier smo.config sur true.
+
Par exemple, retain.alwaysFreeExpiredBackups = true



*Informations connexes*

xref:reference_the_smosmsapbackup_update_command.adoc[Commande smo backup update]
