---
permalink: windows/task_updating_the_existing_repository.html 
sidebar: sidebar 
keywords: update, exist, repository, upgrading, snapmanager, updating, upgrade 
summary: 'Vous n"avez pas besoin de mettre à jour le référentiel existant si vous effectuez une mise à niveau de SnapManager 3.3.x vers SnapManager 3.4 ou version ultérieure, mais pour tous les autres chemins de mise à niveau, vous devez mettre à jour le référentiel existant pour pouvoir y accéder après la mise à niveau.' 
---
= Mise à jour du référentiel existant
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous n'avez pas besoin de mettre à jour le référentiel existant si vous effectuez une mise à niveau de SnapManager 3.3.x vers SnapManager 3.4 ou version ultérieure, mais pour tous les autres chemins de mise à niveau, vous devez mettre à jour le référentiel existant pour pouvoir y accéder après la mise à niveau.

* Le serveur SnapManager mis à niveau doit avoir été démarré et vérifié.
* Une sauvegarde du référentiel existant doit exister.
* Si vous mettez à niveau une version antérieure à SnapManager 3.1 vers SnapManager 3.3 ou une version ultérieure, vous devez d'abord effectuer une mise à niveau vers SnapManager 3.2.
+
Après la mise à niveau vers SnapManager 3.2, vous pouvez ensuite effectuer une mise à niveau vers SnapManager 3.3 ou version ultérieure.

* Après la mise à jour du référentiel, vous ne pouvez pas utiliser le référentiel avec une version antérieure de SnapManager.
+
.. Mettez à jour le référentiel existant : smo repository update -repository -dbname nom_service_hôte nom_hôte_référentiel -login -nom_référentiel_utilisateur -port référentiel_port
+
*** Le nom d'utilisateur du référentiel, le nom du service de référentiel et le nom d'hôte du référentiel peuvent comprendre des caractères alphanumériques, un signe moins, un trait de soulignement et un point.
*** Le port du référentiel peut être n'importe quel numéro de port valide. Les autres options utilisées lors de la mise à jour du référentiel existant sont les suivantes :
*** L'option forcer
*** L'option noprompt
*** L'option silencieux
*** L'option détaillée






[source]
----
smo repository update -repository -dbname SALESDB
-host server1 -login -username admin -port 1521

+
----
Redémarrez le serveur SnapManager pour redémarrer les plannings associés.
