---
permalink: windows/task_downloading_snapmanager_for_oracle_installation_package.html 
sidebar: sidebar 
keywords: download, snapmanager, oracle, installation, package, netapp, support, site 
summary: 'Vous pouvez télécharger le pack d"installation SnapManager pour Oracle depuis le site de support NetApp.' 
---
= Téléchargement du package d'installation de SnapManager pour Oracle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez télécharger le pack d'installation SnapManager pour Oracle depuis le site de support NetApp.

. Connectez-vous au site de support NetApp.
. Sur la page du site de support NetApp, cliquez sur *Downloads* > *Software*.
. Dans le tableau Téléchargement de logiciels, allez à la ligne de produits SnapManager et sélectionnez *Oracle (Windows)* dans la liste déroulante Sélectionner une plate-forme.
. Cliquez sur *Go*.
+
Nous répertoriées les versions de SnapManager.

. Cliquez sur *Afficher et télécharger* pour la version de SnapManager que vous souhaitez installer.
+
La page de description s'affiche.

+

NOTE: Vous devriez lire les informations disponibles sur cette page.

. En bas de cette page, cliquez sur *Continuer*.
+
La page du contrat de licence s'affiche.

+

NOTE: Vous devriez lire les informations disponibles sur cette page.

. Cliquez sur *Accept*.
+
La page de téléchargement s'affiche.

. Téléchargez le package d'installation de votre hôte.
+
Vous pouvez télécharger le fichier d'installation à n'importe quel emplacement sur la machine sur laquelle vous souhaitez installer SnapManager pour Oracle.



http://mysupport.netapp.com/["Site de support NetApp : mysupport.netapp.com"]
