---
permalink: windows/task_clearing_user_credentials_for_all_hosts_repositories_and_profiles.html 
sidebar: sidebar 
keywords: clear, cache, credentials, resource, host, resource, profile, delete 
summary: 'Vous pouvez effacer la mémoire cache de vos informations d"identification pour les ressources (hôtes, référentiels et profils). Ceci supprime toutes les informations d"identification de ressource pour l"utilisateur exécutant la commande. Après avoir effacé le cache, vous devez à nouveau authentifier vos identifiants pour accéder à ces ressources sécurisées.' 
---
= Suppression des informations d'identification utilisateur pour tous les hôtes, référentiels et profils
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effacer la mémoire cache de vos informations d'identification pour les ressources (hôtes, référentiels et profils). Ceci supprime toutes les informations d'identification de ressource pour l'utilisateur exécutant la commande. Après avoir effacé le cache, vous devez à nouveau authentifier vos identifiants pour accéder à ces ressources sécurisées.

. Pour effacer vos informations d'identification, entrez la commande d'effacement des informations d'identification smo dans l'interface de ligne de commande SnapManager ou sélectionnez *Admin* > *Credentials* > *Clear cache* dans l'interface graphique de SnapManager.
. Quittez l'interface graphique de SnapManager.
+
REMARQUE :

+
** Si vous avez effacé le cache des informations d'identification de l'interface graphique SnapManager, il n'est pas nécessaire de quitter l'interface graphique SnapManager.
** Si vous avez effacé le cache des informations d'identification de l'interface de ligne de commande SnapManager, vous devez redémarrer l'interface graphique de SnapManager.
** Si vous avez supprimé manuellement le fichier d'informations d'identification cryptées, vous devez redémarrer l'interface graphique de SnapManager.


. Pour définir à nouveau les informations d'identification, répétez le processus pour définir les informations d'identification du référentiel, de l'hôte du profil et du profil. Pour plus d'informations sur la configuration des informations d'identification de l'utilisateur, reportez-vous à la section « Définition des informations d'identification après effacement du cache des informations d'identification ».


*Informations connexes*

xref:reference_the_smosmsapcredential_clear_command.adoc[La commande smo Credential clear]
