---
permalink: unix-administration/concept_what_user_authentication_is.html 
sidebar: sidebar 
keywords: addition, role-based, access, control, rbac, snapmanager, authenticate, operating, system, os 
summary: 'Outre l"utilisation du contrôle d"accès basé sur des rôles (RBAC), SnapManager authentifie l"utilisateur à l"aide d"une connexion du système d"exploitation sur l"hôte sur lequel le serveur SnapManager est exécuté. Vous pouvez activer l"authentification utilisateur via des invites de mot de passe sur les opérations ou à l"aide de la commande smo Credential set.' 
---
= Qu'est-ce que l'authentification utilisateur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Outre l'utilisation du contrôle d'accès basé sur des rôles (RBAC), SnapManager authentifie l'utilisateur à l'aide d'une connexion du système d'exploitation sur l'hôte sur lequel le serveur SnapManager est exécuté. Vous pouvez activer l'authentification utilisateur via des invites de mot de passe sur les opérations ou à l'aide de la commande smo Credential set.

Les exigences d'authentification de l'utilisateur dépendent de l'endroit où l'opération est effectuée.

* Si le client SnapManager se trouve sur le même serveur que l'hôte SnapManager, vous êtes authentifié par les informations d'identification du système d'exploitation.
+
Vous n'êtes pas invité à saisir un mot de passe car vous êtes déjà connecté à l'hôte sur lequel le serveur SnapManager est exécuté.

* Si le client SnapManager et le serveur SnapManager se trouvent sur des hôtes différents, SnapManager doit vous authentifier auprès des deux identifiants du système d'exploitation.
+
SnapManager vous invite à saisir des mots de passe pour toute opération, si vous n'avez pas enregistré vos identifiants de système d'exploitation dans le cache des informations d'identification utilisateur SnapManager. Si vous entrez la commande smo Credential set -host, vous enregistrez les informations d'identification du système d'exploitation dans le fichier cache des informations d'identification SnapManager. SnapManager ne vous invite donc pas à saisir le mot de passe pour une opération.



Si vous êtes authentifié avec le serveur SnapManager, vous êtes considéré comme l'utilisateur efficace. L'utilisateur effectif pour toute opération doit être un compte utilisateur valide sur l'hôte sur lequel l'opération est exécutée. Par exemple, si vous exécutez une opération de clonage, vous devez pouvoir vous connecter à l'hôte de destination du clone.


NOTE: SnapManager pour Oracle peut échouer pour autoriser les utilisateurs créés dans les services Active Directory centraux, tels que LDAP et ADS. Pour vous assurer que l'authentification ne échoue pas, vous devez définir auth.disableServerAuthorization sur true.

En tant qu'utilisateur efficace, vous pouvez gérer les informations d'identification de la manière suivante :

* Vous pouvez également configurer SnapManager pour stocker les informations d'identification de l'utilisateur dans le fichier des informations d'identification de l'utilisateur SnapManager.
+
Par défaut, SnapManager ne stocke pas les informations d'identification de l'hôte. Vous pouvez modifier ce type de script, par exemple si vous avez des scripts personnalisés qui nécessitent un accès sur un hôte distant. L'opération de clonage à distance est un exemple d'opération SnapManager qui nécessite les identifiants de connexion d'un utilisateur pour un hôte distant. Pour que SnapManager se souvienne des informations d'identification de l'hôte de l'utilisateur dans le cache des informations d'identification de l'utilisateur SnapManager, définissez la propriété host.credentials.persister sur true dans le fichier smo.config.

* Vous pouvez autoriser l'accès des utilisateurs au référentiel.
* Vous pouvez autoriser l'accès des utilisateurs aux profils.
* Vous pouvez afficher toutes les informations d'identification utilisateur.
* Vous pouvez effacer les informations d'identification d'un utilisateur pour toutes les ressources (hôtes, référentiels et profils).
* Vous pouvez supprimer des informations d'identification pour des ressources individuelles (hôtes, référentiels et profils).

