---
permalink: unix-administration/concept_limitations_related_to_oracle_database.html 
sidebar: sidebar 
keywords: snapmanager, limitations, oracle, database, 10gr2, 11gr1, 11gr2, 12_c_, ocds, dnfs 
summary: Avant de commencer à travailler avec SnapManager, vous devez connaître les limites associées à la base de données Oracle. 
---
= Limites relatives à la base de données Oracle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de commencer à travailler avec SnapManager, vous devez connaître les limites associées à la base de données Oracle.

Les limites sont les suivantes :

* SnapManager prend en charge Oracle versions 10gR2, 11gR1, 11gR2 et 12__c__, mais ne prend pas en charge Oracle 10gR1 comme référentiel ou base de données cible.
* SnapManager ne prendra pas en charge l'utilisation d'une adresse IP DE SCAN à la place d'un nom d'hôte.
+
SCAN IP est une nouvelle fonctionnalité d'Oracle 11gR2.

* SnapManager ne prend pas en charge Oracle Cluster File System (OCFS).
* Oracle 11g dans un environnement NFS direct (dNFS) permet d'ajouter des configurations de points de montage dans le fichier oranfstab, telles que plusieurs chemins d'accès pour l'équilibrage de charge.
+
SnapManager ne modifie pas le fichier oranfstab. Vous devez ajouter manuellement toutes les propriétés supplémentaires que vous souhaitez que la base de données clonée utilise, dans le fichier oranfstab.

* La prise en charge d'Oracle Database 9i est obsolète par rapport à SnapManager 3.2.
* La prise en charge d'Oracle Database 10gR2 (antérieure à 10.2.0.5) est obsolète par rapport à SnapManager 3.3.1.



NOTE: Identifier les différentes versions des bases de données Oracle prises en charge en faisant référence à la matrice d'interopérabilité.

*Informations connexes*

http://support.netapp.com/NOW/products/interoperability/["Matrice d'interopérabilité : support.netapp.com/NOW/products/interoperability"]
