---
permalink: unix-administration/concept_variables_available_in_custom_script_for_restore_operation.html 
sidebar: sidebar 
keywords: snapmanager, context, information, environment, variable, restore, operation 
summary: 'SnapManager fournit des informations contextuelles sous forme de variables d"environnement associées à l"opération de restauration en cours. Par exemple, votre script peut récupérer le nom de l"hôte d"origine et le libellé de la sauvegarde restaurée.' 
---
= Variables disponibles dans les scripts de tâches pour l'opération de restauration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager fournit des informations contextuelles sous forme de variables d'environnement associées à l'opération de restauration en cours. Par exemple, votre script peut récupérer le nom de l'hôte d'origine et le libellé de la sauvegarde restaurée.

Le tableau suivant répertorie les variables d'environnement que vous pouvez utiliser dans vos scripts :

|===
| Variables | Description | Format 


 a| 
ID_OPÉRATION_SM
 a| 
Spécifie l'ID de l'opération en cours
 a| 
chaîne



 a| 
NOM_PROFIL_SM
 a| 
Spécifie le nom du profil utilisé
 a| 
chaîne



 a| 
HÔTE_SM
 a| 
Spécifie le nom d'hôte de la base de données
 a| 
chaîne



 a| 
SM_OS_USER
 a| 
Indique le propriétaire du système d'exploitation de la base de données
 a| 
chaîne



 a| 
SM_OS_GROUP
 a| 
Spécifie le groupe OS de la base de données
 a| 
chaîne



 a| 
SM_BACKUP_TYPE
 a| 
Spécifie le type de sauvegarde (en ligne, hors ligne ou auto)
 a| 
chaîne



 a| 
SM_BACKUP_LABEL
 a| 
Spécifie l'étiquette de sauvegarde
 a| 
chaîne



 a| 
ID_SAUVEGARDE_SM
 a| 
Spécifie l'ID de sauvegarde
 a| 
chaîne



 a| 
SM_BACKUP_PROFILE
 a| 
Spécifie le profil utilisé pour la sauvegarde
 a| 
chaîne



 a| 
SM_RECOVERY_TYPE
 a| 
Spécifie les informations sur la configuration de la récupération
 a| 
chaîne



 a| 
SM_VOLUME_RESTORE_MODE
 a| 
Spécifie la configuration de restauration de volume
 a| 
chaîne



 a| 
NOM_FILER_CIBLE_SM
 a| 
Spécifie le nom du système de stockage cible *Remarque :* si plusieurs systèmes de stockage sont utilisés, les noms du système de stockage doivent être séparés par des virgules.
 a| 
chaîne



 a| 
SM_TARGET_VOLUME_NAME
 a| 
Spécifie le nom du volume cible *Remarque :* le nom du volume cible doit être préfixé avec le nom du périphérique de stockage, par exemple SM_TARGET_FILER_NAME/SM_TARGET_VOLUME_NAME.
 a| 
chaîne



 a| 
SM_HOST_FILE_SYSTEM
 a| 
Spécifie le système de fichiers hôte
 a| 
chaîne



 a| 
SM_SNAPSHOT_NAMES
 a| 
Spécifie la liste de snapshots *Remarque :* le nom des copies Snapshot doit être préfixé avec le nom du système de stockage et le nom du volume. Les noms des copies Snapshot sont séparés par une virgule.
 a| 
tableau de chaînes



 a| 
SM_ASM_DISK_GROUPS
 a| 
Spécifie la liste Groupe de disques ASM
 a| 
tableau de chaînes



 a| 
SM_ARCHIVE_LOGS_RÉPERTOIRE
 a| 
Spécifie le répertoire des journaux d'archives *Remarque :* si les journaux d'archives sont situés dans plusieurs répertoires, les noms de ces répertoires sont séparés par des virgules.
 a| 
tableau de chaînes



 a| 
SM_REDO_LOGS_DIRECTORY
 a| 
Spécifie le répertoire des journaux de reprise *Remarque :* si les journaux de reprise se trouvent dans plusieurs répertoires, les noms de ces répertoires sont séparés par des virgules.
 a| 
tableau de chaînes



 a| 
SM_CONTROL_FILES_DIRECTORY
 a| 
Spécifie le répertoire des fichiers de contrôle *Remarque :* si les fichiers de contrôle se trouvent dans plusieurs répertoires, les noms de ces répertoires sont séparés par des virgules.
 a| 
tableau de chaînes



 a| 
SM_DATA_FILES_DIRECTORY
 a| 
Spécifie le répertoire des fichiers de données *Remarque :* si les fichiers de données se trouvent dans plusieurs répertoires, les noms de ces répertoires sont séparés par des virgules.
 a| 
tableau de chaînes

|===