---
permalink: unix-administration/concept_collecting_additional_log_information_for_easier_debugging.html 
sidebar: sidebar 
keywords: additional, log, debug, fail, snapmanager, operation, external, environment, variable 
summary: 'Si vous avez besoin de journaux supplémentaires pour déboguer une opération SnapManager ayant échoué, vous devez définir une variable d"environnement externe Server.log.level. Cette variable remplace le niveau de journal par défaut et vide tous les messages du journal dans le fichier journal. Par exemple, vous pouvez changer le niveau de journalisation en DEBUG, qui consigne des messages supplémentaires et peut aider au débogage des problèmes.' 
---
= Collecte d'informations de journal supplémentaires pour faciliter le débogage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous avez besoin de journaux supplémentaires pour déboguer une opération SnapManager ayant échoué, vous devez définir une variable d'environnement externe Server.log.level. Cette variable remplace le niveau de journal par défaut et vide tous les messages du journal dans le fichier journal. Par exemple, vous pouvez changer le niveau de journalisation en DEBUG, qui consigne des messages supplémentaires et peut aider au débogage des problèmes.

Les journaux SnapManager sont disponibles aux emplacements suivants :

* /var/log/smo


Pour remplacer le niveau de journalisation par défaut, vous devez effectuer les opérations suivantes :

. Créez un fichier texte Platform.override dans le répertoire d'installation de SnapManager.
. Ajoutez le paramètre Server.log.level dans le fichier texte Platform.override.
. Attribuer une valeur (TRACE, DÉBOGAGE, INFO, AVERTISSEMENT, ERREUR, FATAL, ou PROGRESS) vers le paramètre Server.log.level.
+
Par exemple, pour changer le niveau de journal en ERREUR, définissez la valeur de Server.log.level sur ERREUR.

+
Server.log.level=ERREUR

. Redémarrez le serveur SnapManager.



NOTE: Si les informations de journal supplémentaires ne sont pas requises, vous pouvez supprimer le paramètre Server.log.level du fichier texte Platform.override.

SnapManager gère le volume des fichiers journaux du serveur en se basant sur les valeurs définies par l'utilisateur des paramètres suivants dans le fichier smo.config :

* log.max_log_files
* log.max_log_file_size
* log.max_rolling_operation_factory_logs

