---
permalink: unix-administration/reference_the_smosmsapbackup_restore_command.html 
sidebar: sidebar 
keywords: run, backup, restore, command, database, portion, optional, smo, information 
summary: 'Vous pouvez exécuter la commande backup restore pour restaurer les sauvegardes d"une base de données ou d"une partie d"une base de données, puis éventuellement récupérer les informations de la base de données.' 
---
= Commande smo backup restore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter la commande backup restore pour restaurer les sauvegardes d'une base de données ou d'une partie d'une base de données, puis éventuellement récupérer les informations de la base de données.



== Syntaxe

[listing]
----

        smo backup restore
-profile profile_name
\[-label label \| -id id\]
\[-files files \[files...\] \|
-tablespaces tablespaces \[tablespaces...\]\] \|
-complete \| -controlfiles\]
\[-recover \{-alllogs \| -nologs \| -until until\} \[-using-backup-controlfile\] \]
\[-restorespec restorespec \| -from-secondary \[-temp-volume temp_volume\] \[-copy-id id\]\]
\[-preview\]
\[-fast \{-require \| -override \| -fallback \| -off\}\]
\[-recover-from-location path1 \[, path2\]\]
\[-taskspec taskspec\]
\[-dump\]
\[-force\]
\[-quiet \| -verbose\]
----


== Paramètres

* *-profil nom_profil*
+
Indique la base de données à restaurer. Le profil contient l'identifiant de la base de données et d'autres informations sur la base de données.

* *-label nom*
+
Restaure la sauvegarde avec l'étiquette spécifiée.

* *-id guid*
+
Restaure la sauvegarde à l'aide du GUID spécifié. Le GUID est généré par SnapManager lors de la création d'une sauvegarde. Vous pouvez utiliser la commande SMO backup list pour afficher le GUID pour chaque sauvegarde.

* *Choisissez tous les fichiers ou les fichiers spécifiés*
+
Vous pouvez également utiliser l'une des options suivantes :

+
** -Complete : restaure tous les fichiers de données de la sauvegarde.
** -Tabespacelist: Restaure uniquement les espaces de table spécifiés de la sauvegarde.
+
Vous devez utiliser des espaces pour séparer les noms de la liste.

** -Fileslist: Restaure uniquement les fichiers de données spécifiés à partir de la sauvegarde.
+
Vous devez utiliser des espaces pour séparer les noms de la liste. Si la base de données est en cours d'exécution, SnapManager garantit que l'espace table contenant les fichiers est hors ligne.



* *-controlfiles*
+
Restaure les fichiers de contrôle. SnapManager vous permet de restaurer les fichiers de contrôle ainsi que les fichiers de données à partir de sauvegardes en une seule opération. L'option -controlfiles est indépendante des autres paramètres d'étendue de restauration tels que -Complete, -tablespaces et -Files.

* *-récupérer*
+
Restaure la base de données après la restauration. Vous devez également spécifier le point auquel SnapManager doit restaurer la base de données à l'aide de l'une des options suivantes :

+
** -Nologs : récupère la base de données au moment de la sauvegarde et n'applique aucun journal.
+
Vous pouvez utiliser ce paramètre pour les sauvegardes en ligne ou hors ligne.

** -Alllogs: Récupère la base de données à la dernière transaction ou commit, et applique tous les journaux requis.
** -Jusqu'à la date : récupère la base de données jusqu'à la date et l'heure spécifiées.
+
Vous devez utiliser le format année-mois-date: Heure: Minute: Seconde (aaaa-mm-jj:hh:mm:ss). Pour les heures, utilisez le format 12 heures ou 24 heures, selon le paramètre de la base de données.

** -Jusqu'à scn: Fait avancer les fichiers de données jusqu'à ce qu'il atteigne le numéro de changement du système spécifié (SCN).
** -Using-backup-controlfile : récupère la base de données à l'aide du fichier de contrôle de sauvegarde.


* *-restaurable*
+
Vous permet de restaurer les données sur un système de fichiers actif et de les restaurer à partir des données spécifiées en fournissant un mappage de chaque copie Snapshot originale vers son système de fichiers actif. Si vous ne spécifiez pas d'option, SnapManager restaure les données à partir des copies Snapshot sur le stockage primaire. Vous pouvez spécifier l'une des options suivantes :

+
** -Restorespec : spécifie les données à restaurer et le format de restauration.
** -Depuis le secondaire : restaure les données à partir du stockage secondaire.
+
Vous ne pouvez pas utiliser cette option si la sauvegarde existe sur le stockage primaire ; la sauvegarde primaire doit être libérée avant de pouvoir restaurer une sauvegarde à partir du stockage secondaire. Si vous utilisez un volume temporaire, vous devez spécifier le volume à l'aide de l'option -temp-volume.

+
Vous devez spécifier l'option -copy-ID lorsque vous spécifiez l'option -from-Secondary. S'il existe plusieurs sauvegardes sur le système de stockage secondaire, l'option -copy-ID permet de spécifier la copie de sauvegarde sur le stockage secondaire à utiliser pour l'opération de restauration.

+

NOTE: Si vous utilisez Data ONTAP sous 7-mode, vous devez indiquer une valeur valide pour l'option -copy-ID. Cependant, si vous utilisez clustered Data ONTAP, l'option -copy-ID n'est pas requise

+
Lors d'une restauration à partir d'un stockage secondaire, SnapManager procède d'abord à une restauration des données directement depuis le système de stockage secondaire vers le système de stockage primaire (sans impliquer l'hôte). Si SnapManager ne peut pas effectuer ce type de restauration (par exemple, si les fichiers ne font pas partie du système de fichiers), SnapManager revient à une copie de fichier côté hôte. SnapManager propose deux méthodes pour effectuer une restauration de copie de fichier côté hôte à partir d'un stockage secondaire. La méthode sélectionnée par SnapManager est configurée dans le fichier smo.config.

** Direct : SnapManager clone les données sur un système de stockage secondaire, monte les données clonées du système de stockage secondaire sur l'hôte, puis copie les données hors du clone dans l'environnement actif.
+
Il s'agit de la stratégie d'accès secondaire par défaut.

** Indirect : SnapManager copie d'abord les données sur un volume temporaire du stockage primaire, monte les données du volume temporaire sur l'hôte, puis copie les données hors du volume temporaire dans l'environnement actif.
+
Cette règle doit être utilisée uniquement si l'hôte ne dispose pas d'un accès direct au système de stockage secondaire. Les restaurations à l'aide de la méthode indirecte prennent deux fois plus de temps que la règle d'accès secondaire direct, car deux copies de ces données sont créées.



+
La décision d'utiliser la méthode directe ou indirecte est contrôlée par la valeur du paramètre restore.secondaryAccessPolicy dans le fichier de configuration smo.config.

* *-aperçu*
+
Affiche les informations suivantes :

+
** Quel mécanisme de restauration (restauration rapide, restauration du système de fichiers côté stockage, restauration de fichiers côté stockage ou restauration de copie de fichiers côté hôte) sera utilisé pour restaurer chaque fichier
** Pourquoi des mécanismes plus efficaces n'ont pas été utilisés pour restaurer chaque fichier, lorsque vous spécifiez l'option -verbose si vous utilisez l'option -preview, vous devez savoir ce qui suit :
** L'option -force n'a aucun impact sur la commande.
** L'option -recover n'a aucun impact sur la commande.
** L'option -FAST (-exiger, -override, -fallback ou -off) a un impact significatif sur la sortie. Pour prévisualiser l'opération de restauration, la base de données doit être montée. Si vous souhaitez prévisualiser un plan de restauration et que la base de données n'est pas actuellement montée, SnapManager monte la base de données. Si la base de données ne peut pas être montée, alors la commande échoue et SnapManager renvoie la base de données à son état d'origine.


+
L'option -preview affiche jusqu'à 20 fichiers. Vous pouvez configurer le nombre maximal de fichiers à afficher dans le fichier smo.config.

* *-rapide*
+
Vous permet de choisir le processus à utiliser dans l'opération de restauration. Vous pouvez forcer SnapManager à utiliser le processus de restauration rapide basé sur les volumes plutôt que d'autres processus de restauration, si toutes les conditions d'éligibilité à la restauration sont remplies. Si vous savez qu'une restauration de volume ne peut pas être effectuée, vous pouvez également utiliser cette procédure pour empêcher SnapManager de réaliser des vérifications d'éligibilité et de restauration à l'aide du processus de restauration rapide.

+
L'option -FAST inclut les paramètres suivants :

+
** -Exiger : vous permet de forcer SnapManager à effectuer une restauration de volume si toutes les conditions d'éligibilité de restauration sont remplies.
+
Si vous spécifiez l'option -FAST, mais ne spécifiez aucun paramètre pour -FAST, SnapManager utilise le paramètre -exiger comme paramètre par défaut.

** -Override : permet de remplacer les vérifications d'admissibilité non obligatoires et d'exécuter le processus de restauration rapide basé sur le volume.
** -Fallback : permet de restaurer la base de données à l'aide de toute méthode que SnapManager détermine.
+
Si vous ne spécifiez pas l'option -FAST, SnapManager utilise l'option par défaut backup restore -FAST fallback.

** -Off : vous permet d'éviter le temps nécessaire pour effectuer les vérifications d'admissibilité.


* *-récupération-de-l'emplacement*
+
Indique l'emplacement du journal d'archivage externe des fichiers journaux d'archive. SnapManager enregistre les fichiers journaux d'archivage à partir de l'emplacement externe et les utilise pour le processus de restauration.

* *-taskspspspspspspspspec
+
Spécifie le fichier XML de spécification de tâche pour l'activité de prétraitement ou de post-traitement de l'opération de restauration. Vous devez fournir le chemin complet du fichier XML de spécification de tâche.

* *-dump*
+
Indique de collecter les fichiers de vidage après l'opération de restauration.

* *-force*
+
Change l'état de la base de données à un état inférieur à son état actuel, si nécessaire. Pour les clusters Real application (RAC), vous devez inclure l'option -force si SnapManager doit modifier l'état d'une instance RAC en état inférieur.

+
Par défaut, SnapManager peut indiquer un état plus élevé dans la base de données au cours d'une opération. Cette option n'est pas requise pour que SnapManager change l'état de la base de données à supérieur.

* *-calme*
+
Affiche uniquement les messages d'erreur dans la console. Le paramètre par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche les messages d'erreur, d'avertissement et d'information dans la console. Vous pouvez utiliser cette option pour voir pourquoi des processus de restauration plus efficaces n'ont pas pu être utilisés pour restaurer le fichier.





== Exemple

L'exemple suivant illustre la restauration d'une base de données avec les fichiers de contrôle :

[listing]
----
smo backup restore -profile SALES1 -label full_backup_sales_May
-complete -controlfiles -force
----
*Informations connexes*

xref:concept_restoring_database_backup.adoc[Restauration des sauvegardes de bases de données]

xref:task_restoring_backups_from_an_alternate_location.adoc[Restauration des sauvegardes à partir d'un autre emplacement]

xref:task_creating_restore_specifications.adoc[Création de spécifications de restauration]
