---
permalink: unix-administration/reference_the_smosmsapprotection_policy_command.html 
sidebar: sidebar 
keywords: run, protection-policy, command, list, protection, policies, applied, smo 
summary: 'Vous pouvez exécuter la commande protection-policy pour lister les règles de protection qui peuvent être appliquées à un profil. La règle de protection peut être appliquée lorsqu"un nouveau profil est créé ou qu"un profil existant est mis à jour. Vous pouvez également définir la stratégie de protection du profil à l"aide de la console protection Manager.' 
---
= Commande smo protection-policy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter la commande protection-policy pour lister les règles de protection qui peuvent être appliquées à un profil. La règle de protection peut être appliquée lorsqu'un nouveau profil est créé ou qu'un profil existant est mis à jour. Vous pouvez également définir la stratégie de protection du profil à l'aide de la console protection Manager.



== Syntaxe

[listing]
----

        smo protection-policy list
----

NOTE: Pour que vous puissiez utiliser cette commande, protection Manager et SnapDrive doivent être installés sur le serveur.



== Paramètres

* *liste*
+
Affiche la liste des règles de protection pouvant être définies sur un profil.





== Exemple

L'exemple suivant répertorie les règles de protection pouvant être définies sur un profil :

[listing]
----
 smo protection-policy list
----
[listing]
----

Back up
Back up, then mirror
Chain of two mirrors
DR Back up
DR Back up, then mirror
DR Mirror
DR Mirror and back up
DR Mirror and mirror
DR Mirror, then back up
DR Mirror, then mirror
Local backups only
Mirror
Mirror and back up
Mirror to two destinations
Mirror, then back up
No protection
Partial-volume Mirror
Remote backups only
----
*Informations connexes*

xref:concept_managing_profiles_for_efficient_backups.adoc[Gestion des profils pour des sauvegardes efficaces]
