---
permalink: unix-administration/reference_the_smosmsaprepository_show_command.html 
sidebar: sidebar 
keywords: command, display, information, repository, smo 
summary: Cette commande affiche des informations sur le référentiel. 
---
= Commande smo repository show
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande affiche des informations sur le référentiel.



== Syntaxe

[listing]
----

        smo repository show
-repository
-dbname repo_service_name
-host repo_host
-port repo_port
-login -username repo_username
\[-quiet \| -verbose\]
----


== Paramètres

* *-référentiel*
+
Les options suivantes -repository spécifient les détails de la base de données pour le référentiel.

* *-dbname repo_service_name*
+
Indique le nom de la base de données qui stocke le référentiel. Utilisez le nom global ou le SID.

* *-hôte repo_host*
+
Indique le nom ou l'adresse IP de l'ordinateur hôte sur lequel s'exécute la base de données de référentiel.

* *-connexion*
+
Démarre les détails de connexion au référentiel.

* *-username repo_username*
+
Indique le nom d'utilisateur nécessaire pour accéder à la base de données qui stocke le référentiel.

* *-port repo_port*
+
Spécifie le numéro de port TCP utilisé pour accéder à la base de données qui stocke le référentiel.

* *-calme*
+
Affiche uniquement les messages d'erreur sur la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche des messages d'erreur, d'avertissement et d'information sur la console.





== Exemple de commande

L'exemple suivant présente des détails sur le référentiel dans la base de données SALESDB.

[listing]
----
smo repository show -repository -dbname SALESDB -host server1
-port 1521 -login -username admin
Repository Definition:
User Name: admin
Host Name: server1
Database Name: SALESDB
Database Port: 1521
Version: 28
Hosts that have run operations using this repository: 2
server2
server3
Profiles defined in this repository: 2
GSF5A
GSF3A
Incomplete Operations: 0
----