---
permalink: unix-administration/reference_the_smosmsap_repository_rollingback_command.html 
sidebar: sidebar 
keywords: command, enable, rollback, revert, higher, version, snapmanager, original, version, upgrade, smo, repository 
summary: 'Cette commande vous permet de revenir à la version d"origine à partir de laquelle vous avez effectué la mise à niveau ou de revenir d"une version supérieure de SnapManager.' 
---
= Commande de restauration du référentiel smo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande vous permet de revenir à la version d'origine à partir de laquelle vous avez effectué la mise à niveau ou de revenir d'une version supérieure de SnapManager.



== Syntaxe

[listing]
----

        smo repository rollback
-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username
-port repo_port
-rollbackhost host_with_target_database
[-force]
\[-quiet \| -verbose\]
----


== Paramètres

* *-référentiel*
+
Les options suivantes -repository spécifient les détails de la base de données pour le référentiel.

* *-dbname repo_service_name*
+
Indique le nom de la base de données qui stocke le référentiel. Utilisez le nom global ou le SID.

* *-hôte repo_host*
+
Indique le nom ou l'adresse IP de l'ordinateur hôte sur lequel s'exécute la base de données de référentiel.

* *-connexion*
+
Démarre les détails de connexion au référentiel.

* *-username repo_username*
+
Indique le nom d'utilisateur nécessaire pour accéder à la base de données qui stocke le référentiel.

* *-rollbackhost_with_target_database*
+
Spécifie le nom de l'hôte qui sera restauré à partir d'une version supérieure de SnapManager vers la version inférieure d'origine.

* *-port repo_port*
+
Spécifie le numéro de port TCP utilisé pour accéder à la base de données qui stocke le référentiel.

* *-force*
+
Tente de forcer la mise à jour du référentiel. SnapManager vous invite à effectuer une sauvegarde du référentiel actuel avant la mise à jour.

* *-noprompt*
+
N'affiche pas l'invite avant la mise à jour de la base de données du référentiel. L'option -noprompt permet de s'assurer que l'invite n'apparaît pas, ce qui facilite la mise à jour des référentiels à l'aide d'un script.

* *-calme*
+
Affiche uniquement les messages d'erreur sur la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche des messages d'erreur, d'avertissement et d'information sur la console.





== Exemple de commande

L'exemple suivant met à jour le référentiel dans la base de données SALESDB.

[listing]
----
smo repository rollback -repository -dbname SALESDB
-host server1 -login -username admin -port 1521 -rollbackhost hostA
----