---
permalink: unix-administration/reference_the_smosmsapcredential_clear_command.html 
sidebar: sidebar 
keywords: command, clear, cache, user, credentials, secure, resource, smo 
summary: 'Cette commande efface le cache des informations d"identification de l"utilisateur pour toutes les ressources sécurisées.' 
---
= La commande smo Credential clear
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande efface le cache des informations d'identification de l'utilisateur pour toutes les ressources sécurisées.



== Syntaxe

[listing]
----

        smo credential clear
\[-quiet \| -verbose\]
----


== Paramètres

* *-calme*
+
Affiche uniquement les messages d'erreur sur la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche des messages d'erreur, d'avertissement et d'information sur la console.





== Exemple de commande

Cet exemple efface toutes les informations d'identification de l'utilisateur exécutant la commande.

[listing]
----
smo credential clear -verbose
----
[listing]
----
SMO-20024 [INFO ]: Cleared credentials for user "user1".
----
*Informations connexes*

xref:task_clearing_user_credentials_for_all_hosts_repositories_and_profiles.adoc[Suppression des informations d'identification utilisateur pour tous les hôtes, référentiels et profils]
