---
permalink: unix-administration/reference_troubleshooting_known_issues.html 
sidebar: sidebar 
keywords: aware, known, issue, snapmanager, troubleshoot, identify, cluster-mode 
summary: Vous devez connaître certains problèmes connus qui peuvent survenir lorsque vous utilisez SnapManager et savoir comment les contourner. 
---
= Dépannage des problèmes connus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez connaître certains problèmes connus qui peuvent survenir lorsque vous utilisez SnapManager et savoir comment les contourner.



== SnapManager for Oracle n'identifie pas les profils Cluster-mode

Si le nom de profil Cluster-mode n'est pas présent dans le fichier cmode_profiles.config du répertoire d'installation de SnapManager pour Oracle, le message d'erreur suivant peut se déclencher :

Veuillez configurer DFM Server à l'aide de l'ensemble de configuration SnapDrive -dfm nom_utilisateur nom_appliance.

De même, lors de la mise à niveau de SnapManager pour Oracle, si vous supprimez le dossier /opt/NetApp/smo/*, le fichier cmode_profiles.config sur lequel les noms de profils Cluster-mode sont également supprimés. Ce problème déclenche également le même message d'erreur.

*Solution de contournement*

Mettre à jour le profil : mettre à jour le profil smo <nom_profil>


NOTE: Si SnapManager pour Oracle est installé dans le chemin /opt/NetApp/smo/, l'emplacement du fichier est /opt/NetApp/smo/cmode_profile/cmode_profiles.config.



== Le serveur ne démarre pas

Lors du démarrage du serveur, un message d'erreur semblable à ce qui suit peut s'afficher :

SMO-01104 : erreur lors de l'appel de la commande : SMO-17107 : le serveur SnapManager n'a pas pu démarrer sur le port 8074 en raison des erreurs suivantes : java.net.BindException: adresse déjà utilisée

Cela peut être dû au fait que les ports d'écoute SnapManager (27214 et 27215 par défaut) sont actuellement utilisés par une autre application.

Cette erreur peut également se produire si la commande smo_Server est déjà en cours d'exécution, mais SnapManager ne détecte pas le processus existant.

*Solution de contournement*

Vous pouvez reconfigurer le SnapManager ou l'autre application pour utiliser différents ports.

Pour reconfigurer SnapManager, modifiez le fichier suivant : /opt/NTAP/smo/propriétés/smo.config

Vous affectez les valeurs suivantes :

* SMO Server.port=27214
* SMO Server.rmiregistry.port=27215
* remote.registry.ocijdbc.port= 27215
+
Le port remote.registry.ocijdbc.port doit être identique à Server.rmiregistry.port.



Pour démarrer le serveur SnapManager, entrez la commande suivante : smo_Server start


NOTE: Un message d'erreur s'affiche si le serveur est déjà en cours d'exécution.

Si le serveur est déjà en cours d'exécution, effectuez les opérations suivantes :

. Arrêtez le serveur en entrant la commande suivante : smo_Server stop
. Redémarrez le serveur en entrant la commande suivante : smo_Server start




== Fermeture d'une opération SnapManager en cours d'exécution

Si le serveur SnapManager se bloque et que vous ne pouvez pas exécuter correctement les opérations, vous pouvez arrêter SnapManager et ses opérations.

*Solution de contournement*

SnapManager fonctionne avec SnapManager et protection Manager. Vous devez effectuer les étapes suivantes pour lister les différents processus en cours d'exécution et arrêter le dernier processus en cours d'exécution.

. Répertoriez tous les processus SnapDrive en cours d'exécution : ps
+
Exemple : ps | grep SnapDrive

. Arrêtez le processus ou les processus SnapDrive : kill <pid>
+
pid est la liste des processus que vous avez trouvés à l'aide de la commande ps.

+

NOTE: N'arrêtez pas tous les processus SnapDrive. Vous pouvez ne vouloir terminer que le dernier processus en cours d'exécution.

. Si l'une des opérations implique la restauration d'une sauvegarde protégée à partir d'un stockage secondaire, ouvrez la console protection Manager et effectuez les opérations suivantes :
+
.. Dans le menu système, sélectionnez *travaux*.
.. Sélectionnez *Restaurer*.
.. Vérifiez le nom du jeu de données correspondant à celui du profil SnapManager.
.. Cliquez avec le bouton droit de la souris et sélectionnez *Annuler*.


. Lister les processus SnapManager :
+
.. Connectez-vous en tant qu'utilisateur root.
.. Répertoriez les processus à l'aide de la commande ps.
+
Exemple : ps | grep Java



. Fin du processus SnapManager : kill <pid>




== Impossible de supprimer ou de libérer la dernière sauvegarde protégée

Lorsque vous créez la première sauvegarde pour un profil sur un système de stockage secondaire, SnapManager envoie toutes les informations relatives à la sauvegarde à protection Manager. Pour les sauvegardes suivantes liées à ce profil, SnapManager n'envoie que les informations modifiées. Si vous supprimez la dernière sauvegarde protégée, SnapManager n'a plus la possibilité d'identifier les différences entre les sauvegardes et doit trouver un moyen de redéfinir la configuration de base de ces relations. Par conséquent, toute tentative de suppression de la dernière sauvegarde protégée entraîne l'affichage d'un message d'erreur.

*Solution de contournement*

Vous pouvez supprimer le profil ou uniquement la sauvegarde du profil.

Pour supprimer le profil, procédez comme suit :

. Supprimez les sauvegardes du profil.
. Mettez à jour le profil et désactivez la protection dans le profil.
+
Ceci supprime le jeu de données.

. Supprimez la dernière sauvegarde protégée.
. Supprimez le profil.


Pour supprimer uniquement la sauvegarde, effectuez les opérations suivantes :

. Créer une autre copie de sauvegarde du profil.
. Transférez cette copie de sauvegarde vers un système de stockage secondaire.
. Supprimez la copie de sauvegarde précédente.




== Impossible de gérer les noms de destination du fichier journal d'archives si les noms de destination font partie d'autres noms de destination

Lors de la création d'une sauvegarde du journal d'archivage, si l'utilisateur exclut une destination faisant partie d'autres noms de destination, les autres noms de destination sont également exclus.

Par exemple, supposons que trois destinations sont disponibles pour être exclues : /dest, /des1 et /des2. Lors de la création de la sauvegarde du fichier journal d'archives, si vous excluez /dest à l'aide de la commande

[listing]
----
smo backup create -profile almsamp1 -data -online -archivelogs  -exclude-dest /dest
----
, SnapManager pour Oracle exclut toutes les destinations commençant par /dest.

*Solution de contournement*

* Ajoutez un séparateur de chemin après la configuration des destinations dans v$archive_dest. Par exemple, définissez le /dest sur /dest/.
* Lors de la création d'une sauvegarde, incluez les destinations au lieu d'exclure toute destination.




== La restauration des fichiers de contrôle multiplexés sur la gestion automatique du stockage (ASM) et le stockage non ASM échoue

Lorsque les fichiers de contrôle sont multiplexés sur le stockage ASM et non ASM, l'opération de sauvegarde est réussie. Cependant, lorsque vous essayez de restaurer les fichiers de contrôle à partir de cette sauvegarde réussie, l'opération de restauration échoue.



== Échec de l'opération de clonage de SnapManager

Lorsque vous clonez une sauvegarde dans SnapManager, le serveur DataFabric Manager risque de ne pas détecter les volumes et d'afficher le message d'erreur suivant :

SMO-13032 : impossible d'effectuer l'opération : cloner la création. Cause principale : SMO-11007 : erreur lors du clonage de snapshot : FLOW-11019 : échec dans ExecuteConnectionSteps: SD-00018 : erreur lors de la détection du stockage pour /mnt/datas_clone3 : SD-10016 : erreur lors de l'exécution de la commande SnapDrive "/usr/sbin/snapdrive Storage show -fs /mFiler/clone3" : 0002-719.x.sur les serveurs de stockage/volumes.20091122235002515.ne peut pas accéder à l'utilisateur/VMware/consultez le gestionnaire/volumes.x.x.1

Motif : ressource spécifiée non valide. Impossible de trouver son ID sur le serveur Operations Manager 10.x.x.x

Cela se produit si le système de stockage possède un grand nombre de volumes.

*Solution de contournement*

Vous devez effectuer l'une des opérations suivantes :

* À partir du serveur Data Fabric Manager, exécuter l'hôte dfm Discover Storage_system.
+
Vous pouvez également ajouter la commande dans un fichier de script shell et planifier un travail dans le serveur DataFabric Manager afin d'exécuter le script à intervalles réguliers.

* Augmenter la valeur de dfm-rbac-retries dans le fichier SnapDrive.conf.
+
SnapDrive utilise la valeur de l'intervalle de rafraîchissement par défaut et le nombre de tentatives par défaut. La valeur par défaut de dfm-rbac-retry-Sleep-sec est de 15 secondes et dfm-rbac-retries est de 12 itérations.

+

NOTE: L'intervalle d'actualisation d'Operations Manager dépend du nombre de systèmes de stockage, du nombre d'objets de stockage du système et de la charge sur le serveur DataFabric Manager.

+
À titre de recommandation, effectuez les opérations suivantes :

+
.. À partir du serveur DataFabric Manager, lancer manuellement la commande suivante pour tous les systèmes de stockage secondaires associés au dataset : DFM host Discover Storage_system
.. Doubler le temps requis pour effectuer l'opération de découverte de l'hôte et attribuer cette valeur à dfm-rbac-retry-Sleep-sec.
+
Par exemple, si l'opération a pris 11 secondes, vous pouvez définir la valeur de dfm-rbac-retry-Sleep-sec à 22 (11*2).







== La taille des bases de données de référentiel augmente avec le temps et non avec le nombre de sauvegardes

La taille de la base de données de référentiel augmente avec le temps car les opérations SnapManager insèrent ou suppriment des données dans le schéma dans les tables de bases de données de référentiel, ce qui entraîne une utilisation élevée de l'espace d'indexation.

*Solution de contournement*

Vous devez surveiller et reconstruire les index conformément aux directives Oracle pour contrôler l'espace utilisé par le schéma du référentiel.



== L'interface graphique de SnapManager est inaccessible et les opérations de SnapManager échouent lorsque la base de données du référentiel est en panne

Les opérations SnapManager échouent et vous ne pouvez pas accéder à l'interface graphique lorsque la base de données du référentiel est en panne.

Le tableau suivant répertorie les différentes actions que vous pouvez effectuer et leurs exceptions :

|===


| Exploitation | Exceptions 


 a| 
Ouverture d'un référentiel fermé
 a| 
Le message d'erreur suivant est consigné dans sm_gui.log : [AVERTIR ] : SMO-01106 : erreur survenue lors de l'interrogation du référentiel : connexion fermée Java.sql.SQLException : connexion fermée.



 a| 
Actualisation d'un référentiel ouvert en appuyant sur F5
 a| 
Une exception de référentiel s'affiche dans l'interface utilisateur graphique et consigne également une exception NullPointerException dans le fichier sm_gui.log.



 a| 
Actualisation du serveur hôte
 a| 
Une NullPointerException est consignée dans le fichier sumo_gui.log.



 a| 
Création d'un nouveau profil
 a| 
Une exception NullPointerException s'affiche dans la fenêtre Configuration du profil.



 a| 
Actualisation d'un profil
 a| 
L'exception SQL suivante est consignée dans sm_gui.log : [AVERTIR ] : SMO-01106 : erreur lors de l'interrogation du référentiel : connexion fermée.



 a| 
Accès à une sauvegarde
 a| 
Le message d'erreur suivant est consigné dans sm_gui.log : échec de l'initialisation d'une collection.



 a| 
Affichage des propriétés de clone
 a| 
Le message d'erreur suivant est connecté à sm_gui.log et sumo_gui.log : échec de l'initialisation d'une collection.

|===
*Solution de contournement*

Vous devez vous assurer que la base de données du référentiel est en cours d'exécution lorsque vous souhaitez accéder à l'interface graphique ou exécuter des opérations SnapManager.



== Impossible de créer des fichiers temporaires pour la base de données clonée

Lorsque des fichiers d'espaces de table temporaires de la base de données cible sont placés dans des points de montage différents du point de montage des fichiers de données, l'opération de création de clone a réussi mais SnapManager ne parvient pas à créer de fichiers temporaires pour la base de données clonée.

*Solution de contournement*

Vous devez effectuer l'une des opérations suivantes :

* Assurez-vous que la base de données cible est définie de manière à ce que les fichiers temporaires soient placés au même point de montage que les fichiers de données.
* Créez ou ajoutez manuellement des fichiers temporaires dans la base de données clonée.




== Impossible de migrer le protocole de NFSv3 vers NFSv4

Vous pouvez migrer le protocole de NFSv3 vers NFSv4 en activant le paramètre enable-migrer-nfs-version dans le fichier snapdrive.conf. Lors de la migration, SnapDrive prend uniquement en compte la version du protocole, indépendamment des options de point de montage telles que rw, largefiles, nosuid, etc.

Toutefois, après la migration du protocole vers NFSv4, lorsque vous restaurez la sauvegarde créée à l'aide de NFSv3, la situation suivante se produit :

* Si NFSv3 et NFSv4 sont activés au niveau du stockage, la restauration réussit, mais elle est montée avec les options de point de montage disponibles pendant la sauvegarde.
* Si NFSv4 n'est activé que au niveau du stockage, la restauration réussit et seule la version du protocole (NFSv4) est conservée.
+
Cependant, les autres options de point de montage, telles que rw, largefiles, nosuid, etc., ne sont pas conservées.



*Solution de contournement*

Vous devez arrêter manuellement la base de données, démonter les points de montage de la base de données et monter avec les options disponibles avant la restauration.



== Échec de la sauvegarde de la base de données de secours Data Guard

Si un emplacement de journal d'archivage est configuré avec le nom de service de la base de données primaire, la sauvegarde de la base de données de secours Data Guard échoue.

*Solution de contournement*

Dans l'interface utilisateur graphique, vous devez effacer *spécifier l'emplacement du journal d'archives externes* correspondant au nom de service de la base de données principale.
