---
permalink: unix-administration/reference_supported_partition_devices.html 
sidebar: sidebar 
keywords: partition, snapmanager, support, device, red, hat, enterprise, linux, 5x, oracle 
summary: Vous devez connaître les différents périphériques de partition pris en charge par SnapManager. 
---
= Périphériques de partition pris en charge
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez connaître les différents périphériques de partition pris en charge par SnapManager.

Le tableau suivant fournit des informations sur les partitions et indique comment elles peuvent être activées pour différents systèmes d'exploitation :

|===
| Système d'exploitation | Partition unique | Partition multiple | Périphériques sans partition | Système de fichiers ou périphériques RAW 


 a| 
Red Hat Enterprise Linux 5x ou

Oracle Enterprise Linux 5 fois
 a| 
Oui.
 a| 
Non
 a| 
Non
 a| 
ext3*



 a| 
Red Hat Enterprise Linux 6 x or

Oracle Enterprise Linux 6x
 a| 
Oui.
 a| 
Non
 a| 
Non
 a| 
ext3 ou ext4*



 a| 
SUSE Linux Enterprise Server 11
 a| 
Oui.
 a| 
Non
 a| 
Non
 a| 
ext3*



 a| 
SUSE Linux Enterprise Server 10
 a| 
Non
 a| 
Non
 a| 
Oui.
 a| 
ext3***



 a| 
Red Hat Enterprise Linux 5x ou Lateror

Oracle Enterprise Linux 5x ou version ultérieure
 a| 
Oui.
 a| 
Non
 a| 
Oui.
 a| 
ASM avec ASMlib**



 a| 
SUSE Linux Enterprise Server 10 SP4or

SUSE Linux Enterprise Server 11
 a| 
Oui.
 a| 
Non
 a| 
Oui.
 a| 
ASM avec ASMlib**



 a| 
SUSE Linux Enterprise Server 10 SP4 ou Lateror

SUSE Linux Enterprise Server 11
 a| 
Oui.
 a| 
Non
 a| 
Non
 a| 
ASM sans ASMlib****

|===
Pour plus d'informations sur les versions de système d'exploitation prises en charge, reportez-vous à la matrice d'interopérabilité.
