---
permalink: unix-administration/reference_the_smosmsap_schedule_create_command.html 
sidebar: sidebar 
keywords: schedule, create, command, specific, time 
summary: 'Vous pouvez utiliser la commande schedule create pour planifier la création d"une sauvegarde à un moment donné.' 
---
= Commande de planification smo create
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser la commande schedule create pour planifier la création d'une sauvegarde à un moment donné.



== Syntaxe

[listing]
----

        smo schedule create
-profile profile_name
\[-full\{-auto \| -online \| -offline\}
\[-retain -hourly \| -daily \| -weekly \| -monthly \| -unlimited\]
\[-verify\]\] |
\[-data \[\[-files files \[files\]\] \|
\[-tablespaces tablespaces \[tablespaces\]\] \{-auto \| -online \| -offline\}
\[-retain -hourly \| -daily \| -weekly \| -monthly \| -unlimited\]
\[-verify\]\] |
\[-archivelogs\]}
\[-label label\]
\[-comment comment\]
\[-protect \| -noprotect \| -protectnow\]
\[-backup-dest path1 \[ , path2\]\]
\[-exclude-dest path1 \[ , path2\]\]
\[-prunelogs \{-all \| -until-scn until-scn \| -until -date  yyyy-MM-dd:HH:mm:ss\] \| -before \{-months \| -days \| -weeks \| -hours}}
-prune-dest prune_dest1,\[prune_dest2\]\]
-schedule-name schedule_name
\[-schedule-comment schedule_comment\]
-interval \{-hourly \| -daily \| -weekly \| -monthly \| -onetimeonly\}
-cronstring cron_string
-start-time \{start_time <yyyy-MM-dd HH:mm\>\}
-runasuser runasuser
\[-taskspec taskspec\]
-force
\[-quiet \| -verbose\]
----


== Paramètres

* *-profil nom_profil*
+
Indique le nom du profil associé à la base de données pour lequel vous souhaitez planifier la sauvegarde. Le profil contient l'identifiant de la base de données et d'autres informations sur la base de données.

* *-auto option*
+
Si la base de données est dans un état monté ou hors ligne, SnapManager effectue une sauvegarde hors ligne. Si la base de données est à l'état ouvert ou en ligne, SnapManager effectue une sauvegarde en ligne. Si vous utilisez l'option -force avec l'option -offline, SnapManager force une sauvegarde hors ligne, même si la base de données est actuellement en ligne.

* *-option en ligne*
+
Spécifie une sauvegarde de base de données en ligne.

+
Vous pouvez créer une sauvegarde en ligne d'une base de données RAC (Real application clusters), tant que le système primaire est à l'état ouvert ou monté et qu'une instance est à l'état ouvert. Vous pouvez utiliser l'option -force pour les sauvegardes en ligne si l'instance locale est à l'état d'arrêt, ou si aucune instance n'est ouverte.

+
** Si l'instance locale est à l'état d'arrêt et qu'au moins une instance est ouverte, vous pouvez utiliser l'option -force pour modifier l'instance locale sur montée.
** Si aucune instance n'est à l'état ouvert, vous pouvez utiliser l'option -force pour modifier l'instance locale pour l'ouvrir.


* *-hors ligne option*
+
Spécifie une sauvegarde hors ligne lorsque la base de données est à l'état d'arrêt. Si la base de données est à l'état ouvert ou monté, la sauvegarde échoue. Si l'option -force est utilisée, SnapManager tente de modifier l'état de la base de données pour arrêter la base de données pour une sauvegarde hors ligne.

* *-option complète*
+
Sauvegarde l'intégralité de la base de données. Cela inclut toutes les données, le journal archivé et les fichiers de contrôle. Les journaux de reprise archivés et les fichiers de contrôle sont sauvegardés quel que soit le type de sauvegarde que vous effectuez. Pour sauvegarder uniquement une partie de la base de données, utilisez l'option -files ou -tablespaces.

* *-liste de fichiers*
+
Sauvegarde uniquement les fichiers de données spécifiés, ainsi que les fichiers de journal et de contrôle archivés. Séparez la liste des noms de fichiers par des espaces. Si la base de données est à l'état ouvert, SnapManager vérifie que les tablespaces appropriés sont en mode de sauvegarde en ligne.

* *-espaces de stockage*
+
Sauvegarde uniquement les espaces de stockage de base de données spécifiés ainsi que les fichiers de journal et de contrôle archivés. Séparez les noms des espaces de table. Si la base de données est à l'état ouvert, SnapManager vérifie que les tablespaces appropriés sont en mode de sauvegarde en ligne.

* *-label nom*
+
Spécifie un nom facultatif pour cette sauvegarde. Ce nom doit être unique dans le profil. Le nom peut contenir des lettres, des chiffres, des traits de soulignement (_) et un trait d'Union (-). Il ne peut pas commencer par un tiret.

+
Si vous ne spécifiez pas d'étiquette, SnapManager crée une étiquette par défaut au format Scope_type_date :

+
** La portée est soit F pour indiquer une sauvegarde complète, soit P pour indiquer une sauvegarde partielle.
** Le type est C pour indiquer une sauvegarde hors ligne (à froid), H pour indiquer une sauvegarde en ligne (à chaud) ou A pour indiquer une sauvegarde automatique, par exemple P_A_20081010060037IST.
** Date correspond à l'année, au mois, au jour et à l'heure de la sauvegarde.
+
SnapManager utilise une horloge de 24 heures.



+
Par exemple, si vous avez effectué une sauvegarde complète avec la base de données hors ligne le 16 janvier 2007 16, à 5 h 45 Heure normale de l'est, SnapManager créerait l'étiquette F_C_20070116174516EST.

* *-chaine de commentaire*
+
Spécifie un commentaire facultatif décrivant cette sauvegarde. Placez la chaîne entre guillemets simples (').

+

NOTE: Certains guillemets de bande de coques sont désactivés. Si c'est vrai pour votre shell, vous devez inclure le guillemets avec une barre oblique inverse (\). Par exemple, vous devrez peut-être entrer : `\' this is a comment\'`.

* *-vérifier option*
+
Vérifie que les fichiers de la sauvegarde ne sont pas corrompus en exécutant l'utilitaire dbv d'Oracle.

+

NOTE: Si vous spécifiez l'option -verify, l'opération de sauvegarde n'est pas terminée tant que l'opération de vérification n'est pas terminée.

* *-force option*
+
Force un changement d'état si la base de données n'est pas à l'état correct. Par exemple, SnapManager peut passer de l'état en ligne de la base de données à l'état hors ligne, en fonction du type de sauvegarde que vous spécifiez et de l'état dans lequel la base de données est.

+
Avec une sauvegarde de base de données RAC en ligne, utilisez l'option -force si l'instance locale est à l'état d'arrêt, ou si aucune instance n'est ouverte.

+

NOTE: La version d'Oracle doit être 10.2.0.5 ; sinon, la base de données sera suspendue si une instance du RAC est montée.

+
** Si l'instance locale est à l'état d'arrêt et qu'au moins une instance est ouverte, vous pouvez modifier l'instance locale pour qu'elle soit montée à l'aide de l'option -force.
** Si aucune instance n'est ouverte, vous pouvez modifier l'instance locale pour l'ouvrir à l'aide de l'option -force.


* *-protect | -noprotect | -protectnow*
+
Indique si la sauvegarde doit être protégée sur le stockage secondaire. L'option -noProtect spécifie que la sauvegarde ne doit pas être protégée sur le stockage secondaire. Seules les sauvegardes complètes sont protégées. Si aucune option n'est spécifiée, SnapManager protège la sauvegarde comme option par défaut si la sauvegarde est une sauvegarde complète et que le profil spécifie une stratégie de protection. L'option -protectnow est applicable uniquement aux Data ONTAP 7-mode. L'option indique que la sauvegarde est immédiatement protégée sur un stockage secondaire.

* *-conserver { -horaire | -quotidien | -hebdomadaire | -mensuel | -illimité}*
+
Indique si la sauvegarde doit être conservée toutes les heures, tous les jours, toutes les semaines, tous les mois ou sans limite. Si l'option -retain n'est pas spécifiée, la classe de rétention est par défaut -horaire. Pour conserver des sauvegardes permanentes, utilisez l'option -Unlimited. L'option -Unlimited rend la sauvegarde inéligible à la suppression par la stratégie de rétention.

* *-archiveils*
+
Spécifie la création d'une sauvegarde du journal d'archives.

* *-backup-dest path1, [, [path2]]*
+
Spécifie les destinations du journal d'archivage pour la sauvegarde du journal d'archivage.

* *-exclude-dest path1, [, [path2]]*
+
Spécifie les destinations du journal d'archivage à exclure de la sauvegarde.

* *-prunelogs {-all | -jusqu'à-sscnto-scn | -jusqu'à-dateyyyy-MM-DD:HH:mm:ss | -avant {-mois | -jours | -semaines | -heures}*
+
Indique si les fichiers journaux d'archives doivent être supprimés des destinations du journal d'archivage en fonction des options fournies lors de la création d'une sauvegarde. L'option -all supprime tous les fichiers journaux d'archive des destinations du journal d'archivage. L'option -jusqu'à-scn supprime les fichiers journaux d'archive jusqu'à ce qu'un numéro de changement de système (SCN) spécifié soit défini. L'option -jusqu'à-date supprime les fichiers journaux d'archive jusqu'à la période spécifiée. L'option -before supprime les fichiers journaux d'archive avant la période spécifiée (jours, mois, semaines, heures).

* *-nom-programme nom_programme*
+
Spécifie le nom que vous fournissez pour le planning.

* *-commentaire-planning_commentaire*
+
Spécifie un commentaire facultatif décrivant la planification de la sauvegarde.

* *-intervalle { -horaire | -quotidien | -hebdomadaire | -mensuel | -onetimeonly}*
+
Spécifie l'intervalle de temps par lequel les sauvegardes sont créées. Vous pouvez planifier la sauvegarde toutes les heures, tous les jours, toutes les semaines, tous les mois ou une seule fois.

* *-cronstring cron_string*
+
Spécifie la planification de la sauvegarde à l'aide de cronstring. Les expressions cron sont utilisées pour configurer des instances de CronTrigger. Les expressions cron sont des chaînes qui sont constitués des sous-expressions suivantes :

+
** 1 correspond aux secondes.
** 2 correspond aux minutes.
** 3 correspond aux heures.
** 4 correspond à un jour dans un mois.
** 5 correspond au mois.
** 6 correspond à un jour dans une semaine.
** 7 correspond à l'année (facultatif).


* *-heure-début aaaa-MM-jj HH:mm*
+
Spécifie l'heure de début de l'opération planifiée. L'heure de début de l'horaire doit être incluse au format aaaa-MM-jj HH:mm.

* *-runasuser runasuser*
+
Spécifie la modification de l'utilisateur (utilisateur root ou utilisateur Oracle) de l'opération de sauvegarde planifiée pendant la planification de la sauvegarde.

* *-taskspspspspspspspspspspspspsp
+
Spécifie le fichier XML de spécification de tâche qui peut être utilisé pour l'activité de prétraitement ou de post-traitement de l'opération de sauvegarde. Le chemin complet du fichier XML doit être fourni avec l'option -taskspspspspspspspspspec.

* *-calme*
+
Affiche uniquement les messages d'erreur dans la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche les messages d'erreur, d'avertissement et d'information dans la console.


