---
permalink: unix-administration/reference_the_smosmsap_operation_show_command.html 
sidebar: sidebar 
keywords: run, operation, show, command, list, summary, information, perform, specified, profile, smo, list 
summary: 'Vous pouvez exécuter la commande opération show pour lister les informations récapitulatives de toutes les opérations effectuées sur le profil spécifié. La sortie répertorie l"utilisateur client \(l"utilisateur pour le PC client\) et l"utilisateur effectif \(l"utilisateur dans SnapManager qui est valide sur l"hôte sélectionné\).' 
---
= Commande smo opération show
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter la commande opération show pour lister les informations récapitulatives de toutes les opérations effectuées sur le profil spécifié. La sortie répertorie l'utilisateur client (l'utilisateur pour l'ordinateur client) et l'utilisateur effectif (l'utilisateur dans SnapManager qui est valide sur l'hôte sélectionné).



== Syntaxe

[listing]
----

        smo operation show
-profile profile_name
\[-label label \| -id id\]
\[-quiet \| -verbose\]
----


== Paramètres

* *-profil nom_profil*
+
Spécifie le nom du profil. Ce nom peut comporter jusqu'à 30 caractères et doit être unique au sein de l'hôte.

* *-étiquette*
+
Spécifie le libellé de l'opération.

* *-id*
+
Spécifie l'identifiant de l'opération.

* *-calme*
+
Facultatif : affiche uniquement les messages d'erreur dans la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Facultatif : affiche les messages d'erreur, d'avertissement et d'information dans la console.





== Exemple

La ligne de commande suivante affiche des informations détaillées sur une opération :

[listing]
----
# smo operation show -profile myprofile -id ff8080811295eb1c011295eb28230001
----
[listing]
----
Operation Attempted
   Operation ID: ff8080811295eb1c011295eb28230001
   Type:RestoreFor profile: myprofile
   With Force: No
   Performed on backup
   Operation ID: ff8080811295eb1c011296eb23290001
   Label: mylabel
Operation Runtime Information
   Status: SUCCESS
   Start date: 2007-07-16 13:24:09 IST
   End date: 2007-07-16 14:10:10 IST
   Client user: amorrow
   Effective user: amorrow
Host
   Host Run upon: Host3
   Process ID: 3122
   SnapManager version: 3.3
Repository
   Connection: user1@SMOREPO/hotspur:1521
   Repository version: 3.3
Resources in use
   Volume:
     ssys1:/vol/luke_ES0_0 (FlexClone)
   Filesystems:
     /opt/NetApp/smo/mnt/-mnt_ssys1_luke_ES0_smo_e_es0_f_c_1_8abc0112129b0f81580001_0
----
*Informations connexes*

xref:task_viewing_operation_details.adoc[Affichage des détails de l'opération]
