---
permalink: unix-administration/reference_the_smosmsapoperation_dump_command.html 
sidebar: sidebar 
keywords: run, operation, dump, command, create, jar, file, diagnostic, information, smo 
summary: Vous pouvez exécuter la commande opération dump pour créer un fichier JAR qui contient des informations de diagnostic sur une opération. 
---
= Commande smo opération dump
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter la commande opération dump pour créer un fichier JAR qui contient des informations de diagnostic sur une opération.



== Syntaxe

[listing]
----

        smo operation dump
-profile profile_name
\[-label label_name \| -id guid\]
\[-quiet \| -verbose\]
----


== Paramètres

* *-profil nom_profil*
+
Spécifie le profil pour lequel vous souhaitez créer les fichiers de vidage. Le profil contient l'identifiant de la base de données et d'autres informations sur la base de données.

* *-label nom_label*
+
Crée des fichiers de vidage pour l'opération et attribue l'étiquette spécifiée.

* *-id guid*
+
Crée des fichiers de vidage pour l'opération avec le GUID spécifié. Le GUID est généré par SnapManager au démarrage de l'opération.

* *-calme*
+
Affiche uniquement les messages d'erreur dans la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche les messages d'erreur, d'avertissement et d'information dans la console.





== Exemple

L'exemple suivant crée le fichier de vidage pour la sauvegarde :

[listing]
----
smo operation dump -profile SALES1
-id 8abc01ec0e78f3e2010e78f3fdd00001
----
[listing]
----
Dump file created Path:/userhomedirectory/.netapp/smo/3.3/smo_dump_8abc01ec0e78f3e2010e78f3fdd00001.jar
----
*Informations connexes*

xref:concept_dump_files.adoc[Vider les fichiers]
