---
permalink: unix-administration/reference_the_smosmsapclone_template_command.html 
sidebar: sidebar 
keywords: command, create, clone, specification, template, smo 
summary: Cette commande permet de créer un modèle de spécification clone. 
---
= Commande de modèle de clone smo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande permet de créer un modèle de spécification clone.



== Syntaxe

[listing]
----

        smo clone template
-profile name
\[-backup-id guid  \| -backup-label backup_name\]
\[-quiet \| -verbose\]
----


== Paramètres

* *-nom de profil*
+
Spécifie la base de données dont vous souhaitez créer une spécification de clone. Le profil contient l'identifiant de la base de données et d'autres informations sur la base de données.

* *-id-sauvegarde guid*
+
Crée une spécification de clone à partir de la sauvegarde avec le GUID spécifié. Le GUID est généré par SnapManager lors de la création d'une sauvegarde. Utilisez la commande smo backup list pour afficher le GUID pour chaque sauvegarde.

* *-label-backup_label_name*
+
Crée une spécification de clone à partir de la sauvegarde avec l'étiquette de sauvegarde spécifiée.

* *-calme*
+
Affiche uniquement les messages d'erreur sur la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche des messages d'erreur, d'avertissement et d'information sur la console.





== Exemple de commande

L'exemple suivant crée un modèle de spécification de clone à partir de la sauvegarde avec l'étiquette Full_Backup_sales_May. Une fois la commande de modèle de clone smo terminée, le modèle de spécification de clone est terminé.

[listing]
----
smo clone template -profile SALES1 -backup-label full_backup_sales_May
Operation Id [8abc01ec0e79004b010e79006da60001] succeeded.
----
*Informations connexes*

xref:task_creating_clone_specifications.adoc[Création de spécifications de clonage]

xref:task_cloning_databases_from_backups.adoc[Le clonage des bases de données à partir des sauvegardes]
