---
permalink: unix-administration/reference_the_smosmsap_clone_split_command.html 
sidebar: sidebar 
keywords: clone, split, command, independent, original, snapmanager 
summary: 'Vous pouvez exécuter la commande clone Split pour séparer un clone. Le clone fractionné devient indépendant du clone d"origine. SnapManager génère un nouveau profil après l"opération de fractionnement de clone et vous pouvez utiliser ce profil pour gérer le clone divisé.' 
---
= Commande SMO clone split
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter la commande clone Split pour séparer un clone. Le clone fractionné devient indépendant du clone d'origine. SnapManager génère un nouveau profil après l'opération de fractionnement de clone et vous pouvez utiliser ce profil pour gérer le clone divisé.



== Syntaxe

[listing]
----

        smo clone split
-profile clone-profile
\[-host hostname\]
\{-label clone-label | -id clone-id\} \[-split-label split-operation_label\]
\[-comment comment\]
-new-profile new-profile-name \[-profile-password new-profile_password\]
-repository -dbname repo_service_name
-host repo_host
-port repo_port
-login -username repo_username
-database -dbname db_dbname
-host db_host \[-sid db_sid\] \[-login -username db_username -password db_password
-port db_port\]
\[-rman \{\{-controlfile \| \{-login -username rman_username
-password rman_password\} -tnsname rman_tnsname\}\}\]
-osaccount osaccount
-osgroup osgroup
\[-retain
\[-hourly \[-count n\] \[-duration  m\]\]
\[-daily \[-count n\] \[-duration m\]\]
\[-weekly  \[-count n\] \[-duration m\]\]
\[-monthly \[-count n\] \[-duration m\]\] \]
\[-profile-comment profile-comment\]
\[-snapname-pattern pattern\]
\[-protect \[-protection-policy policy_name\]\] \| \[-noprotect\]\]
\[-summary-notification
\[-notification
\[-success -email email_address1,email_address2
-subject subject-pattern\]
\[failure -email email_address1,email_address2
-subject subject-pattern\] \]
[-separate-archivelog-backups
-retain-archivelog-backups
 -hours  hours |
-days days |
-weeks weeks |
-months months
[-protect \[-protection-policy policy_name \| -noprotect]
[-include-with-online-backups \| -no-include-with-online-backups]]
[-dump]
\[-quiet \| -verbose\]
----


== Paramètres

* *-profil de clone*
+
Spécifie le nom de profil à partir duquel le clone est créé.

* *-hôte_hôte*
+
Spécifie le nom d'hôte dans lequel le clone existe.

* *-label clone*
+
Spécifie le nom de libellé généré par l'opération de clonage.

* *-id clone*
+
Spécifie l'ID unique généré par l'opération de clonage.

* *-label-split-operation_label*
+
Spécifie le nom de libellé généré par l'opération de clonage.

* *-nouveau-profil nom-nouveau-profil*
+
Spécifie le nouveau nom de profil que SnapManager va générer après une opération de fractionnement réussie.

* *-profile-password new-profile_password*
+
Spécifie le mot de passe du profil.

* *-référentiel*
+
Spécifie les détails de la base de données pour le référentiel.

* *-dbname repo_service_name*
+
Indique le nom de la base de données qui stocke le référentiel. Vous pouvez utiliser le nom global ou l'identifiant système.

* *-hôte repo_host*
+
Indique le nom ou l'adresse IP de l'ordinateur hôte sur lequel réside la base de données du référentiel.

* *-port repo_port*
+
Spécifie le numéro de port TCP (transmission Control Protocol) utilisé pour accéder à l'hôte sur lequel réside la base de données de référentiel.

* *-connexion*
+
Spécifie les détails de connexion au référentiel. Cette option est facultative. Si ce n'est pas le cas, SnapManager utilise par défaut le mode de connexion à l'authentification OS.

* *-username repo_username*
+
Indique le nom d'utilisateur requis pour accéder à l'hôte sur lequel réside la base de données du référentiel.

* *-base de données*
+
Spécifie les détails de la base de données qui sera sauvegardée, restaurée ou clonée.

* *-dbname db_dbname*
+
Indique le nom de la base de données décrit par le profil. Vous pouvez utiliser le nom global ou l'identifiant système.

* *-hôte db_host*
+
Indique le nom ou l'adresse IP de l'ordinateur hôte sur lequel réside la base de données.

* *-sid db_sid*
+
Indique l'identifiant système de la base de données décrit par le profil. Par défaut, SnapManager utilise le nom de la base de données comme identificateur système. Si l'identifiant système est différent du nom de la base de données, vous devez le spécifier à l'aide de l'option -sid.

+
Par exemple, si vous utilisez Oracle Real application clusters (RAC), vous devez spécifier l'identifiant système de l'instance RAC sur le nœud RAC à partir duquel SnapManager est exécuté.

* *-connexion*
+
Spécifie les détails de connexion à la base de données.

* *-username db_username*
+
Indique le nom d'utilisateur requis pour accéder à la base de données décrit par le profil.

* *-mot de passe db_password*
+
Spécifie le mot de passe requis pour accéder à la base de données décrit par le profil.

* *-rman*
+
Spécifie les détails qu'SnapManager utilise pour cataloguer les sauvegardes avec Oracle Recovery Manager (RMAN).

* *-controlfile*
+
Spécifie les fichiers de contrôle de base de données cibles comme référentiel RMAN au lieu d'un catalogue.

* *-connexion*
+
Spécifie les détails de connexion RMAN.

* *-mot de passe rman_mot de passe*
+
Spécifie le mot de passe utilisé pour se connecter au catalogue RMAN.

* *-username rman_username*
+
Spécifie le nom d'utilisateur utilisé pour se connecter au catalogue RMAN.

* *-tnsname nomnet*
+
Indique le nom de la connexion tnsname (défini dans le fichier tsname.ora).

* *-oscompte compte*
+
Spécifie le nom du compte utilisateur de la base de données Oracle. SnapManager utilise ce compte pour effectuer les opérations Oracle telles que le démarrage et l'arrêt. Il s'agit généralement de l'utilisateur propriétaire du logiciel Oracle sur l'hôte, par exemple oracle.

* *-groupe d'osgroup*
+
Spécifie le nom du groupe de bases de données Oracle associé au compte oracle.

+

NOTE: Les variables -osaccount et -osgroup sont requises pour UNIX mais ne sont pas autorisées pour les bases de données fonctionnant sous Windows.

* *-retain [-hourly [-count n] [-duration m]] [-daily [-count n] [-duration m]] [-hebdomadaire [-count n] [-duration m]] [-mensuel [-comptage n] [-durée m]*
+
Spécifie la stratégie de rétention pour une sauvegarde.

+
Pour chaque classe de rétention, le nombre de rétention ou la durée de conservation peuvent être spécifiés. La durée est exprimée en unités de la classe (par exemple, heures pour l'heure, jours pour la journée). Par exemple, si vous spécifiez uniquement une durée de conservation de 7 pour les sauvegardes quotidiennes, SnapManager ne limite pas le nombre de sauvegardes quotidiennes du profil (car le nombre de rétention est 0), mais SnapManager supprimera automatiquement les sauvegardes quotidiennes créées il y a plus de 7 jours.

* *-profil-commentaire-profil*
+
Spécifie le commentaire d'un profil décrivant le domaine de profil.

* *-motif-snapname*
+
Spécifie le modèle de nom pour les copies Snapshot. Vous pouvez également inclure du texte personnalisé, par exemple HAOPS pour les opérations hautement disponibles, dans tous les noms de copie Snapshot. Vous pouvez modifier le schéma de nommage des copies Snapshot lorsque vous créez un profil ou après sa création. La mise à jour s'applique uniquement aux copies Snapshot qui n'ont pas encore été créées. Les copies Snapshot qui existent conservent le modèle Snapname précédent. Vous pouvez utiliser plusieurs variables dans le texte du motif.

* *-protect -protection-policy_nom_politique*
+
Indique si la sauvegarde doit être protégée sur le stockage secondaire.

+

NOTE: Si -Protect est spécifié sans -protection-policy, le jeu de données ne dispose pas d'une règle de protection. Si -Protect est spécifié et -protection-policy n'est pas définie lors de la création du profil, il peut alors être définie ultérieurement par la commande smo profile update ou par l'administrateur du stockage en utilisant la console de protection Manager.

* *-résumé-notification*
+
Spécifie les détails de la configuration de la notification par e-mail de synthèse pour plusieurs profils sous une base de données de référentiel. SnapManager génère cet e-mail.

* *-notification*
+
Spécifie les détails de la configuration de la notification par e-mail pour le nouveau profil. SnapManager génère cet e-mail. La notification par e-mail permet à l'administrateur de base de données de recevoir des e-mails sur l'état réussi ou échoué de l'opération de base de données effectuée à l'aide de ce profil.

* *-succès*
+
Indique que la notification par e-mail est activée pour un profil pour lequel l'opération SnapManager réussit.

* *-adresse e-mail 1 adresse e-mail 2*
+
Spécifie l'adresse e-mail du destinataire.

* *-sujet-modèle*
+
Spécifie l'objet de l'e-mail.

* *-échec*
+
Indique que la notification par e-mail est activée pour un profil lorsque l'opération SnapManager échoue.

* *-séparé-archivelog-sauvegardes*
+
Spécifie que la sauvegarde du journal d'archivage est séparée de la sauvegarde du fichier de données. Il s'agit d'un paramètre facultatif que vous pouvez fournir lors de la création du profil. Une fois les sauvegardes séparées à l'aide de cette option, vous pouvez créer une sauvegarde des fichiers de données uniquement ou une sauvegarde des journaux d'archivage uniquement.

* *-conserver-archivelog-sauvegardes -heures | -jours de repos | -semaines| -mois de semaine*
+
Indique que les sauvegardes du journal d'archivage sont conservées en fonction de la durée de conservation du journal d'archivage (horaire, quotidien, hebdomadaire ou mensuel).

* *protéger [-protection-policypolitolique_name] | -noprotect*
+
Indique que les fichiers journaux d'archives sont protégés en fonction de la stratégie de protection du journal d'archivage.

+
Spécifie que les fichiers journaux d'archives ne sont pas protégés à l'aide de l'option -noProtect.

* *-inclure-avec-sauvegardes-en-ligne | -sans-inclure-avec-sauvegardes-en-ligne*
+
Indique que la sauvegarde du journal d'archivage est incluse avec la sauvegarde de base de données en ligne.

+
Indique que les sauvegardes du journal d'archivage ne sont pas incluses avec la sauvegarde de base de données en ligne.

* *-dump*
+
Indique que les fichiers de vidage ne sont pas collectés après l'opération de création de profil réussie.

* *-calme*
+
Affiche uniquement les messages d'erreur dans la console. Le paramètre par défaut affiche des messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche les messages d'erreur, d'avertissement et d'information dans la console.


