---
permalink: unix-administration/reference_the_smosmsap_clone_update_command.html 
sidebar: sidebar 
keywords: command, update, information, clone, comment, smo 
summary: Cette commande met à jour les informations relatives au clone. Vous pouvez mettre à jour le commentaire. 
---
= Commande smo clone update
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette commande met à jour les informations relatives au clone. Vous pouvez mettre à jour le commentaire.



== Syntaxe

[listing]
----

        smo clone update
-profile profile_name
\[-label label \| -id id\]
-comment  commment_text
\[-quiet \| -verbose\]
----


== Paramètres

* *-profil nom_profil*
+
Spécifie le nom du profil contenant le clone à mettre à jour. Le profil contient l'identifiant de la base de données et d'autres informations sur la base de données.

* *-id*
+
Spécifie l'ID du clone. L'ID est généré par SnapManager lors de la création d'un clone. Utilisez la commande smo clone list pour afficher l'ID de chaque clone.

* *-étiquette*
+
Spécifie le libellé du clone.

* *-commentaire*
+
Affiche le commentaire saisi dans le clone de création. Ce paramètre est facultatif.

* *-calme*
+
Affiche uniquement les messages d'erreur sur la console. La valeur par défaut est d'afficher les messages d'erreur et d'avertissement.

* *-verbose*
+
Affiche des messages d'erreur, d'avertissement et d'information sur la console.





== Exemple de commande

L'exemple suivant met à jour le commentaire sur le clone.

[listing]
----
smo clone update -profile anson.pcrac5
-label clone_pcrac51_20080820141624EDT -comment See updated clone
----