---
permalink: unix-administration/task_configuring_e_mail_notification_for_a_new_profile.html 
sidebar: sidebar 
keywords: creating, new, profile, configure, receive, email, notification, completeion, database, operation, comma-seperated, list, multiple, address 
summary: 'Lorsque vous créez un nouveau profil, vous pouvez configurer pour recevoir une notification par e-mail à la fin de l"opération de base de données.' 
---
= Configuration de la notification par e-mail pour un nouveau profil
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous créez un nouveau profil, vous pouvez configurer pour recevoir une notification par e-mail à la fin de l'opération de base de données.

* Vous devez configurer l'adresse e-mail à partir de laquelle les alertes sont envoyées.
* Vous devez utiliser une liste séparée par des virgules pour plusieurs adresses électroniques.
+
Vous devez vous assurer qu'il n'y a pas d'espace entre la virgule et l'adresse e-mail suivante.

+
.. Entrez la commande suivante : smo profile create -profileprofile [-profile-passwordprofile_password] -repository-dbnamerepo_service_name-hostrepo-host-portrepo-port-login-usernamerpo-database-dbnamedb_nomdhostdb_host [-groupedaterm-nomdeamb] [-nom-nomdeamerideb] [-nom-nomdeameridaydaydaydayr] [-nomdeb] [-nomdeamb-nomdeb-nomdeb-nomdeamb] [-nomdeb] [-nom-nomdetadaydaydaydaydaydaydaydaydaydaydaydaydaynomdeb] [-nomdeb] [-nomdeb-nomdeb] [-nomdeb-nomdeb-nomdeb-nomdeb-nomdeb-nomdeb-nomdeb] [-nomdeb-nomdeb-nomdeb-nomdeb-nomdeamb-nomdeb-nomde
+
Les autres options de cette commande sont les suivantes :

+
[-force]

+

NOTE: SnapManager prend en charge jusqu'à 1000 caractères pour les adresses e-mail.

+
Lorsque vous créez une sauvegarde des fichiers de données et des fichiers journaux d'archive ensemble à l'aide du profil (pour la création de sauvegardes de journaux d'archive séparés) et que la création de la sauvegarde du fichier de données échoue, la notification par e-mail est envoyée avec la sauvegarde des données comme nom de l'opération au lieu de la sauvegarde des journaux d'archivage et de sauvegarde des données. Lorsque l'opération de sauvegarde du fichier de données et du fichier journal d'archives réussit, le résultat s'affiche comme suit :

+
[listing]
----

Profile Name    : PROF_31
Operation Name 	: Data Backup and Archive Logs Backup
Database SID   	: TENDB1
Database Host 	 : repo1.rtp.org.com
Start Date 	    : Fri Sep 23 13:37:21 EDT 2011
End Date 	      : Fri Sep 23 13:45:24 EDT 2011
Status 	        : SUCCESS
Error messages 	:
----




L'exemple suivant montre la notification par e-mail configurée lors de la création d'un nouveau profil :

[listing]
----

smo profile create -profile sales1 -profile-password sales1 -repository -dbname repo2 -host 10.72.197.133 -port 1521 -login -username oba5 -database -dbname DB1 -host 10.72.197.142 -sid DB1 -osaccount oracle
-osgroup dba -notification -success -email admin1@org.com -subject {profile}_{operation-name}_{db-sid}_{db-host}_{start-date}_{end-date}_{status}
----