---
permalink: unix-administration/task_authorizing_user_access_to_the_repository.html 
sidebar: sidebar 
keywords: addition, role-based, access, control, rbac, snapmanager, enable, credential, database, user, repository, authorizing 
summary: 'En plus du contrôle d"accès basé sur des rôles \(RBAC\), SnapManager vous permet de définir des informations d"identification pour les utilisateurs de base de données afin d"accéder au référentiel. À l"aide des informations d"identification, vous pouvez restreindre ou empêcher l"accès aux hôtes, référentiels, profils et bases de données SnapManager.' 
---
= Autorisation de l'accès au référentiel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Outre le contrôle d'accès basé sur des rôles (RBAC), SnapManager vous permet de définir les identifiants pour les utilisateurs de base de données afin d'accéder au référentiel. À l'aide des informations d'identification, vous pouvez restreindre ou empêcher l'accès aux hôtes, référentiels, profils et bases de données SnapManager.

Si vous définissez les informations d'identification à l'aide de la commande dataset, SnapManager ne vous invite pas à entrer un mot de passe.

Vous pouvez définir les informations d'identification de l'utilisateur lors de l'installation de SnapManager ou d'une version ultérieure.

. Saisissez la commande suivante :
+
'jeu d'informations d'identification mo -référentiel -nombd repo_nom_service -hôte repo_hôte -login -nom_utilisateur repo_nom_utilisateur [-mot_de_passe_référentiel] -port repo_port'


