---
permalink: unix-administration/task_using_snapmanager_for_oracle_to_create_the_database_profile_and_assign_a_protection_policy.html 
sidebar: sidebar 
keywords: create, profile, snapmanager, oracle, enable, protect, client, payroll, paydb 
summary: Vous devez créer un profil dans SnapManager pour Oracle, activer la protection dans le profil et attribuer une règle de protection pour créer une sauvegarde protégée. 
---
= Utilisation de SnapManager pour Oracle pour créer le profil de base de données et affecter une stratégie de protection
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez créer un profil dans SnapManager pour Oracle, activer la protection dans le profil et attribuer une règle de protection pour créer une sauvegarde protégée.

Un profil contient des informations sur la base de données gérée, notamment ses informations d'identification, ses paramètres de sauvegarde et ses paramètres de protection pour les sauvegardes. Après avoir créé un profil, vous n'avez pas besoin de spécifier les détails de la base de données chaque fois que vous effectuez une opération. Un profil ne peut référencer qu'une seule base de données, mais cette même base de données peut être référencée par plusieurs profils.

. Accédez au client SnapManager pour Oracle.
. Dans l'arborescence des référentiels, cliquez avec le bouton droit de la souris sur l'hôte et sélectionnez *Créer un profil*.
. Sur la page informations sur la configuration du profil, entrez les détails du profil et cliquez sur *Suivant*.
+
Vous pouvez entrer les informations suivantes :

+
** Nom du profil : Paypaie_prod2
** Mot de passe du profil: Payroll123
** Commentaire : base de données paie de production


. Dans les pages informations sur la configuration de la base de données, entrez les détails de la base de données, puis cliquez sur *Suivant*.
+
Vous pouvez entrer les informations suivantes :

+
** Nom de la base de données : PAYDB
** SID de base de données : payrolldb
** Hôte de base de données : acceptez la valeur par défaut. Comme vous créez un profil à partir d'un hôte dans l'arborescence du référentiel, SnapManager affiche le nom de l'hôte.
** Compte hôte, représentant le compte utilisateur Oracle : oracle
** Groupe hôte, représentant le groupe Oracle : dba


. Sur la page informations de connexion à la base de données, cliquez sur *utiliser l'authentification de base de données* pour permettre aux utilisateurs de s'authentifier à l'aide des informations de base de données.
. Entrez les détails de la connexion à la base de données et cliquez sur *Suivant*.
+
Vous pouvez entrer les informations suivantes :

+
** SYSDBA Privileged User Name, représentant l'administrateur de la base de données système disposant de privilèges d'administration : sys
** Mot de passe (mot de passe SYSDBA) : oracle
** Port de connexion à l'hôte de base de données : 1521


. Sur la page informations sur la configuration RMAN, cliquez sur *n'utilisez pas RMAN* et cliquez sur *Suivant*.
+
Oracle Recovery Manager (RMAN) est un outil Oracle qui vous aide à sauvegarder et à restaurer vos bases de données Oracle à l'aide d'une détection au niveau des blocs.

. Sur la page informations d'attribution de nom d'instantané, spécifiez une convention d'attribution de nom pour les snapshots associés à ce profil en sélectionnant des variables.
+
La variable smid crée un identifiant de snapshot unique.

+
Effectuez les opérations suivantes :

+
.. Dans la liste jeton variable, sélectionnez texte utilisateur et cliquez sur *Ajouter*.
.. Entrez payroll.techco.com_ comme nom d'hôte et cliquez sur *OK*.
.. Cliquez sur *Left* jusqu'à ce que le nom d'hôte apparaisse juste après smo dans la zone format.
.. Cliquez sur *Suivant*.


+
La convention de nommage des snapshots de smo_hostname_smoprofile_dbsid_scope_mode_smid devient "smo_payroll.techco.com_payroll_prod2_payrolldb_f_a_x" (où "f" indique une sauvegarde complète, "a" indique le mode automatique et "x" représente le SMID unique).

. Sélectionnez *protection Manager protection Policy*.
+
*Protection Manager protection Policy* permet de sélectionner une règle de protection qui a été configurée à l'aide de NetApp Management Console.

. Sélectionnez *TechCo données de paie : sauvegarde* comme règle de protection dans les règles de protection extraites de la console de gestion NetApp, et cliquez sur *Next*.
. Sur la page effectuer une opération, vérifiez les informations et cliquez sur *Créer*.
. Cliquez sur *Operation Details* pour afficher des informations sur l'opération de création de profil et les informations d'éligibilité à la restauration basée sur le volume.
+
** L'attribution d'une règle de protection NetApp Management Console au profil de base de données crée automatiquement un jeu de données non conforme, visible par l'opérateur de la console de gestion NetApp, avec le nom de convention smo_<hostname>_<profilName>, ou dans cet exemple : smo_payroll.tech.com_PAYDB.
** Si le profil n'est pas éligible pour la restauration de volume (également appelée « restauration rapide »), les événements suivants se produisent :
+
*** L'onglet *Résultats* indique que la création du profil a réussi et que des avertissements se sont produits pendant l'opération.
*** L'onglet *Operation Details* contient un journal D'AVERTISSEMENT, qui indique que le profil n'est pas éligible pour la restauration rapide et explique pourquoi.





