---
permalink: unix-administration/task_configuring_snapmanager_for_oracle_with_veritas_file_system.html 
sidebar: sidebar 
keywords: snapmanager, install, solaris, configure, veritas, storage, foundation, oracle, rac, sfrac, environment 
summary: 'Lorsque SnapManager est installé sur Solaris, vous pouvez configurer SnapManager pour prendre en charge l"environnement Veritas Storage Foundation for Oracle RAC \(SFRAC\).' 
---
= Configuration de SnapManager pour prendre en charge l'environnement Veritas SFRAC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque SnapManager est installé sur Solaris, vous pouvez configurer SnapManager pour prendre en charge l'environnement Veritas Storage Foundation for Oracle RAC (SFRAC).

* Solaris, utilitaires hôtes et Veritas doivent être installés sur l'hôte.
+
.. Créez un groupe de disques partagé et un système de fichiers pour SnapManager à l'aide de SnapDrive pour UNIX afin que les systèmes de fichiers soient montés simultanément sur les deux nœuds de Real application clusters (RAC).
+
Pour plus d'informations sur la création d'un groupe de disques et d'un système de fichiers partagés, reportez-vous à la documentation SnapDrive.

.. Installez et configurez la base de données Oracle à monter sur les systèmes de fichiers partagés.
.. Démarrez une instance de base de données sur un nœud du RAC.




http://mysupport.netapp.com/["Documentation sur le site de support NetApp : mysupport.netapp.com"]
