---
permalink: unix-administration/task_cloning_databases_from_backups.html 
sidebar: sidebar 
keywords: clone, database, backup, using, clone, create, command, sid, snapmanager 
summary: 'Vous pouvez cloner une base de données à partir d"une sauvegarde à l"aide de la commande clone create.' 
---
= Le clonage des bases de données à partir des sauvegardes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez cloner une base de données à partir d'une sauvegarde à l'aide de la commande clone create.

Vous devez d'abord créer un fichier de spécifications de clone pour la base de données. SnapManager crée le clone sur la base des informations contenues dans ce fichier de spécifications.

Vous devez attribuer un nouvel identifiant système Oracle au clone. Vous ne pouvez pas exécuter deux bases de données avec le même SID simultanément sur le même hôte. Un clone peut être installé sur un autre hôte utilisant le même SID. Pour désigner un nom unique pour le clone, utilisez -label. Si vous n'utilisez pas cette option, SnapManager crée un nom unique pour le clone, qui inclut le SID, la date et l'heure.

Une fois que vous avez cloné une base de données, vous pouvez mettre à jour vos fichiers tnsnames.ora sur vos ordinateurs clients avec les nouvelles informations de connexion de base de données clonées. Les fichiers tnsnames.ora sont utilisés pour se connecter à une instance Oracle sans avoir à spécifier les informations complètes de la base de données. SnapManager ne met pas à jour les fichiers tnsnames.ora.

SnapManager crée toujours une sauvegarde comprenant les fichiers journaux d'archive, si vous utilisez le profil créé avec -include-with-online-backups. SnapManager vous permet de cloner uniquement les sauvegardes complètes de base de données.

SnapManager (3.2 ou version ultérieure) vous permet de cloner les sauvegardes contenant les fichiers de données et les fichiers journaux d'archivage.

Si le journal d'archivage est disponible à partir d'un emplacement externe, vous pouvez spécifier l'emplacement externe pendant le clonage pour restaurer la base de données clonée à un état cohérent. Vous devez vous assurer que l'emplacement externe est accessible par Oracle. Le clonage des sauvegardes de journaux d'archives uniquement n'est pas pris en charge.

Bien que la sauvegarde du journal d'archivage soit créée avec la sauvegarde partielle en ligne, vous ne pouvez pas créer de clone de base de données à l'aide de cette sauvegarde.

Vous pouvez cloner la sauvegarde de la base de données à partir de l'emplacement du fichier journal d'archives externe uniquement pour une base de données autonome.

Le clonage de la sauvegarde de base de données en ligne de la base de données RAC (Real application clusters) à l'aide de l'emplacement du fichier journal d'archives externe échoue en raison d'un échec de restauration. Ceci est dû au fait que la base de données Oracle ne parvient pas à trouver et à appliquer les fichiers journaux d'archive pour la récupération à partir de l'emplacement du journal d'archivage externe pendant le clonage de la sauvegarde de la base de données.

Vous pouvez spécifier l'option -dump en tant que paramètre facultatif afin de collecter les fichiers de dump après l'opération de création de clone réussie ou échec.

*Clonage de sauvegarde de fichier de données sans sauvegarde de journal d'archivage*

Lorsque la sauvegarde des fichiers de données n'inclut pas la sauvegarde du journal d'archivage, SnapManager for Oracle clone la base de données en fonction du numéro de changement du système (SCN) enregistré lors de la sauvegarde. Si la base de données clonée ne peut pas être restaurée, le message d'erreur « Archived log for thread <number> and change <SCN> required to Complete Recovery error » (fichier journal archivé pour le thread <number>) s'affiche, même si SnapManager for Oracle continue à cloner la base de données et a finalement réussi à créer le clone.

Lors du clonage à l'aide de la sauvegarde des fichiers de données sans inclure la sauvegarde du journal d'archivage, SnapManager récupère la base de données clonée jusqu'au dernier SCN du journal d'archivage, qui est enregistré pendant la sauvegarde.

. Créer un fichier de spécification clone.
. Pour créer un clone, entrez la commande suivante : smo clone create -backup-labelbackup_name-newsidNew_sid-labelclone_label-profilprofile_name-clonesplein_chemin_to_clonespecfile [-specspec] [-recover-from-location] path1 [,<2> tasket1] [...]


*Informations connexes*

xref:task_cloning_databases_in_the_current_state.adoc[Clonage des bases de données dans l'état actuel]

xref:concept_considerations_for_cloning_a_database_to_an_alternate_host.adoc[Considérations relatives au clonage d'une base de données vers un autre hôte]

xref:task_creating_clone_specifications.adoc[Création de spécifications de clonage]

xref:reference_the_smosmsapclone_create_command.adoc[Commande smo clone create]

xref:task_creating_pretask_post_task_and_policy_scripts.adoc[Création de scripts de stratégie, de post-tâche et de prétâche]

xref:concept_variables_available_in_the_task_scripts_for_clone_operation.adoc[Les variables disponibles dans les scripts de tâches pour l'opération de clonage]

xref:task_creating_task_scripts.adoc[Création de scripts de tâches]

xref:task_storing_the_task_scripts.adoc[Stockage des scripts de tâche]
