---
permalink: unix-administration/task_cloning_a_database_to_an_alternate_host.html 
sidebar: sidebar 
keywords: clone, create, command, database, backup, alternate, host, cloning, exist 
summary: Vous pouvez utiliser la commande clone create pour cloner une sauvegarde de base de données sur un autre hôte. 
---
= Clonage d'une base de données vers un autre hôte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser la commande clone create pour cloner une sauvegarde de base de données sur un autre hôte.

* Créer un profil ou avoir un profil existant.
* Créez une sauvegarde complète ou bénéficiez d'une sauvegarde de base de données existante.
* Créez une spécification de clone ou possédez une spécification de clone existante.
+
.. Pour cloner une base de données sur un autre hôte, entrez la commande suivante : smo clone create -backup-label backup_label nom-newsid New_sid-host target_host-label clone_label-commentairetext-profileprofile_name-clonespec Full_path_to_clonespecfile
+
Oracle ne vous permet pas d'exécuter deux bases de données avec le même SID simultanément sur le même hôte. Pour cette raison, vous devez fournir un nouveau SID pour chaque clone. Cependant, vous pouvez avoir une base de données sur un autre hôte avec le même SID.





*Informations connexes*

xref:task_creating_profiles.adoc[Création de profils]

xref:task_cloning_databases_from_backups.adoc[Le clonage des bases de données à partir des sauvegardes]

xref:task_creating_clone_specifications.adoc[Création de spécifications de clonage]

xref:reference_the_smosmsapclone_create_command.adoc[Commande smo clone create]
