---
permalink: unix-administration/task_using_snapmanager_for_oracle_to_create_the_database_profile_for_a_local_backup.html 
sidebar: sidebar 
keywords: database, administrator, snapmanager, create, profile, backup, local, oracle 
summary: 'Les administrateurs de base de données utilisent SnapManager pour créer un profil de base de données qui sera utilisé pour lancer une sauvegarde sur du stockage local sur un système de stockage primaire. La création de profils et les processus de sauvegarde sont entièrement exécutés dans SnapManager, mais ils n"impliquent pas protection Manager.' 
---
= Utilisation de SnapManager pour Oracle pour créer le profil de base de données pour une sauvegarde locale
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les administrateurs de base de données utilisent SnapManager pour créer un profil de base de données qui sera utilisé pour lancer une sauvegarde sur du stockage local sur un système de stockage primaire. La création de profils et les processus de sauvegarde sont entièrement exécutés dans SnapManager, mais ils n'impliquent pas protection Manager.

Un profil contient les informations relatives à la base de données gérée, notamment ses informations d'identification, ses paramètres de sauvegarde et ses paramètres de protection pour les sauvegardes. En créant un profil, vous n'avez pas besoin de spécifier les détails de la base de données chaque fois que vous effectuez une opération sur cette base de données, mais il vous suffit de fournir le nom du profil. Un profil ne peut référencer qu'une seule base de données. Cette même base de données peut être référencée par plusieurs profils.

. Accédez au client SnapManager pour Oracle.
. Dans l'arborescence des référentiels SnapManager, cliquez avec le bouton droit de la souris sur l'hôte que vous souhaitez associer à ce profil et sélectionnez *Créer un profil*.
. Dans la page informations sur la configuration du profil, entrez les informations suivantes et cliquez sur *Suivant*.
+
** Nom du profil : Paypay_prod
** Mot de passe du profil: Payroll123
** Commentaire : base de données paie de production


. Dans la page informations sur la configuration de la base de données, entrez les informations suivantes et cliquez sur *Suivant*.
+
** Nom de la base de données : PAYDB
** SID de base de données : payrolldb
** Hôte de base de données : acceptez la valeur par défaut
+
Comme vous créez un profil à partir d'un hôte dans l'arborescence du référentiel, SnapManager affiche le nom de l'hôte.



. Dans la deuxième page informations sur la configuration de la base de données, acceptez les informations suivantes de la base de données et cliquez sur *Suivant* :
+
** Compte hôte, représentant le compte utilisateur Oracle : oracle
** Groupe hôte, représentant le groupe Oracle : dba


. Dans la page Database Connection information (informations de connexion à la base de données), sélectionnez *Use database Authentication* (utiliser l'authentification de la base de données) pour permettre aux utilisateurs de s'authentifier à l'aide des informations
+
Dans cet exemple, entrez les informations suivantes et cliquez sur *Suivant*.

+
** SYSDBA Privileged User Name, représentant l'administrateur de la base de données système disposant de privilèges d'administration : sys
** Mot de passe (mot de passe SYSDBA) : oracle
** Port de connexion à l'hôte de base de données : 1521


. Dans la page informations sur la configuration RMAN, sélectionnez *n'utilisez pas RMAN* et cliquez sur *Suivant*.
+
Oracle Recovery Manager (RMAN) est un outil Oracle qui vous aide à sauvegarder et à restaurer vos bases de données Oracle à l'aide d'une détection au niveau des blocs.

. Dans la page informations d'attribution de nom d'instantané, spécifiez une convention d'attribution de nom pour les snapshots associés à ce profil en sélectionnant des variables. La seule variable requise est la variable *smid*, qui crée un identifiant de snapshot unique.
+
Pour cet exemple, procédez comme suit :

+
.. Dans la liste jeton variable, sélectionnez la variable *{usertext}* et cliquez sur *Ajouter*.
.. Entrez "payroll.techco.com_" comme nom d'hôte et cliquez sur *OK*.
.. Cliquez sur *Left* jusqu'à ce que le nom d'hôte apparaisse juste après "smo" dans la zone format.
.. Cliquez sur *Suivant*.


+
La convention de nommage des snapshots de smo_hostname_smoprofile_dbsid_scope_mode_smid devient "smo_payroll.techco.com_payroll_prod2_payrolldb_f_a_x" (où le "f" indique une sauvegarde complète, le "a" indique le mode automatique et le "x" représente le SMID unique).

. Sur la page effectuer une opération, vérifiez les informations et cliquez sur *Créer*.
. Cliquez sur *Operation Details* pour afficher des informations sur l'opération de création de profil et les informations d'éligibilité à la restauration basée sur le volume.

