---
permalink: unix-administration/task_using_protection_manager_to_configure_a_secondary_backup_protection_policy.html 
sidebar: sidebar 
keywords: configuring, backup, schedule, storage, administrator, configure, protect 
summary: 'Après avoir configuré le planning de sauvegarde, l"administrateur du stockage configure une stratégie de stockage de sauvegarde protégée dans laquelle ce planning doit être inclus.' 
---
= Utilisation de protection Manager pour configurer une stratégie de protection de sauvegarde secondaire
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir configuré le planning de sauvegarde, l'administrateur du stockage configure une stratégie de stockage de sauvegarde protégée dans laquelle ce planning doit être inclus.

Avant de configurer la règle de protection, l'administrateur du stockage confère au partenaire DBA les informations suivantes :

* Durée de conservation à spécifier pour le stockage secondaire
* Type de protection de stockage secondaire requis


La stratégie de protection créée peut être répertoriée dans SnapManager pour Oracle par le partenaire de l'administrateur de bases de données, et attribuée à un profil de base de données pour les données à protéger.

. Accédez à la console de gestion NetApp de protection Manager.
. Dans la barre de menus, cliquez sur *stratégies* > *protection* > *Présentation*.
+
L'onglet Présentation de la fenêtre stratégies de protection s'affiche.

. Cliquez sur *Ajouter une stratégie* pour lancer l'assistant Ajouter une stratégie de protection.
. Exécutez l'assistant en procédant comme suit :
+
.. Spécifiez un nom de stratégie descriptif.
+
Dans cet exemple, entrez *données de paie TechCo : sauvegarde* et une description, puis cliquez sur *Suivant*.

.. Sélectionnez une stratégie de base.
+
Pour cet exemple, sélectionnez *Sauvegarder* et cliquez sur *Suivant*.

.. Dans la feuille de propriétés de la stratégie de noeud de données principal, acceptez les paramètres par défaut et cliquez sur *Suivant*.
+

NOTE: Dans cet exemple, la planification de sauvegarde locale configurée dans SnapManager est appliquée. Tout programme de sauvegarde local spécifié à l'aide de cette méthode est ignoré.

.. Dans la feuille de propriétés connexion données primaires à sauvegarde, sélectionnez un programme de sauvegarde.
+
Dans cet exemple, sélectionnez *Payroll Saturday à 1 AM plus Daily à 7 PM* comme programme de sauvegarde, puis cliquez sur *Next*.

+
Dans cet exemple, la planification que vous avez sélectionnée inclut à la fois les horaires hebdomadaires et quotidiens que vous avez configurés précédemment.

.. Dans la feuille de propriétés de la stratégie de sauvegarde, spécifiez le nom du nœud de sauvegarde et les temps de conservation pour les sauvegardes quotidiennes, hebdomadaires ou mensuelles.
+
Dans cet exemple, indiquez une durée de conservation quotidienne des sauvegardes de 10 jours et une durée de conservation hebdomadaire des sauvegardes de 52 semaines. Après avoir terminé chaque feuille de propriétés, cliquez sur *Suivant*.

+
Une fois toutes les feuilles de propriétés terminées, l'assistant Ajout de stratégie de protection affiche une feuille récapitulative pour la stratégie de protection que vous souhaitez créer.



. Cliquez sur *Terminer* pour enregistrer vos modifications.


La politique de protection * données de paie TechCo : sauvegarde* figure parmi les autres politiques configurées pour protection Manager.

Le partenaire de l'administrateur de bases de données peut désormais utiliser SnapManager for Oracle pour répertorier et affecter cette stratégie lors de la création du profil de base de données pour les données à protéger.
