---
permalink: unix-administration/task_adding_new_profile_to_summary_notification.html 
sidebar: sidebar 
keywords: configure, summary, email, notification, repository, database, add, new, profile 
summary: 'Après avoir configuré une notification de synthèse par e-mail pour la base de données du référentiel, vous pouvez ajouter un nouveau profil à la notification de synthèse à l"aide de la commande de notification de synthèse.' 
---
= Ajout d'un nouveau profil aux notifications par e-mail récapitulatives
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir configuré une notification de synthèse par e-mail pour la base de données du référentiel, vous pouvez ajouter un nouveau profil à la notification de synthèse à l'aide de la commande de notification de synthèse.

. Entrez la commande suivante : smo profile create -profileprofile_name [-profile-passwordprofile_password] -repository-dbnamerepo_service-hostrepo-host-portrepo-port-login-usernamerepo-database-dbnamedb_nomddb_nom_hôte [-nomdeport] [-nomdecompte] [-nomdecompte_mid-nomdeb] [-nomdecompte] [-nomdecompte_nomdecompte] [] [-nomdecompte_nomdecompte_nomdecompte_nomdecompte] [] [-nomdecompte_nomdecompte_nomdeutilisateur] [-nomdecompte_nomdecompte_nomdecompte_nom_decompte_decompte_nomdecompte] [] [] [-nomdecompte_nomdecompte_nom_nomdecompte_nom_nom_nom_nom_nom_nom_nom_nom_nom_nom_nom_nom_nom_nom_nom_nom_nom_nom_nom_nom_nom_nom_nom_nom_nom_nom_nom_nom_nom_nom_de
+
Les autres options de cette commande sont les suivantes :

+
[-force]


