---
permalink: unix-installation-cmode/delete_reference_trademark.html 
sidebar: sidebar 
keywords: trademark, information 
summary: marques commerciales, informations 
---
= Informations sur les marques commerciales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


NetApp, le logo NetApp , Go Further, Faster, AltaVault, ASUP, AutoSupport, Campaign Express, Cloud ONTAP, Clustered Data ONTAP, Customer Fitness, Data ONTAP, DataMotion, Fitness, Flash Accel, Flash Cache, Flash Pool, FlashRay, FlexCache, FlexClone, FlexPod, FlexScale, FlexShare, FlexVol, FPolicy, GetSuccessful, LockVault, Manage ONTAP, Mars, MetroCluster, MultiStore, NetApp Insight, OnCommand, ONTAP, ONTAPI, RAID DP, RAID-TEC, SANtricity, SecureShare, Simplicity, Simulate ONTAP, Snap Creator, SnapCenter, SnapCopy, SnapDrive, SnapIntegrator, SnapLock, SnapManager, SnapMirror, SnapMover, SnapProtect, SnapRestore, Snapshot SnapValidator, SnapVault, StorageGRID, Tech OnTap, Unbound Cloud et WAFL , ainsi que d'autres noms, sont des marques commerciales ou des marques déposées de NetApp, Inc., aux États-Unis et/ou dans d'autres pays. Toutes les autres marques ou produits sont des marques commerciales ou des marques déposées de leurs détenteurs respectifs et doivent être traités comme tels.  Une liste actualisée des marques déposées de NetApp est disponible sur le site web suivant : http://www.netapp.com/us/legal/netapptmlist.aspx[] .
