---
permalink: unix-installation-cmode/task_backing_up_your_database.html 
sidebar: sidebar 
keywords: creating, profile, back, up, database, schedule, recurring, database, initial, verification, unix, snapmanager 
summary: Après avoir créé un profil, vous devez sauvegarder votre base de données. Vous pouvez planifier des sauvegardes récurrentes après la sauvegarde et la vérification initiales. 
---
= Sauvegarde de votre base de données
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir créé un profil, vous devez sauvegarder votre base de données. Vous pouvez planifier des sauvegardes récurrentes après la sauvegarde et la vérification initiales.

Ces étapes montrent comment créer une sauvegarde de votre base de données à l'aide de l'interface utilisateur de SnapManager. Si vous préférez, vous pouvez également utiliser l'interface de ligne de commandes.

Pour plus d'informations sur la création de sauvegardes à l'aide de la CLI, reportez-vous au _SnapManager for Oracle Administration Guide for UNIX_.

. Dans l'arborescence des référentiels, cliquez avec le bouton droit de la souris sur le profil contenant la base de données à sauvegarder, puis sélectionnez *Backup*.
. Dans *Label*, entrez un nom personnalisé pour la sauvegarde.
+
Vous ne devez pas inclure d'espaces ou de caractères spéciaux dans le nom. Si vous ne spécifiez pas de nom, SnapManager crée automatiquement une étiquette de sauvegarde.

+
À partir de SnapManager 3.4, vous pouvez modifier l'étiquette de sauvegarde créée automatiquement par SnapManager. Vous pouvez modifier les variables de configuration override.default.backup.pattern et new.default.backup.pattern pour créer votre propre modèle de libellé de sauvegarde par défaut.

. Dans *SnapVault Label*, vous devez entrer l'étiquette SnapMirror que vous avez spécifiée dans les règles de la règle SnapMirror lors de la configuration de la relation SnapVault.
+

NOTE: Le champ *étiquette SnapVault* apparaît uniquement si vous avez sélectionné _SnapManager_cdot_Vault_ comme stratégie de protection lors de la création du profil.

. Sélectionnez *Autoriser le démarrage ou l'arrêt de la base de données, si nécessaire*, pour modifier l'état de la base de données, si nécessaire.
+
Cette option garantit que si la base de données n'est pas à l'état requis pour créer une sauvegarde, SnapManager place automatiquement la base de données à l'état souhaité pour terminer l'opération.

. Sur la page base de données, tablespaces ou fichiers de données à sauvegarder, effectuez les opérations suivantes :
+
.. Sélectionnez *Sauvegarder les fichiers de données* pour sauvegarder la base de données complète, les fichiers de données sélectionnés ou les espaces de stockage sélectionnés.
.. Sélectionnez *Backup Archivelugs* pour sauvegarder les fichiers journaux d'archive séparément.
.. Sélectionnez *Prune Archivelugs* si vous souhaitez supprimer les fichiers journaux d'archives du système de fichiers actif qui est déjà sauvegardé.
+

NOTE: Si la zone de récupération Flash (FRA) est activée pour les fichiers journaux d'archive, SnapManager ne parvient pas à nettoyer les fichiers journaux d'archive.

.. Sélectionnez *protéger la sauvegarde* si vous souhaitez activer la protection de sauvegarde.
+
Cette option n'est activée que si la stratégie de protection a été sélectionnée lors de la création du profil.

.. Dans la liste déroulante *Type*, sélectionnez le type de sauvegarde (hors ligne ou en ligne) que vous souhaitez créer.
+
Si vous sélectionnez Auto, SnapManager crée une sauvegarde basée sur l'état actuel de la base de données.

.. Dans la liste déroulante *classe de rétention*, sélectionnez la classe de rétention.
.. Cochez la case *vérifier la sauvegarde à l'aide de l'utilitaire Oracle DBVERIFY* si vous souhaitez vous assurer que les fichiers sauvegardés ne sont pas corrompus.


. Sur la page activation des tâches, indiquez si vous souhaitez effectuer des tâches avant et après la fin des opérations de sauvegarde.
. Sur la page effectuer une sauvegarde, vérifiez les informations et cliquez sur *Sauvegarder*.
. Cliquez sur *Terminer* pour fermer l'assistant.
+
Si l'opération échoue, cliquez sur *Détails de l'opération* pour voir ce qui a provoqué l'échec de l'opération.



*Informations connexes*

https://library.netapp.com/ecm/ecm_download_file/ECMP12471546["Guide d'administration SnapManager 3.4 for Oracle pour UNIX"]
