---
permalink: unix-installation-7mode/delete_reference_trademark.html 
sidebar: sidebar 
keywords: trademark 
summary: Informations sur les marques commerciales 
---
= Informations sur les marques commerciales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


NetApp, le logo NetApp, Go further, faster, AltaVault, ASUP, AutoSupport, Campaign Express, Cloud ONTAP, clustered Data ONTAP Customer Fitness, Data ONTAP, DataMotion, Fitness, Flash Accel, Flash cache, Flash Pool, FlashRay, FlexArray, FlexCache, FlexClone, FlexPod, FlexScale, FlexShare, FlexVol, FPolicy, GetSuccessful, LockVault, gérer ONTAP, Mars, MetroCluster, MultiStore, NetApp Insight, OnCommand, ONTAP, ONTAPI, RAID DP, RAID-TEC, SANtricity, SecureShare, Simplicité, Simulate ONTAP, Snap Creator, SnapCenter, SnapCopy, SnapDrive, SnapIntegrator, SnapLock, SnapManager, SnapMirror, SnapMover, SnapProtect, SnapRestore, Snapshot, SnapValidator, SnapVault, StorageGRID, Tech OnTap, Unbound Cloud, WAFL et d'autres noms sont des marques déposées ou des marques commerciales de NetApp, Inc. Aux États-Unis et/ou dans d'autres pays. Tous les autres noms de produit ou de marque sont des marques, déposées ou non, de leur propriétaire respectif et doivent être considérés comme telles. La liste des marques de NetApp est disponible sur la page Web, à l'adresse http://www.netapp.com/us/legal/netapptmlist.aspx[].
